### ISSUE TITLE
✨ Video Embed - Vimeo support

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1016]
cc @tiagov8 

As part of the perfomance optimisations for issue #910 the video embed component was replaced but Vimeo functionality was removed.

```[tasklist]
### Tasks
- [x] Replace Vimeo links with YouTube
- [x] Check with TV Team - do we need vimeo support?
- [ ] If yes, implement
```

_Originally posted by @tiagov8 in https://github.com/SSWConsulting/SSW.Website/issues/1002#issuecomment-1632894075_

**Comment by bradystroud** [comment]
We might need vimeo support as we do some client videos there, but for now youtube is enough. Moving this to the backlog as it is low priority
