### ISSUE TITLE
✨ Page - Company index

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1020]
https://www.ssw.com.au/ssw/Company/Default.aspx

```[tasklist]
### Tasks
- [x] Create a collection for this page
- [x] Create the template
- [x] Add visual editing
- [x] Get it approved from designer
- [x] Update Mega menu link
- [x] Add Front Door redirect
```

**Comment by amankumarrr** [comment]
<img width="1272" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/ddba00ec-d4c7-46a5-8865-6e0789fe924f">

**Figure: Company Index page - v2** 

<img width="240" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/ee4f5226-3d06-49a9-a879-e1d784efe1eb">

**Figure: Mobile view - Company Index page - v2**
