### ISSUE TITLE
🐛 Breadcrumb - Assuming all page types have index page

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1037]
**To Reproduce**
1. Go to https://www.ssw.com.au/training/internship-fullstack
2. Click `Training` in the breadcrumb
3. 404 - It takes you to `https://www.ssw.com.au/training` which doesn't exist

**Expected behavior**
If there is no index page, it should not be a link

![image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/3a5150df-bf03-4034-a486-2fd95f130bee)

```[tasklist]
### Tasks
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/1059
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/1055
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/1056
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/1058
```

**Comment by bradystroud** [comment]
As discussed with @amankumarrr we will remove the breadcrumbs from these pages until we have an index page

**Comment by jeoffreyfischer** [comment]
✅ Done - Fixed by removing the 'training' breadcrumb
