### ISSUE TITLE
♻️ Move Angular Superpowers to /events

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1054]
```[tasklist]
### Tasks
- [x] Create new template
- [x] Move it to /events
- [x] Move any related images
- [x] Add a redirect for this change
- [x] Update MegaMenu link
```
