### ISSUE TITLE
Index page for /events

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1056]
As per my conversation with @camillars this page should allow users to link to certain events. These links should scroll to the event.

This page will need to fetch data from the SharePoint events (e.g. User Groups), and the training events in Tina (e.g. Superpowers)

```[tasklist]
### Tasks
- [x] Migrate the page https://www.ssw.com.au/ssw/Events/?tech=all&type=all
- [x] Keep the same filters avaliable
- [x] Each event should also be an anchor link
```

**Comment by Harry-Ross** [comment]
Is that this page - https://www.ssw.com.au/ssw/Events/?tech=all&type=all?

**Comment by camillars** [comment]
> Is that this page - https://www.ssw.com.au/ssw/Events/?tech=all&type=all?
Yes :)
