### ISSUE TITLE
✨ New Page - Company | History

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1074]
Migrate this page https://www.ssw.com.au/ssw/Company/History/

New URL should be /company/history

There are other pages that will use the same template, so keep that in mind when building it.

This history timline should be a seperate component

```[tasklist]
### Tasks
- [x] Build the new template
- [x] Build the timeline component, should be editable in Tina
- [x] Add redirect in FrontDoor
- [x] Update megamenu link
```

**Comment by Harry-Ross** [comment]
As per https://github.com/SSWConsulting/SSW.FrontDoor/pull/80 and https://github.com/SSWConsulting/SSW.Website.Menu.json/pull/91, the FrontDoor and megamenu updates are done
