### ISSUE TITLE
✨ Presenters - Source them from SSW.People

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1080]
#### Description:
Currently, we are manually adding the content and profile images of presenters from [SSW.People](https://github.com/SSWConsulting/SSW.People), we need to find a way to make them a source of truth (E.g. a new field "blurb" on SSW.People.Profiles)
Ideally it should have the first 1 or 2 paragraphs

```[tasklist]
### Tasks
- [x] setup cron job to copy people profiles from ssw.people to local repo
- [x] profiles should be processed to reduce the amount of data being stored e.g. remove unnecessary fields, use first 1-2 paragraphs as profile
- [x] copy profile picture
- [x] People - create an API endpoint that contains people's info and returns a .json payload
```

**Comment by tkapa** [comment]
Some issues that I have already run into:

- SSW.People.Profiles includes Alumni
- People doesn't contain a field in the .md that denotes someone as Alumni, it is compared against CRM data. We can't easily filter out Alumni from the data
- There's also a slight data issue, because everyone also has badges and images at the top of their profile, making it slightly harder to grab the good information to add as an about section.

If we don't mind grabbing everyone that is in People.Profiles then that is fine, and we can just go ahead.

**Comment by tkapa** [comment]
As per my conversation with @wicksipedia, it's not a big worry to pull in Alumni from the People Repo as we'll eventually be able to search for references in Tina.
