### ISSUE TITLE
📃 Docs - Creating a new [filename] route

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1093]
As per my conversation with @amankumarrr, the system for creating a new collection is not apparently clear. 

```[tasklist]
### Tasks
- [x] Create docs that reference how to create a new `[filename].tsx` route
- [x] Reference the new query that has to be written in `queries.gql` with the `...LayoutQueryFragment` part
- [x] Add the boilerplate required to create the page (i.e. the `getStaticProps` and `getStaticPaths`
```

**Comment by Harry-Ross** [comment]
Done - https://github.com/SSWConsulting/SSW.Website/wiki/Developing-Pages-with-TinaCMS#creating-new-route-templates

Pending @amankumarrr's approval

**Comment by amankumarrr** [comment]
looks good, easy to read the instructions.
