### ISSUE TITLE
🐛 Employment Opportunity - Adding in Tina doesn't update UI

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1157]
**Describe the bug**

**To Reproduce**
1. Go to https://www.ssw.com.au/admin/index.html#/~/employment
2. Add an opportunity
4. Tina editor shows the new role, but the UI does not

**Expected behavior**

<img width="1800" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/38869720/b584bbfb-51df-4dd1-9faf-402cc20a020a">

```[tasklist]
### Tasks
- [x] Verify the useEffect change in the comment below fixed the display issue
- [x] Then refactor to remove the status value from the opportunities schema - have the status be determined by the ranking of opportunities on the employment page
- [x] Rewrite documentation w/ new functionality + redo done video
```

**Comment by Harry-Ross** [comment]
I believe this can be fixed by adding `opportunities` to the `useEffect` dependency array (along with the filtered variables) in opportunities.tsx.

**Comment by Harry-Ross** [comment]
Done - updated the documentation at https://github.com/SSWConsulting/SSW.Website/wiki/Editing-the-website#editing-and-creating-employment-opportunities
