### ISSUE TITLE
🐛 WebApp Slots - Old PR slots are still running  

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1175]
**Describe the bug**
We currently have 3 active PRs, but from the resources, it seems like 9 slots that have been running, which implies that some pipelines are not working as expected or need to be cleaned up some old slots to avoid extra cost. 

**Expected behavior**
For every active PR, there should be a slot that gets deleted when it gets merged.  

<img width="667" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/c419456d-4023-47ec-848f-36e8c4bf0e21">

**Figure: SSW website's 9 slots that are running** 

```[tasklist]
### Tasks
- [x] Investigate the issue
- [x] Fix the issue
- [x] Clean up the slots and associated roles
```

**Comment by amankumarrr** [comment]
@wicksipedia  @bradystroud 

Hi Team,

On investigation, it appears that some of the pull request (PR) slots have been running for the past 2 months. It seems that in certain cases, when PRs were closed manually without merging them, their respective slots were not deleted. However, this issue was not observed with every PR, for example, PR #901.

It has been challenging to pinpoint the exact cause of this issue. However, we have taken action to clean up the unused resources. Moving forward, we should implement a weekly check on our resources and closely monitor the checks to ensure they run as expected.

<img width="928" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/d8e24dc7-6e02-4b2b-bedb-f3f562fd2308">

**Figure: First slot that was closed manually back in 26th May**


<img width="920" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/a5aadca3-b7e0-43f0-a059-123db323f0f6">

**Figure: PR that was automatically closed by merging still had a slot running**

<img width="798" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/37c5dce3-6722-4b84-8479-e75f8c7390c6">

**Figure: Slots after cleaning up**

**Comment by amankumarrr** [comment]
@wicksipedia  @bradystroud 

On further investigation, I found a way to reproduce this by the following steps:

1. Create a Pull request
2. Close the Pull request instantly 
3. **PR close check** will be triggered and it will fail because by that time there wouldn't be any deployed slot
4. In the background, it will deploy the slot and will remain there until we manually delete the slot

**Comment by amankumarrr** [comment]
@wicksipedia  @bradystroud 

This issue has been addressed, and now we have a weekly check to clean up the slots that are abandoned through our GitHub action.


![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/7051b541-9a8b-4b81-9bae-13ba1003d310)

**Figure: Flow that runs on weekly basis**
