### ISSUE TITLE
✨ New Feature - Table Component 

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1187]
As per my conversation with @pierssinclairssw, it would be good if we could have a dedicated table component to be used in the TinaCMS, as the current UI for editing the `TableLayout` component is a bit clunky. 

```[tasklist]
### Tasks
- [ ] Create a custom form component (saves as an object) for table editing using elements from https://github.com/Harry-Ross/tinacms-components/blob/main/custom-file-upload.tsx
- [ ] Research publishing the component as an NPM package
- [ ] Test please from Piers
```

**Comment by bradystroud** [comment]
@Harry-Ross I'm confused why you need the file upload feature... Can the table component not just be a Custom field component? https://tina.io/docs/extending-tina/custom-field-components/

**Comment by Harry-Ross** [comment]
@bradystroud - no file upload feature is needed, it just has some logic that could be borrowed that is left out of Tina's custom field component page i.e. calling `input.onChange(data)` to commit data to TinaCMS.

**Comment by Harry-Ross** [comment]
As per my conversation with @pierssinclairssw + @bradystroud, this issue is low priority until v1 pages are migrated.
