### ISSUE TITLE
💄 UI - Broken Text Colour on Newsletters

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1192]
**Describe the bug**
![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/4e70ef97-d8de-41c6-b401-94e6a911405e)

```[tasklist]
### Tasks
- [ ] Fix broken text on /newsletters
- [ ] Confirm fixing text has not impacted https://www.ssw.com.au/?liveBanner=1&liveStream=1
- [ ] Make sure it doesn't effect the styling on the homepage
```
