### ISSUE TITLE
📄 Inconsistent SSW Red

### ISSUE THREAD

**Issue by hveraus** [SSWConsulting/SSW.Website#1201]
Creating this issue to doc some inconsistent SSW red been used across ssw.com.au
```[tasklist]
### Tasks
- [ ] Change Call us button to SSW Red (#CC4141)
- [ ] The main SSW logo's svg file color are little bit off, might be something happened during export, please replace with the one below (see 2nd comment)
```

**Comment by hveraus** [comment]
<img width="1387" alt="Screenshot 2023-08-09 at 2 27 50 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/4745861/2352640c-25fb-4fd3-a42a-b7ac64882f8f">

- [ ] 1. Change Call us button to SSW Red (#CC4141)

**Note:** Youtube icon is OK

**Comment by hveraus** [comment]
<img width="704" alt="Screenshot 2023-08-09 at 3 05 35 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/4745861/a10c0723-4e63-4134-ba69-f00a78f2e2c3">

- [ ] 2. The main SSW logo's svg file color are little bit off, might be something happened during export, please replace with the one below

![ssw-logo](https://github.com/SSWConsulting/SSW.Website/assets/4745861/5957319f-3682-469f-8364-bf966614c07c)
