### ISSUE TITLE
📄SSW Hangzhou and SSW Strasbourg Directions - add Close-up Map image

### ISSUE THREAD

**Issue by vladislav-kir** [SSWConsulting/SSW.Website#1204]
URLs: 
- https://www.ssw.com.au/offices/strasbourg#Directions
- https://www.ssw.com.au/offices/hangzhou#Directions

**Screenshots**
![image](https://github.com/SSWConsulting/SSW.Website/assets/54652701/ef5caeb2-ec0c-4713-a036-c44bffd7ee0b)
**Figure: Change Strasbourg Google Maps with Close-up Map image**

![image](https://github.com/SSWConsulting/SSW.Website/assets/54652701/166fac0c-6da9-4c1c-aeec-0418d86f8edf)
**Figure: Change Hangzhou Google Maps with Close-up Map image**

**Additional context**
Related to [SSW Coding Challenge project](https://github.com/orgs/SSWConsulting/projects/21/views/15) - [🎨 Get assets created to update the location info for SSW Hangzhou and SSW Strasbourg#212](https://github.com/SSWConsulting/SSW.CodingChallengeReimagined/issues/212)

@Geordie88 created the required assets.
They can be found here: [Close-Maps](https://sswcom.sharepoint.com/sites/SSWDESIGN/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=kIjENU&cid=6fe87dab%2D18fa%2D4ee0%2Da27c%2D8352490b91b1&RootFolder=%2Fsites%2FSSWDESIGN%2FShared%20Documents%2FGeneral%2FProject%2DSSWWebsite%2FOffices%2Dmaps%2FClose%2DMaps&FolderCTID=0x012000B6BF72AABC74FE4B945D57002722E9F0)

```[tasklist]
### Tasks
- [x] Change Strasbourg Google Maps with Close-up Map image
- [x] Change Hangzhou Google Maps with Close-up Map image
- [x] Test Strasbourg page with Jean
- [x] Test Hangzhou page with Alvin
```
