### ISSUE TITLE
♻️ Update "Superior Software for Windows" to be be "SSW"

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1205]
Cc: @adamcogan @wicksipedia 

Hi @bradystroud 

### Pain
On Google results I am seeing the deprecated "Superior Software for Windows". I only noticed in the past couple of days:
<img width="886" alt="Screen Shot 2022-12-19 at 12 37 30 PM" src="https://user-images.githubusercontent.com/12601228/208517104-28ff2749-91db-4bf5-bcb1-b8155ee22016.png">

### What code could be improved?
Update the term as per https://my.sugarlearning.com/SSW/items/8150/the-important-terms-and-formats-at-ssw?term=superior 

### Tasks
- [x] Find from where the term is coming from
- [x] Update to be "SSW"

Thanks!

**Comment by tiagov8** [comment]
Hey @bradystroud Any updates on this one?

FYI - @MattParkerDev has also reported this same issue

**Comment by bradystroud** [comment]
Hey @tiagov8 

It looks like this is effecting all results under the ssw.com.au domain, not just SSW.Rules.

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/38869720/236084470-d7818fed-d770-4401-9309-7c8bfe9b5da1.png">


---

https://developers.google.com/search/docs/appearance/site-names#how-site-names-in-google-search-are-created

According to these docs, there are 4 places where Google might get the site name.

- [WebSite structured data](https://developers.google.com/search/docs/appearance/site-names#website)
- Content in <title> elements
- Heading elements, such as \<h1\> elements
- og:site_name

I have checked all these

## WebSite structured data

On the new SSW Website (ssw.com.au), we already have the correct structured data

![image](https://user-images.githubusercontent.com/38869720/236123595-1b80267c-9e36-4496-a571-90da085b13f1.png)
**Figure: Structured data as recommended by google**

I checked the search console, and this page is being indexed so google should be aware of it

## Content in <title> elements

Our title is `SSW Consulting - .NET, Web, Mobile, CRM, SharePoint, Azure, Power BI, Angular, React, Office 365 and Dynamics` on the new and old website
Maybe google won't use this because of the length?

## Heading elements, such as \<h1\> elements
There are lots of these, none of them are Superior Software for Windows

## og:site_name

New website - SSW Consulting
Old website - doesn't have one

---

I did a search for `Superior Software for Windows` on the old and new website source code but couldn't find anywhere that name is used.

Updating the registrant info will probably have no effect. The docs don't appear to look at that.

https://www.ssw.com.au/ssw/Company/ContactUs.aspx#EFT



---


Next steps

- [x] Make meta tags consistent

**Comment by bradystroud** [comment]
As per my convesation with @camillars 

To fix this issue, I am going to change the title of the home page to be "SSW - Enterprise Software Development" and the name in the structured data to also be "SSW - Enterprise Software Development"

The title is currently `SSW Consulting - .NET, Web, Mobile, CRM, SharePoint, Azure, Power BI, Angular, React, Office 365 and Dynamics` really long and has lots of keywords in it.

Theses are also in the description, so I dont think there is any harm in removing them from the title.

Currently this is inconsistent which could be causing the problem.

- [x] Update title
- [x] Request a recrawl
- [x] Test in 2 days - is it fixed?

**Comment by bradystroud** [comment]
Automatically closed by the PR

Reopening as its not done

**Comment by tiagov8** [comment]
Hi All, 

FYI - I am trying to claim and fix these occurences on the web:

- https://www.yellowpages.com.au/nsw/neutral-bay/superior-software-for-windows-ssw-14600639-listing.html
- https://www.truelocal.com.au/business/superior-software-for-windows-ssw/neutral-bay
- https://www.cylex-australia.com/company/superior-software-for-windows-pty-ltd-18573600.html
- https://www.yelp.com/biz/superior-software-for-windows-neutral-bay-2

**Comment by tiagov8** [comment]
FYI - I had a chat with ChatGPT about this... The deprecated name is out there but can't figure out from where

> What company is behind ssw.com?

> ChatGPT:
> As of my knowledge cutoff in September 2021, I do not have specific information about the company behind ssw.com, as there could be multiple companies with similar names or acronyms. To determine the company behind ssw.com, it is best to visit the website directly and look for information about the company or contact details provided on the site. Additionally, conducting an internet search using the full name or further context about ssw.com may provide more insights into the company behind it.

> what about ssw.com.au

> ChatGPT
> SSW (Superior Software for Windows) is a well-known software development company based in Australia. The domain ssw.com.au is associated with SSW. They offer a range of services including software development, consulting, and training. SSW has been operating since 1990 and has worked with numerous clients across various industries. They are known for their expertise in Microsoft technologies and provide solutions for web, mobile, and desktop applications. If you are looking for more specific information about SSW and their services, I recommend visiting their official website at ssw.com.au.

> where did you get "Superior Software for Windows" from?

> ChatGPT
> I apologize for the incorrect information in my previous response. The acronym "SSW" does not stand for "Superior Software for Windows." I apologize for any confusion caused. Without further information, I cannot determine the exact meaning of "SSW" or the specific company associated with ssw.com.au. It is advisable to visit the website directly or conduct an internet search for more accurate and up-to-date information.

**Comment by bradystroud** [comment]
Hey all,

This is still an issue.
I am working with the SysAdmins to update our registrant info which currently says "Superior Software for Windows"

**Comment by bradystroud** [comment]
@camillars @tiagov8 @wicksipedia @MattParkerDev 

Update - We were not able to change the registrant info since the company is still called Superior Software for Windows in the ABR (Australian Business Register)

We are working on changing the name to SSW (or similar, names must be unique) in the ABR.

**Comment by ricksu978** [comment]
It looks like a lot of our old pages/files with "Superior Software for Windows" are cached on Google. 
This could lead to Google misinterpreting our company name. 
Maybe we could start removing those deprecated pages/files.

## How to check all pages indexed on Google
Try Google search with the following query. **Note:** the double quote is important
```
"superior software for windows" site:ssw.com.au
```
![Google Search Screen Shot](https://github.com/SSWConsulting/SSW.Website/assets/35659961/c0dcef7f-51d4-4e81-9db4-07e9739229f9)
**Figure: Google result showing all indexed pages**

**Comment by tiagov8** [comment]
Few updates:

- The 1st result for [Contact Us page](https://www.ssw.com.au/ssw/Company/ContactUs.aspx) has already been fixed 
- I [created a PR](https://github.com/SSWConsulting/SSW.Rules.Content/pull/6320) to fix the one in the rule "[Comments - Do you have brand at the top of each file?](https://www.ssw.com.au/rules/have-brand-at-the-top-of-each-file/)"
- I fixed the [Privacy Policy page](https://www.ssw.com.au/ssw/company/privacy.aspx) and sent an email to Cameron to check content. Subject: **SSW Privacy Policy - Old page**

**Comment by ricksu978** [comment]
> **Note:** The 1st result has already been fixed - https://www.ssw.com.au/ssw/Company/ContactUs.aspx

For each page we want to fix, there will be 2 steps involved.
1. Remove "Superior Software for Windows" on the page. (This is done for Contact Us page)
2. Ask Google to re-index the page via Google Search Console (**this step is important**).

**Comment by tiagov8** [comment]
> 2. Ask Google to re-index the page via Google Search Console (this step is important).

Done for both "Contact Us" and "Privacy" pages (will action after every page I fix)

<img width="1167" alt="Screenshot 2023-08-11 at 9 11 28 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/dc33a161-63d5-4b58-a8c7-445df53e6b81">

**Comment by camillars** [comment]
> > 2. Ask Google to re-index the page via Google Search Console (this step is important).
> 
> Done for both "Contact Us" and "Privacy" pages (will action after every page I fix)
> 
> <img alt="Screenshot 2023-08-11 at 9 11 28 AM" width="1167" src="https://user-images.githubusercontent.com/12601228/260059209-dc33a161-63d5-4b58-a8c7-445df53e6b81.png">

Tiago,

have you already tried this before? or was this the first time that you requested the info to be indexed?

**Comment by tiagov8** [comment]
Hey @camillars 

> have you already tried this before? or was this the first time that you requested the info to be indexed?

(A bit unclear...) I have used this feature before on other pages and sites, but this was the first time for this specific info we just updated.

PS. I am not 100% on how long it takes to get updated results

**Comment by ricksu978** [comment]
> PS. I am not 100% on how long it takes to get updated results

Hi @tiagov8 
From my experience, it usually take 1 to 5 days to get a page re-indexed. However, I double checked the details on the search result page, the indexed page is actually in `http://` and we have requested `https://` to be re-indexed, this is probably why it hasn't updated yet.

1. Could you submit another re-index request with URL: `http://www.ssw.com.au/ssw/Company/ContactUs.aspx`

![image](https://github.com/SSWConsulting/SSW.Website/assets/35659961/59e14a7c-49e3-4124-97f1-e1873caf1d5d)
Figure: Google search result showing indexed was in `http://`

**Comment by tiagov8** [comment]
@ricksu978 

> 1. Could you submit another re-index request with URL: http://www.ssw.com.au/ssw/Company/ContactUs.aspx

Done

<img width="1175" alt="Screenshot 2023-08-17 at 4 24 50 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/000cf10a-7c2d-46dc-a81d-2bc3f482a900">

**Comment by bradystroud** [comment]
@tiagov8 @ricksu978 @camillars @adamcogan @leahy268 
Hey All,

DONE 🎊
This was a tough issue, but I learned so much about SEO and we fixed a ton of SEO issues on the website so I’m super happy I got to work on it.

It required help from 10+ people, so thanks everyone!

<img width="1015" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/38869720/9fec4118-2fd9-45ac-ae06-303f78fec8ef">

**Figure: Google search results no longer shows deprecated name**
