### ISSUE TITLE
💸💄 Tech Debt - Components - add preview images 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1246]
Template: `/events/*`

**Description:**
For our event's template, we are not showing the preview images for all of the available components, each component should have its preview image.

**Screenshots**
<img width="255" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/37abc292-f3f1-4601-ab66-831814a3e67f">

**Figure: Components that are without preview** 

```[tasklist]
### Tasks
- [x] ensure all components have preview images
```

**Comment by jeoffreyfischer** [comment]
@Calinator444 you marked this PBI as Done, however:
- [ ] it's not assigned to anyone
- [ ] there's no closing comment on the PBI
- [ ] there's no closing comment on the related PR
- [ ] the task in the PBI have not been ticked off

Please reopen the PBI, fix all these comments, and then close it.

**Comment by Calinator444** [comment]
@wicksipedia 

Here's a screenshot of the preview images in production

![Image](https://github.com/user-attachments/assets/fc2a1c9f-ee63-493c-a01d-f22f1e8bd38a)

Note: I couldn't get the following components to render in Tina und thus couldn't add preview image for them

- Hero
- Citation
- Dynamic Column Layout
- Join As Presenter
- Organizer
- Vertical Image Layout
