### ISSUE TITLE
✨Company page - Contact US

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1256]
URL: https://www.ssw.com.au/ssw/Company/ContactUs.aspx

**Description:**
We need to migrate this page asap as it has still the inquiry form that is pointing to the old endpoint, which creates the record into CRM but there is no email to be sent out. 

<img width="1017" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/bc047b88-670c-4edd-8806-e6d46b201592">

**Figure: Contact us page - referencing old inquiry form**
```[tasklist]
### Tasks
- [x] Update the Company's template
- [x] Migrate the content to Contact
- [x] Update Megamenu
- [x] Add redirect in Front Door
```

**Comment by amankumarrr** [comment]
@bradystroud @wicksipedia 

As per my conversation with @UlyssesMaclaren, we don't need the right side content, and need to make the form more prominent. This is most important page for our website, therefore, it needs to be redesigned.

**Comment by amankumarrr** [comment]
**Screenshots:**
<img width="949" alt="header1" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/4088b529-741b-4129-94cd-2ad590fc4971">
<img width="947" alt="header2" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/3c290ead-74e5-4ba8-9825-9b6802f56300">
**Figure: Contact Us page new look** 


<img width="233" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/7f05062a-ef7a-4110-a993-77efc9580757">

**Figure: Contact us page in mobile view**

**Comment by wicksipedia** [comment]
I think it would look better if the EFT table in the mobile view had text vertically centered. The `Account Name`, `BSB`, `Account Number`, and `SWIFT Number` look odd sitting at the top

**Comment by amankumarrr** [comment]
@wicksipedia right, I just fixed it with this #1287 

<img width="352" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/d8e608f6-5aaa-4a21-a07f-c44755bb628f">

**Figure: EFTs details vertically center aligned**
