### ISSUE TITLE
📄 Company Pages - Testimonials

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1258]
https://www.ssw.com.au/ssw/Testimonials/default.aspx

As discussed with Aman, we can use the existing Testimonials collection for this page.
We should exclude the FBC/Internship testimonial categories.
Most of these wont have images - this is fine.

```[tasklist]
### Tasks
- [x] Migrate page
- [x] Migrate old testimonials to the Tesimonial collection
- [x] Add redirect
- [x] Update MegaMenu inside website (mockData.ts)
- [x] Update old MegaMenu on https://github.com/sswconsulting/ssw.website.menu.json
```

**Comment by KristenHu** [comment]
1. Update MegaMenu inside website (mockData.ts) - https://github.com/SSWConsulting/SSW.Website/pull/1632
2. Update old MegaMenu on https://github.com/sswconsulting/ssw.website.menu.json - https://github.com/SSWConsulting/SSW.Website.Menu.json/pull/106
