### ISSUE TITLE
📄 Migration - Track Migrated Pages

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1263]
As we migrate pages from the old website, they should be zz'ed in a duplicate/separate branch of the v1 website. This way we can track whats been migrated and what is left

```[tasklist]
### Tasks
- [x] zz consulting pages
- [x] zz offices pages
- [x] zz any other pages we have migrated
- [x] Create issues for pages that haven't been migrated (check that they dont already exist)
- [x] Create Excel spreadsheet with pages migrated + to migrate
- [ ] Reply done to "Re: SSW Web API - Where it should be used"
```

If there are any pages that dont look relevant to migrate, check with @wicksipedia then zz them if he agrees

**Acceptance Criteria**
- Every page has been 
    - migrated then zz'ed
    - The PO's have agreed to not migrate it, then zz'ed
    - moved to a new issue (and linked)

**Comment by wicksipedia** [comment]
@bradystroud I’d double check that this won’t break any links on the old site before zz’ing the

are there case studies under the consulting folder? G(and have they been migrated?)

**Comment by Harry-Ross** [comment]
Created a repo to track progress on the v3 site here: https://github.com/SSWConsulting/SSW.Website-v1-Progress

**Comment by Harry-Ross** [comment]
As per my conversation with @adamcogan, I will download to HTML and then move:

* Training 
* Events
* Old products pages (i.e. DataPro, SQLAuditor)
* Standards 


To the public folder under `/history`.

**Comment by Harry-Ross** [comment]
Update:

Created a script to save HTML files from ssw.com.au using the v1 website's file structure, and saves all related images on the page. See below example where I have saved ssw.com.au/ssw/WisePRO:


![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/c784152a-0ed0-4244-836e-27831ad60336)
**Figure: Archived WisePRO page**

I've also got it working with all AccessReporter and DataMergePRO pages - which means it should work with all ASPX pages to be archived in HTML form.

**Comment by bradystroud** [comment]
cc @adamcogan @wicksipedia 
@Harry-Ross 

Just to confirm, the plan is to migrate all pages to static HTML, host them in Blob Storage (or simply in the public folder of the new site) then zz those pages on the old website as a shortcut to turning off the old VM.

Is this correct?
Who approved this decision? (Adam and/or Matt W)

**Comment by Harry-Ross** [comment]
The plan - as set out to me by Adam in the Sprint 39 Review would be to create a `/history` folder *only* for approved routes (e.g. standards, old products, etc.) so that we could store old pages that are not in use anymore. This is not a solution to zz every page on the old website, only the ones that we know don't need functionality and will only be stored purely for archival/history reasons. 

This is set out in the comment above: https://github.com/SSWConsulting/SSW.Website/issues/1263#issuecomment-1790158409

Saving these pages as HTML probably isn't ideal for pages with interactivity and ones in current use - this is only for old pages that people don't use. 

As discussed with you yesterday, the best approach to store the old pages for archival reasons would either be using Azure Static Web Apps or Azure Storage and then using Front Door to direct `/history` requests to the correct place.

**Comment by Harry-Ross** [comment]
cc @JeanThirion 

Update:

1. The new number after running my archive script on the approved routes is now 648/1001 - these 400 archived pages will be deployed to Azure Static Web Apps, as the size of the folder is only 200 MB
2. A spreadsheet to track progress has been created in the SSW Website Teams channel called todos.xlsx:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/6b7109a6-25f7-4786-add9-8c7898f906e4)
**Figure: the XLSX file added to the team**

This XLSX file was converted from a CSV file generated by the `todo_outputter_csv.py` in https://github.com/SSWConsulting/SSW.Website-v1-Progress

**Comment by Harry-Ross** [comment]
Created issues for new pages at:

https://github.com/SSWConsulting/SSW.Website/issues/1694
https://github.com/SSWConsulting/SSW.Website/issues/1693

**Comment by jeoffreyfischer** [comment]
I have created an Excel file that list all the pages (.aspx and .html) that need to be migrated. 
It also provides an estimate of the remaining time needed.

📊 Migration - Current status | migrate all the remaining pages (.aspx and .htm)

- ✅ 387 pages already migrated/archived
- 🚧 242 pages to migrate
- 💾 3935 pages to archive (🏎️ thanks to Harry's Python script)

The 2 big jobs are: 
- /Standards: these are a bunch of old rules. If Adam agrees to migrate them to history, it should take 25 days. If not, it will take 400 days.
- /Redirect: there are around 3000 pages in there. I tested a few and most of them seem to be 404. If we just ignore them, we save another 300 days.

Link: https://sswcom.sharepoint.com/:x:/s/SSWWebsitev3/EXeGN4n3zZRCuj6F1jwWueEBC7zCjGD0SaNOvj38S3mdyg?e=o7gxJZ

**Comment by jeoffreyfischer** [comment]
/Redirect - As per my conversation with Matt, I am investigating how many of the pages in /Redirect generate a Status Code>400.
This will help us refine the number of pages we can ignore in this folder.

**Comment by jeoffreyfischer** [comment]
/Redirect - I have an estimate of the status code for each page, see https://sswcom.sharepoint.com/:x:/s/SSWWebsitev3/ETEdLS1F5rtKrsbC9jJjIvkBbXoFdh7IRjrod6ThvWUVPA?e=PV4zlS

In summary:
- 1753 pages have a 200 code
- 476 pages have a 4** code (between 400 and 499)
- 13 pages have a 5** code (between 500 and 599)
- 626 pages have an error with no code (timeout, nameResolutionError, etc.)
