### ISSUE TITLE
📄 Content - Create a Next.js Consulting Page

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1302]
As per my conversation with @adamcogan + @wicksipedia, we think it would be great to have a Next.js consulting page to attract Next.js clients. 

```[tasklist]
### Tasks
- [x] Create a Next.js consulting page on `/consulting/nextjs`
- [ ] Test please from Adam + Uly
- [x] Add to megamenu
```

**Comment by Harry-Ross** [comment]
As per my conversation with @bradystroud, the next step is to set up a meeting w/ skilled Next.js developers in the company.

>set up a meeting with @wicksipedia , @william-liebenberg, @christoment, @bradystroud 
>Agenda - best way to host NextJS on Azure
>Once thats solved, we can make a consulting page and make a bunch of awesome nextjs websites
