### ISSUE TITLE
📄 zz Hololens experience page

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1315]
URL: https://www.ssw.com.au/ssw/Events/HoloLens-experience.aspx

**Description:**
~Need to migrate this page. It has a form that is pointing to the old create lead endpoint which is only responsible for creating a record in CRM. (CRM doesn't dispatches any email notification anymore )
Remove all the COVID related content and ask @camillars for any other content change.~

See discussion below - dont need to migrate this page

```[tasklist]
### Tasks
- [x] Redirect this page to the hololens consulting page https://www.ssw.com.au/consulting/microsoft-hololens
- [x] zz It on the old website
```

**Comment by camillars** [comment]
Hi @sethdailyssw 
cc: @camillars 

1. please review the content of this page
2. make content suggestions in a word doc
3. get it checked by me and @UlyssesMaclaren 

Thanks

**Comment by sethdaily** [comment]
@camillars 
1. please review the content of this page
3. make content suggestions in a word doc
4. get it checked by me and @UlyssesMaclaren

All done - only made grammar changes as per Uly's suggestion (check it if you want to)

Hey @amankumarrr 
1.  Keep the format and style of the original page
2. Use the text in this doc - [Updated content](https://sswcom-my.sharepoint.com/:w:/g/personal/sethdaily_ssw_com_au/EQXepEVJL7JJtzF9qzXpZsgBz83YGGMOpEBrXpWyn3Ry2w?e=csVe5n).

**Comment by bradystroud** [comment]
As discussed with @UlyssesMaclaren @camillars @amankumarrr 

We are not going to migrate this page


- [ ] @sethdailyssw - Mention we can do a demo of Microsoft HoloLens in the consulting page https://www.ssw.com.au/consulting/microsoft-hololens
- [x] Redirect the event page to the new consulting page https://www.ssw.com.au/consulting/microsoft-hololens 
- [ ] @sethdailyssw - SEO
- [x] zz it on the old website

I've updated the tasks in the issue and send and email to @sethdailyssw

**Comment by amankumarrr** [comment]
@bradystroud @camillars @UlyssesMaclaren @bradystroud 

We have implemented the Front Door redirection for this page as the booking form on that page was not functioning.

**Comment by camillars** [comment]
@sethdaily 
cc myself @camillars 

1. any updates?

**Comment by amankumarrr** [comment]
Closing this issue as I have created a separate issue for the remaining tasks with issue #2399
