### ISSUE TITLE
DevOps - Application Insights - Clean Failed requests

### ISSUE THREAD

**Issue by vladislav-kir** [SSWConsulting/SSW.Website#1318]
Based on email chain:

From: Adam Cogan [SSW]
Sent: Friday, 25 August 2023 at 2:21 pm
To: Vlad Kireyev [SSW] 
Cc: Matt Wicks [SSW], Brady Stroud [SSW], John Xu [SSW], Warwick Leahy [SSW], Gordon Beeming [SSW], William Liebenberg [SSW]
Subject: DevOps - TimePro - Failed requests

```[tasklist]
### Tasks
- [x] Write KUSTO query to remove noise
- [x] Show the updated Failed Requests graph
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/1344
- [x] Record Done Video - make it generic so it can reused for the rule
- [x] Other projects might have this problem - Write a rule on this
- [x] Add Probing Attempts chart to Dashboard
```

**Comment by vladislav-kir** [comment]
A ton of failures happen for /_next/data/{{Something goes here}}/en/consulting.json.

Digging into into showed that it happens from prefetch requests on https://www.ssw.com.au/



![Image](https://github.com/SSWConsulting/SSW.Website/assets/54652701/357aae69-07e3-4456-9986-3c2992917e51)
Figure: Seems like the Link for Rules is the source of error.

Do not see why only this prefetch does not work yet, but I think this could be fixed in code after further investigation

Will discuss with other devs

**Comment by vladislav-kir** [comment]
Another frequent Failed Request kind is for the requests with names like "GET /icons/android-chrome-{{dimentions}}.png"

These are thrown whenever someone is going to [SSW Rules site](https://www.ssw.com.au/rules/)

These kinds of icons can be accessed by the https://www.ssw.com.au/rules/icons... 

However, they are looked up automatically in the path https://www.ssw.com.au/icons... (notice the missing /rules directory)

**Comment by vladislav-kir** [comment]
I opened a new issue in the SSW Rules backlog - [🐛 Bug - SSW Rules - 404 requests from icons#1096](https://github.com/SSWConsulting/SSW.Rules/issues/1096)

As per my conversation with @JackDevAU, he will fix it.

**Comment by vladislav-kir** [comment]
Created the following Rule: https://www.ssw.com.au/rules/clean-failed-requests/

Recorded v1 of the Video: https://www.youtube.com/watch?v=r70oalOZqAk&ab_channel=VladislavKireyev
