### ISSUE TITLE
📄 Content - Migrate All Case Study Pages

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1328]
```[tasklist]
### Tasks
- [x] New TinaCMS schema
- [x] New page template
- [x] Create PBIs for each case study
- [x] ~Migrate all case study pages found on https://www.ssw.com.au/ssw/Company/Clients/~ Created a milestone to track migration
- [x] new path - `company/clients/*`
- [x] Add redirect in Front Door
```

**Comment by Harry-Ross** [comment]
@bradystroud @wicksipedia @jeoffreyfischer @camillars 

As per my conversation with @amankumarrr, the routes should be in the format: ssw.com.au/company/clients/case-study/[CLIENT_HERE] e.g. bupa

**Comment by amankumarrr** [comment]
Done 
<img width="947" alt="shepherd-center" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/c69a9787-056e-4ce5-973b-d0f27c2027c7">

**Figure: Shepherd case study**

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud 

Here is milestone for all case studies - https://github.com/SSWConsulting/SSW.Website/milestone/8

**Comment by camillars** [comment]
@amankumarrr @Harry-Ross 

is there a plan to organize these categories e.g. alphabetical order?
![image](https://github.com/SSWConsulting/SSW.Website/assets/53064613/96c47653-7507-426e-8be0-f3ce764eba15)

**Comment by Harry-Ross** [comment]
@camillars @amankumarrr 

> is there a plan to organize these categories e.g. alphabetical order?

The current order of the categories was migrated as is from the v1 site.

The categories can be reordered in TinaCMS if needed. I feel its better that we can reorder client categories based on importance rather than having them by alphabetical order. 

However, I just tried to reorder the categories in TinaCMS, and I encountered a weird bug (at https://www.ssw.com.au/admin/index.html#/~/company/clients), so I have created an issue athttps://github.com/SSWConsulting/SSW.Website/issues/1869 to fix it.
