### ISSUE TITLE
📄 Page - Services | Consulting Options

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1389]
Migrate https://www.ssw.com.au/ssw/Consulting/Consulting.aspx

```[tasklist]
### Tasks
- [x] migrate the page almost as is (text content shouldn't need updating)
- [x] Experts - Remove Jason
- [x] Get your project started! - should use book now component
- [x] Book an expert - update the tech list (remove MVC and add current tech - Angular, React, Power Platform, AI)
- [x] Book a team - update screenshots (the burndown chart makes it look like nothing happened in that Sprint)
- [x] Book a team - add an image of a team of people working (get it from @sethdailyssw)
- [x] get before/after screenshots checked by @adamcogan
- [x] tabs - we've done something similar before
- [x] Add front door redirect
- [x] TODO: done video
```

**Comment by UlyssesMaclaren** [comment]
I would say no... but I think Adam might like this page











Ulysses Maclaren   |   SSW General Manager<http://www.ssw.com.au/People/Ulysses-Maclaren?utm_source=emailsignature>   |    +61 419 418 232<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Ping me on ***@***.***>

From: Brady Stroud [SSW] ***@***.***>
Sent: Wednesday, September 13, 2023 6:52 AM
To: SSWConsulting/SSW.Website ***@***.***>
Cc: Ulysses Maclaren [SSW] ***@***.***>; Mention ***@***.***>
Subject: [SSWConsulting/SSW.Website] Page - Consulting Options (Issue #1389)


https://www.ssw.com.au/ssw/Consulting/Consulting.aspx

Do we need to migrate?
check with @UlyssesMaclaren<https://github.com/UlyssesMaclaren> @wicksipedia<https://github.com/wicksipedia>

-

**Comment by wicksipedia** [comment]
I think this page is important to Adam.

We should:
- migrate the page almost as is (text content shouldn't need updating)
- update the tech list (remove MVC and add current tech - Angular, React, Power Platform, AI)
- Remove Jason
- Update screenshots (the burndown chart makes it look like nothing happened in that Sprint)

description updated to reflect this

**Comment by amankumarrr** [comment]
Mock-ups are ready, waiting for Adam's approval with the email subject "Test Please - Migrating - SSW Consulting Option page "

### Tab 1 - Book an SSW Expert 

<img width="977" alt="old-first-tab-highlighted-2" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/9de3afdf-28f3-412b-83d7-68ac9d005959">

**Figure: Before - Tab with outdated Content highlighted in red** 

 
<img width="682" alt="new-first-tab-highlighted" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/c41a95a3-0c84-487d-bad9-cc0f885f112e">

**Figure: After – Tab with new content highlighted in yellow** 

### Tab 2 - Book an SSW Team

<img width="923" alt="old-second-tab-highlighted-2" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/81d0d747-8b0d-46da-9d4f-9f4c04025114">

**Figure: Before – Removed content highlighted in red** 

 
<img width="1061" alt="new-second-tab-highlighted-2" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/b705952f-875a-4357-930a-0a12418b8da9">

**Figure: After – Adding a video playlist of client case studies**

**Comment by amankumarrr** [comment]
Received some feedback from Adam and will be working on it after the Christmas break since I'm on leave next week

**Comment by amankumarrr** [comment]
@wicksipedia 

As per my conversation with @adamcogan, he has asked us to improve the user experience so:

- The user can find the devs for a particular technology 
- Link this page to the some part of the website.

As per my conversation with @bettybondoc, @jaydenalchin and @2fernandez, they recommended that if this page is to link to the mega menu, it should be under the “About us” section.
 
I and @2fernandez was not 100% sure about this option, so we looped in @uly, who recommended we link the page to `Book an Expert` block under core services and leave it completely out of the mega menu, and we agree with this option.

<img width="671" alt="BookAnExpert" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/e5b3e483-dc29-47ba-b2de-f880adfc901c">

**Figure: Book an expert block on homepage**

**Comment by amankumarrr** [comment]
Done 
<img width="1186" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/9478e451-a176-44b3-ace9-8e00b40d1315">

**Figure: Consulting options page on prod**

**Comment by amankumarrr** [comment]
I've recorded done video - https://youtu.be/iA_AV5UfNcg and sent out the email for the feedback.

**Comment by jeoffreyfischer** [comment]
Comments about the Done Video:

Good video, it shows all the features of the new page 🙂 I have a few comments: 

1. The video was cut at several places (0:08, 1:40, 1:53). Adam will definitely ask you to record a V2 without making any cut 🥲
2. When you are in Full Screen (during intro and outro) the camera angle is great. But when you are in PIP (Picture In Picture), your camera angle is too low. Always keep the camera at eye level, such as you did in your intro/outro.
3. At 0:28 you say "if he clicks here, it will take us to [...]". Generally, it is better to stick with the same subject throughout the video to avoid confusion for the viewer 🙂. So basically:
- if you start by "If **a client** [...]" then stick to "it will take **him** to [...]". 
- if you start by "I **we** [...]" then stick to "it will take **us** to [...]"
4. You say "We are showing [...]" on numerous occasions, maybe try to change it to other options. Below are a few ideas: 
"The page displays [...]", "You can see [...]", "Next, we have [...]", etc.

**Comment by amankumarrr** [comment]
Done. v2 - https://youtu.be/jyo0jPnMAFo

**Comment by jeoffreyfischer** [comment]
Hi Aman,
I can see the improvement :) Really good ! I would say to record a V3 because of the cut (see first comment). The other comments are minor : 

- 0:53 - There is a cut here that kills a bit the flow
- 1:50 - You say it can be edited in PowerBI reports and also in Tina CMS. What's the preferred option?
- Outro - Don't forget to say "from SSW"
