### ISSUE TITLE
💄 Events template - Body content style is bad

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1397]
cc @danielmackay @Hona @wicksipedia 
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/1ad0cd01-9b6e-49ff-8354-1a650b49f658)

As per my conversation with @jaydenalchin, he suggested some improvements to the events pages (e.g.
https://www.ssw.com.au/events/clean-architecture-superpowers-tour)

```[tasklist]
### Tasks
- [ ] Body content doesn't need to be in a card
- [ ] Make body content headings consistent with the rest of the page headings (centered)
- [ ] Make body content text consistent with the rest of the page
- [ ] Center images
- [ ] Make sure this looks good on all events pages
- [ ] Ensure these changes dont affect any other pages
- [ ] checked by @jaydenalchin
```

**Comment by bradystroud** [comment]
Hey @johnxu77 @KristenHu 

I'm a bit confused... you are both assigned to this PBI, is this intentional?

**Comment by bradystroud** [comment]
@johnxu77 
None of the tasks here have been ticked off, can you give an update on this one?

**Comment by KristenHu** [comment]
> Hey @johnxu77 @KristenHu
> 
> I'm a bit confused... you are both assigned to this PBI, is this intentional?

Hey @bradystroud ,
Since John is on client work now, he has passed this PBI to me, I'll update the status of these tasks later.
