### ISSUE TITLE
✨ Test create lead email - Power Automate flow 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1399]
**Description:**
We need to set up a recurring flow that triggers our existing flow on a weekly basis to ensure that each flow is running smoothly.

```[tasklist]
### Tasks
- [x] Create a Flow
- [x] Update the document for the deployment for CRM
- [x] Update the document for SSW.Website WIKI
- [x] Send emails to Account Managers
```

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud 

Hi Team,

We've developed a new flow to ensure the smooth operation of our 'create lead' flows. This flow submits a test lead every Monday. 

To improve recall, we've added a task in the notes for Account Managers. This ensures that the task is prominently displayed and less likely to be missed. Missing this email could potentially indicate a malfunction in our 'create lead' flow, prompting Account Managers to promptly escalate the issue to the Development team. 

Please note that this serves as an additional precautionary measure for our visibility, especially in cases where our other checks may not function as intended.
 
<img width="765" alt="testEmailLead" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/0832cd60-ac2a-4879-9297-fc443ec51539">

**Figure: Test lead email from our new flow**

**Comment by wicksipedia** [comment]
Hey Aman, I'm not seeing a link to any PR... is that expected?
Looking at the description, I'm confused as this was originally meant to be some automation that submits a lead through the website UI.

It doesn't look like this was checked by anyone, or CC'd to anyone

**Comment by amankumarrr** [comment]
Hey @wicksipedia,

I've created a Power Automate flow named "Weekly - Create a test lead," so there isn't a pull request (PR) associated with it. While our initial plan was to integrate it into our pipeline to send the payload to our endpoint on a weekly basis, we ultimately chose to develop a flow for easier maintenance and to handle failover scenarios more effectively.

**Comment by amankumarrr** [comment]
@UlyssesMaclaren 
Hey @wicksipedia,

As per my conversation with @bradystroud, there are few things left on this PBI:

1. Make an UI test - this requires a discussion with @wicksipedia 

   - Should we implement this for all websites or just one? (i.e SSW.Rules and SSW.Peoples)

2. Right now, there is no check that verifies if emails are arriving in Account managers inboxes
   - I have asked @zl24622  to create a Power BI report to send the list of flows with their statuses (this solution will help but won't fix it - this also requires a discussion)

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud 

Closing this as we will implement the new solution with issue #1448
