### ISSUE TITLE
⬆️ Upgrade Next.js to 13.5 

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1449]
As per my conversation with @bradystroud, Next.js 13.5 has a couple new features that would be useful for us:

* Allows us to use `next/image` for CSS background images 
* General performance improvements

```[tasklist]
### Tasks
- [x] Update the website to use Next.js 13.5
- [x] Test to see if the update has broken anything
- [ ] See if you can implement https://nextjs.org/blog/next-13-5#nextimage-improvements with the bits of the site that use `background-image`
```

**Comment by Harry-Ross** [comment]
As per my conversation with @bradystroud, we chose not to use the getImgProps function until it is stable.
