### ISSUE TITLE
🐛 Pipeline - Secrets are visible 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1466]
@wicksipedia @bradystroud 

**Describe the bug**
I've observed that our secrets are currently visible in the pipeline logs when they are collapsed, which poses a potential security risk. To mitigate this risk, we should implement masking to prevent these secrets from being copied or exposed.

**Screenshots/Video**
<img width="803" alt="SecretsInPipeline" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/6e782ee9-89ae-4f6a-9b36-2f5f5762561c">
**Figure: Secrets are visible in plain text in pipeline**
```[tasklist]
### Tasks
- [x] Add the masking for all the secrets
- [x] Rotate the respective keys that are exposed
- [x] Add new keys in the pipeline
- [x] Test all the associated scenarios
```

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud @Harry-Ross 

Hi Team,

We have implemented secret masking in our pipeline, and I have also rotated the secret key (`MICROSOFT_OAUTH_CLIENT_SECRET`) in our Key Vault that was previously exposed in our GitHub logs and removed the old secret.

**Comment by wicksipedia** [comment]
Can you add a rule about this

**Comment by amankumarrr** [comment]
@wicksipedia 

Rule added - https://ssw.com.au/rules/mask-secrets-in-github-actions/ , closing this issue.
