### ISSUE TITLE
📄 Content - Next.js Page Improvements

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1467]
```[tasklist]
### Tasks
- [x] Add Next.js to the /consulting page
- [x] Add the Next.js consulting page to rules to better Next.js
- [x] Add the new OpenGraph image to /consulting/nextjs from @Geordie88
```

**Comment by Harry-Ross** [comment]
Added to SSW Rules in https://github.com/SSWConsulting/SSW.Rules.Content/pull/6861
