### ISSUE TITLE
💸 Tech Debt - Integrate chatbot via Google Tag manager 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1502]
Subject: RE: Urgent - GTM tracking for SSW.fr may be missing
CC: @JeanThirion @tiagov8 @camillars @sethdailyssw @divgul 

**Description**  
Currently, we are manually adding the chatbot to our code. Ideally, it should be managed through Google Tag Manager (GTM) since all our scripts are generated through GTM. Centralizing it in GTM would streamline maintenance and management.

```[tasklist]
### Tasks
- [x] ~Add  Chatbot script as a tag in the GTM~
- [x] ~Clean up the Chatbot scripts from the code~
- [x] ~Doc - Add GTM tag for any third party scripts~
```

**Comment by amankumarrr** [comment]
Hi @camillars @divgul

During testing, we discovered that integrating the chatbot from Google Tag Manager is being blocked by ad-blocker software. Therefore, this change will not progress any further after discussing it with @wicksipedia.

I have cleaned up it for our Australian site, will do the same French site from GTM and will revert the changes I made on the site.

**Comment by amankumarrr** [comment]
Hi @camillars @divgul @JeanThirion @sethdailyssw @tiagov8 

I removed the GTM tag for our French website and added it back into code, closing this issue it will not progress any further.
