### ISSUE TITLE
📄 User Group - Index Page

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1503]
```[tasklist]
### Tasks
- [x] Migrate https://www.ssw.com.au/ssw/netug/
- [x] Make the page a part of the current NETUG collection, either by using an existing or new template (replicate behaviour for homepage in getStaticPaths)
- [x] Enable the breadcrumb on every usergroup page
- [x] Add redirect for this page
- [x] Update new and old megamenu
```

**Comment by Harry-Ross** [comment]
As per my conversation with @adamcogan, @bradystroud, @pierssinclairssw, @wicksipedia: 

1. The Developer Links page will be migrated to Adam's blog and removed from the page
2. The past sessions page will be migrated to SharePoint
