### ISSUE TITLE
💸 Megamenu - layout should be configurable in Tina

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#1559]
**Description**  
In order to get the new megamenu out sooner, we shipped a version with layout/routes hardcoded in a class.

See https://github.com/SSWConsulting/SSW.Website/blob/main/mock-data/mock-data.ts

**Proposed solution**  
Add a new object to store the layout, and configure it in Tina
That way, end users can make edits to the menu

```[tasklist]
### Tasks
- [x] Move menu to TinaCMS
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/1848
- [x] Create Done video
```

**Comment by Harry-Ross** [comment]
Done video: 

https://www.youtube.com/watch?v=n1OB91ejNSo
