### ISSUE TITLE
🐛 Pipeline - Deploy to staging, run tests, swap slots

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1568]
**Describe the bug**
Our `Run - Playwright Tests` pipeline is currently failing, and there's no notification mechanism in place to alert us about it.

We will modify the deployment procedures to prevent builds going to production that fail UI tests:
```mermaid
graph TD;
    A[Main Build] --> B[Deploy to Staging Slot];
    B --> C[Run UI Tests];
    C --> D[Swap Staging with Prod Slot];
```

```[tasklist]
### Tasks
- [ ] ~~Get email or Team's message on a failure~~
- [x] Fix the failing tests on `main`
- [x] Make it as a required check before merging it to main
- [ ] ~~Separate from Main - build + deploy to a different pipeline~~
- [x] Ensure Playwright image tests are running on PR deployments
- [x] Add slot swapping from staging deployments (main build -> deploy to staging slot -> run UI tests -> swap staging with prod slot)
```

**Screenshots/Video**
<img width="657" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/17518b30-9c84-4449-8631-5d986202a079">

**Figure: `Run - Playwright Tests` pipeline is failing**

**Comment by Harry-Ross** [comment]
As per my conversation with @wicksipedia, we are not going to implement the notifications on Teams/email, and we are introducing slot swapping as a part of this issue.

Updated description to add new task, removed email/Teams notifcation task.

A new issue was created at https://github.com/SSWConsulting/SSW.Website/issues/1642 for fixing the broken Playwright tests.

**Comment by Harry-Ross** [comment]
As per my conversation with @amankumarrr, we have found an alternative to deleting the slot. I have created Middleware in Next.js set the `X-Robots-Tag` with the `middleware.ts` file, which is dynamically set using either an environment URL or if staging is contained within the URL.
