### ISSUE TITLE
🐛 Using Next Link on external links causing error in App Insights

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1570]
App Insights is logging 404s when Next tries to prefetch the page data from external link.

This is because we are using the Next Link component to link to external pages 
e.g. SSW Rules or event the old website (ssw.com.au/ssw)

```[tasklist]
### Tasks
- [x] ~Dont use next link for external pages~ Adding prefetch property with link can prevent preloading
- [ ] ~Create a wrapper for next/link that sets prefetch=false for external links~
- [x] Investigate why there are some 200 codes in the failed requests section
```

![Image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/4fe607fa-40e2-41c6-a6c8-57496919b2f1)

**Comment by Harry-Ross** [comment]
Maybe also consider dynamically setting the prop `prefetch` based on a whitelist of URLs: 
https://nextjs.org/docs/pages/api-reference/components/link#prefetch

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud @Harry-Ross 

I've added the property prefetch to false for all the footer links that were pointing to external links with this PR #1636, I'll monitor the logs if we still getting this error then we might go for creating a wrapper component for our external links.

**Comment by amankumarrr** [comment]
@wicksipedia @Harry-Ross @bradystroud 

We are getting far less errors in logs after adding the prefetch property. Therefore, I don't think adding a wrapper would add any value there. 

<img width="480" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/4b5ec94f-4f66-4c9b-b70f-4579ca7178c2">

**Figure: Error logs in App Insight**
