### ISSUE TITLE
✨ Redirection - SSW.COM

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1614]
FROM: @UlyssesMaclaren 
Subject: RE: Could we redirect ssw.com to local regional site (e.g. ssw.com.au)
CC: @jaydenalchin @camillars @pierssinclairssw @adamcogan @wicksipedia @bradystroud  @2fernandez @JeanThirion @samsmithssw @Marxoz 

URL: https://ssw.com/

We need to set up location-based redirection for `ssw.com`:

- When the website is accessed from China, it should redirect to `ssw.cn`.
- If the access is from France, it should redirect to `ssw.fr`.
- If the access is from New Zealand, it should redirect to `ssw.nz`.
- For all other cases or locations, the default redirection should be to `ssw.com.au`.

This way, users will be automatically redirected to the appropriate regional website based on their location.

```[tasklist]
### Tasks
- [x] Add a redirection based on geolocation
- [x] ~Remove~ zz the landing page hosted on WPengine (Work with SysAdmin to remove it)
- [x] Nord VPN - Use free version for testing and Done Video
- [x] Add Hong Kong for China's website
```

**Comment by amankumarrr** [comment]
@jaydenalchin @camillars @pierssinclairssw @adamcogan @wicksipedia @bradystroud  @2fernandez @JeanThirion @samsmithssw @Marxoz

As per my conversation with @UlyssesMaclaren, we also own `ssw.nz` domain, so from New Zealand, we will be redirecting its traffic to that domain.

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud @UlyssesMaclaren @Marxoz @samsmithssw 

I've configured the Staging Front Door for redirection. Currently awaiting clarification on questions raised in the email with the subject "RE: Could we redirect ssw.com to local regional site (e.g. ssw.com.au)"

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud @UlyssesMaclaren @Marxoz @samsmithssw

All the redirections for Europe, China, and the rest of the world have been successfully implemented. As per my conversation with @leahy268, the wpengine site has been zz'ed for now, and we plan to delete it after a month if everything functions as expected.

All redirections are documented here - https://sswcom.sharepoint.com/:x:/r/sites/SSWDevelopers/_layouts/15/Doc.aspx?sourcedoc=%7B73E92FB3-F878-4EF8-8FA9-10D1937F572F%7D&file=Redirections.xlsx&action=default&mobileredirect=true

**Comment by amankumarrr** [comment]
CC: @UlyssesMaclaren @tiagov8 

I'm reopening this issue as we found issue with French speaking European countries, where it is redirecting to ssw.fr instead of ssw.fr/fr/. 

As per my conversation with @AttackOnMorty , @bradystroud and @GordonBeeming, we are also adding Hong Kong in our list for China website.

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud 

I've added Hong Kong to redirect its audience to China and fixed the redirection for the French-speaking European country. Here is the done video - https://youtu.be/ax3Ct_KNM50 (3:44)
