### ISSUE TITLE
Forms - switch to Jotform

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#1619]
Current stack:

- Custom booking form on website, different one on people, different one on rules, different one for SSWTV, etc
- Need to store keys for PowerAutomate, Recaptcha

Proposed solution:

- Move form to Jotform <https://www.jotform.com/pricing/>
- Have 1 definition of the booking form (reused on all sites)
- Then use Jotform for UG bookings

```[tasklist]
### Tasks
- [x] Get purchase please approved
- [x] Migrate booking form to JotForm
- [x] Create a new Power Automate flow for submission
- [x] Disable Weekly - Test lead email PA Flow
- [x] ~Remove unused packages/secrets from app~ Once people and rules are not using current api then we will delete it
- [x] Reply done to "Re: Consulting enquiry - Metro Finance - Chevon Abbaticchio"
```

**Comment by wicksipedia** [comment]
purchase please approved - email subject: `Website - capturing leads - switch to form service`

**Comment by camillars** [comment]
cc: @tiagov8

**Comment by amankumarrr** [comment]
JotForm is ready for production deployment. However, due to feedback received on this PR - https://github.com/SSWConsulting/SSW.Website/pull/1919, I'll initiate the rollout after the Christmas break after completing the feedback since I'll be on leave next week.

**Comment by amankumarrr** [comment]
@wicksipedia @camillars 

After submitting the form, the browser blocks the redirection, resulting in the thank-you page displaying within the form frame, which appears disjointed. Additionally, the vertical scrollbar on the form detracts from the user experience. I've reported both issues to their support team and am awaiting feedback. Meanwhile, I'll explore alternative embedding options within a time frame of 3-4 hours.

<img width="913" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/ea92a11a-8451-4a03-a0ad-02616131e276">

**Figure: Ticket for vertical scrollbar issue - https://www.jotform.com/answers/10642061-ligthbox-showing-vertical-scrollbar**

<img width="890" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/69f49423-9914-480c-b119-a28e64684144">

**Figure: Ticket for redirect's issue - https://www.jotform.com/answers/10642001-ligthbox-script-thankyou-redirect-is-being-blocked-by-browser**

**Comment by amankumarrr** [comment]
@wicksipedia @camillars @adamcogan 

Our existing booking form has been replaced with the new JotForm, and it's now live and functioning as expected. The test has passed, verified by @UlyssesMaclaren

<img width="738" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/be666fd6-1793-4c58-8fb7-f1b0314fb8a7">

**Figure: JotForm on the production**

**Comment by camillars** [comment]
@amankumarrr 

1. Has this been tested against Google Analytics/GTM as well? to make sure it counts as a lead form submitted?

**Comment by amankumarrr** [comment]
@wicksipedia 

Hi @camillars ,

I reviewed Google Analytics and discovered these statistics. Not sure if that aligns with your inquiry.

<img width="946" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/b17ab682-8a6f-4eb6-b365-0b74338e6d1a">

**Figure: Leads from the Google Analytics for the JotForm**

**Comment by tiagov8** [comment]
Hi @amankumarrr 

Few things to improve the form:

- [ ] 1. FORM TEXT - Can we change from "Name" to "Full name"?

- [x] 2. FORM TEXT - Do we need `example@example.com` in 2024? If we do... can it be a placeholder inside the field?

- [x] 3. FORM CSS - Can we reduce the margin between label and field?

     E.g. from

```
 .form-label-top {
    width: 100%;
    margin-left: 2px;
    margin-bottom: 14px;
}
```

to

```
.form-label-top {
    width: 100%;
    margin-left: 2px;
    margin-bottom: .5rem;
}
```

- [x] 4. FORM CSS - Change the required `*` red color to be SSW's `#cc4141`

- [x] 5. LOCATION - I don't see a good reason to have "South America" as a major option (do we get leads from there?). I think we should remove (so it's under Others) OR at least move it to be after USA

- [x] 6. HOW DID YOU HEAR - Does anyone still use Yellow Pages? Can we remove from the list?

- [x] 7. COMPANY - I wouldn't make this required... and I think it should come before LOCATION... please check if others agree

- [x] 8. FORM / LESS IS MORE - Don't think we need the border top above the SUBMIT button

- [x] 9. FORM CSS - If you scroll down, we see this weird footer... Please investigate and remove

 
    <img width="1064" alt="Screenshot 2024-01-22 at 3 07 14 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/e0e64470-670a-4759-86c2-420a267f7a9b">

- [ ] 10. VALIDATION - Apparently there is no validation on the phone to be numbers... consider adding

**Comment by amankumarrr** [comment]
Done video - https://youtu.be/WxSuVRdq-Ag

**Comment by jeoffreyfischer** [comment]
Good video! I think it would need a V2 because of the cut (see first comment below). The other comments are minor : 

0:12 - You did a video cut here that kills the flow
2:58 - No need to say it looks weird, just say it's narrow because that's the width that we just fixed :) 
3:30 - Maybe add an example of country like "For instance we can see that most jotform users are from India.

**Comment by tiagov8** [comment]
Hi @amankumarrr 

Can you check my comment https://github.com/SSWConsulting/SSW.Website/issues/1619#issuecomment-1904993307 ?

I expected this to be closed only after those are actioned

**Comment by amankumarrr** [comment]
Hey @tiagov8, 

The auto closure was triggered by the associated PR, but tasks still remain. I'll close it once all those tasks are addressed.

**Comment by tiagov8** [comment]
> Hey @tiagov8,
> 
> The auto closure was triggered by the associated PR, but tasks still remain. I'll close it once all those tasks are addressed.

Thanks, @amankumarrr !

PS. @Geordie88 had a problem with jotForm. He will contact will with more details

**Comment by amankumarrr** [comment]
> > Hey @tiagov8,
> > The auto closure was triggered by the associated PR, but tasks still remain. I'll close it once all those tasks are addressed.
> 
> Thanks, @amankumarrr !
> 
> PS. @Geordie88 had a problem with jotForm. He will contact will with more details

Yes we just had a chat, and I found out his branch was outdated. Probably it's been fixed now.

**Comment by amankumarrr** [comment]
Hi @tiagov8,

I've addressed all your feedback on JotForm's styling except for these two:

> 1. FORM TEXT - Can we change from "Name" to "Full name"?

As per my discussion with @wicksipedia, it's noted that updating the label field would necessitate modifying the Power Automate flow. Considering there's no other name field, keeping 'Name' as the label makes sense.

> 10. VALIDATION - Apparently there is no validation on the phone to be numbers... consider adding

As phone numbers can vary in format across different countries and are essentially string values, adding specific validation for numbers might not be feasible.

<img width="345" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/4a55177e-5948-42f9-8ffe-2e7023c05d09">

**Figure: Booking form on production**

**Comment by amankumarrr** [comment]
Hi @tiagov8,

I've reverted the order of 'company' and 'location' to their previous arrangement as it was causing issues in the Power Automate flow. However, I have created an issue for this to not have any impact - : https://github.com/SSWConsulting/SSW.Website/issues/2112
