### ISSUE TITLE
✨ New Functionality - Shop

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1646]
cc @adamcogan, @wicksipedia, @jeoffreyfischer, @amankumarrr, @KristenHu, @bradystroud 

**Low priority until all pages migrated from v1 site**

As per our conversation in the Sprint Review, there is a `/Shop` route on the v1 site, but it would be good to have shop functionality in the case of needing to sell SSW Products. 

```[tasklist]
### Tasks
- [ ] Implement the ability to create shop pages
```

**Comment by Calinator444** [comment]
@uly1 

CC: @wicksipedia 

I'd recommend fleshing out this PBI description a bit and maybe breaking it into several. There's a lot of important information we need to figure out. Happy call Adam regarding this for clarification.

A few things we'd want to figure out are:
- [ ] What we're planning to sell (e.g. Merchandise? Software? both?)
- [ ] What the design should look like
- [ ] What payment options do we support?
- [ ] Do we need an account system to facilitate this?
- [ ] How are we keeping record of payments? (I'd strongly recommend having a separate endpoint/database for customer information and invoices for security reasons of course)
- [ ] How will we send receipts out?
- [ ] Do what kind of shipping options do we offer (if applicable)
