### ISSUE TITLE
💄UI/UX - .NET UG Quick Fixes

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1653]
As per my conversation with @camillars and @hveraus, the .NET UG page could be improved:

```[tasklist]
### Tasks
- [x] Move About the .NET UG section to the top after the event description section
- [x] Center the elements in the banner when there is no torso image provided
- [x] Fix incorrect links on all pages
```
