### ISSUE TITLE
💸 Tech Debt - Change Event Times To Come from SharePoint

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1690]
As per my conversation with @bradystroud, it would be better to have time information for SSW Events to come from SharePoint instead of TinaCMS because:

1. Previous issue with Tina dates - https://github.com/SSWConsulting/SSW.Website/issues/1664
2. Easier for marketing to move events in only 1 location

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/fbf5b886-bb0f-4c5b-ad06-64d7a43412fa)
**Figure: The times for specific cities**

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/29345a32-3131-4a98-94e0-9061b57f60e1)
**Figure: The objects to be replaced with SharePoint IDs**

```[tasklist]
### Tasks
- [ ] Create an endpoint to validate SharePoint ids that come from the Events calendar 
- [ ] Create an endpoint to get SharePoint data based on ID
- [ ] Change events to accept a list of SharePoint IDs instead of Tina values (in form above)
```
