### ISSUE TITLE
💸 Tech Debt - Old Endpoints Discovered

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1691]
As per my conversation with @pierssinclairssw @bradystroud:

Piers discovered some old endpoints 

- https://webservices.internal.ssw.com.au/SSWWebService/Contact.asmx
- https://webservices.internal.ssw.com.au/SSWRegistrationWebService/registration_v2.asmx?wsdl
- https://webservices.internal.ssw.com.au/

```[tasklist]
### Tasks
- [ ] Check they are not being used and zz
- [ ] Reply done to "Subject: SSW.Website - Old API URLs to be removed from HealthCheck"
- [ ] Reply done "SSW Web API - Where it should be used"
```
