### ISSUE TITLE
💸 Tech Debt - next/core-web-vitals not in use

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1727]
As per https://nextjs.org/docs/pages/building-your-application/configuring/eslint, we are not using the `next/core-web-vitals` setting.

```[tasklist]
### Tasks
- [x] Apply the eslint setting
- [x] Fix all lint issues
- [x] Ensure all functionality is still working
```

This should also fix a range of hydration errors
