### ISSUE TITLE
🐛 Megamenu - Error Occurs on Click

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1753]
As per my conversation with @ricksu978, when the "SSW Rules" link is clicked on in the megamenu, it throws an error. 

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/f201775d-2172-4467-9d3c-44cd87cac893)
**Figure: output after clicking the link**

```[tasklist]
### Tasks
- [x] Fix issue for "SSW Rules"
- [x] Fix issue for "Our People"
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/1832
```

**Comment by Harry-Ross** [comment]
@bradystroud @amankumarrr @jeoffreyfischer @wicksipedia 

As per our conversation in the Sprint Review, reopening as the "Our People" link creates the same error.

**Comment by amankumarrr** [comment]
Done - CustomLink has been added and Next's Link has been replaced with anchor tag to solve this problem of client-side exception and resolved by this pr - #1832
