### ISSUE TITLE
💸 Tech Debt - isTitle Not Used for SEO Titles

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1755]
cc @bradystroud @wicksipedia @amankumarrr @jeoffreyfischer 

As per our conversation in the Sprint Review, using the `isTitle` field in the `seoSchema` would be good to allow filenames to be automatically generated, possibly not needing the additional field added in https://github.com/SSWConsulting/SSW.Website/pull/1641.

**Relevant documentation:**
https://tina.io/docs/reference/fields/#istitle

```[tasklist]
### Tasks
- [ ] Add the `isTitle` field to `seoSchema` in `components/util/seo.tsx` 
- [ ] Make the field required 
- [ ] Test it automatically generates the filename when a new document is created
```

**Comment by andrewwaltosssw** [comment]
seoSchema is a component and its fields cannot be accessed at time of creating a new page due to the filename being a required top-level field:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/53bff27a-7175-4518-81d2-3850129ac59d)
**Figure: Error shown trying to add values to SEO fields**

Another solution here might be to add a new string field that has isTitle and is the first field in the UI.
