### ISSUE TITLE
🐛  Strange linked page on website home page carousel item

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#1757]
**Describe the bug**
On ssw.com.au, when the user clicks on "Watch the video" in the carousel, it opens a "Application error" page.

**To Reproduce**
1. Go on ssw.com.au
2. Click on "Watch the Video" in the 3rd carousel item.
3. The page shows "Application error"

**Expected behavior**
This video should open in a modal: https://www.youtube.com/watch?v=Jveq6VFjWTA 

**Tasks**
- [x] Redirect the user to the video.
- [x] Add the video to the top of the page.

**Screenshots/Video**
![issue1](https://github.com/SSWConsulting/SSW.Website/assets/106663901/28efb9f8-9290-4fd3-872f-f165c6b02672)
**Figure**: 

![issue2](https://github.com/SSWConsulting/SSW.Website/assets/106663901/2eb8afc5-ba53-4ab8-92cb-9db4b4ea7714)
**Figure**:

**Comment by jeoffreyfischer** [comment]
- [x] Fix all the remaining broken links in the carousel menu.

**Comment by jeoffreyfischer** [comment]
Problem: The links were routing towards the old website. 
Solution: The links have been updated using Tina CMS.

- Affected routes: /

- Fixed #1757

- Screenshots

![website-PR-006a](https://github.com/SSWConsulting/SSW.Website/assets/106663901/3799c37f-e058-4df5-8792-1e0f5dd833f9)
Figure: Step 1

![website-PR-006b](https://github.com/SSWConsulting/SSW.Website/assets/106663901/f1d81fe6-c5c6-4b25-8dd8-afe05bbc7f65)
Figure: Step 2
