### ISSUE TITLE
🗃️ Archive Old Training Pages into /history

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1767]
(Checked by @adamcogan @wicksipedia @bradystroud @jeoffreyfischer)

I have saved groups of pages as per https://github.com/SSWConsulting/SSW.Website/issues/1263 from the v1 site to HTML ready to be deployed to Blob Storage on `ssw.com.au/history`. 

```[tasklist]
### Tasks
- [x] Set up Front Door to route `ssw.com.au/history` to this Blob Storage
- [x] Create an `index.html` on each of the directories to access old pages (automatically via Python)
- [x] Link `/history` sitemap to main index sitemap
- [x] Breadcrumbs - Add `/history` to breadcrumbs links
- [x] Breadcrumbs - If clicked on link, navigate to old history page i.e. `/history/training`
- [x] Add box at top of page to denote that is an archived page (similar to archived rules)
- [x] Direct the "Book Now" buttons on pages e.g. `ssw/Training/BI-TheGuts.aspx` to `/booknow` (create temporary Next.js page that can be redirected from later)
- [x] Fix broken presenter image of Adam on `/Training` pages
- [x] Fix broken Adam Stephensen + Eric Phan photos
- [x] Make all resources (HTML + images) lowercase
- [x] Deploy training pages' HTML files to Blob Storage
- [ ] Test Please each group of pages with Wicksy, then Adam
```

**Comment by Harry-Ross** [comment]
As per https://github.com/SSWConsulting/SSW.Website/pull/1835, there is now a storage account deployed to https://stsswwebsitezjkojq27uhqb.z8.web.core.windows.net/. 

This will be added as a Front Door route at ssw.com.au/history. 

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/bed6ac51-811f-45fb-a396-c0cd4b7c2c79)
**Figure: The storage account deployed to the `ssw.com.au` resource group**

**Comment by Harry-Ross** [comment]
Changes to the archiving script in https://github.com/SSWConsulting/SSW.Website-v1-Progress/pull/9:

* Archive heading has been added 
* Adam's image has been fixed 
* Added index.html generation for folders
* Added correction of breadcrumbs links to history index pages
* Simplified script slightly + comments



![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/82e4d3a6-abac-488d-bf20-6ac5bd685c06)
**Figure: Screenshot of archived banner**

TODO still: Fix Christmas SVG, replace book now links

**Comment by amankumarrr** [comment]
Fixed the Front Door issue https://github.com/SSWConsulting/SSW.FrontDoor/pull/129, and manually updated index.html file under `/history/Training/` and here is the PR for that change - https://github.com/SSWConsulting/SSW.Website-v1-Progress/pull/10

<img width="514" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/4d5d14e9-74b2-45df-97ac-b53f18b42e7d">

**Figure: Archived page - https://www.tfs365.com/history/AccesstoSQLServerandNET.aspx.html under `/history`**

**Comment by Harry-Ross** [comment]
As per my conversation with @wicksipedia, the archive Blob Storage has now been deployed to ssw.com.au/history. 
Front Door redirects added in https://github.com/SSWConsulting/SSW.FrontDoor/pull/129, 
Script improvements + file cleanup added in https://github.com/SSWConsulting/SSW.Website-v1-Progress/pull/11

All of the migrated training pages can be found in a list at https://www.ssw.com.au/history/training/



![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/7c1a5dd6-59f9-4524-8754-754755f22b56)
**Figure: Example of a migrated page (https://www.ssw.com.au/history/training/sharepointuts.html)**
