### ISSUE TITLE
🐛 Events list - text too small

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1772]
**Describe the bug**
This was introduced in #1769

![image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/9b424a43-e9f5-4dd3-a4af-fdd45fa1cfab)
**Figure: small text 🔍**

**To Reproduce**
1. See home page 
https://www.ssw.com.au/

```[tasklist]
### Tasks
- [x] Make text normal size (figure out what is was before)
- [x] Get checked by designer/or Camilla
- [x] Check for other places
```

**Expected behavior**
Looks normal

**Comment by amankumarrr** [comment]
Resolved the issue with the footer font being too small. No issues identified with 'Upcoming Events,' and no other areas were found to be broken.

<img width="949" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/77765ba0-eb00-4c64-91ff-1d3424e5e9a3">

**Figure: Fixed font-size for the footer text Before and After**
