### ISSUE TITLE
📄 Review old rules to better SQL Reporting Services

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#1809]
**From**: @jeoffreyfischer 
**Sent**: Friday, 24 November 2023 6:13 PM
**To**: @jeoffreyfischer 
**Cc**: @william-liebenberg; @GordonBeeming; @adamcogan
**Subject**: Migrate rules to new website

(Checked by William L. and Gordon B. and Adam)
Hi Uly,

[ssw.com.au/ssw/Standards/Rules/RulesToBetterSQLReportingServices.aspx](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Fssw%2FStandards%2FRules%2FRulesToBetterSQLReportingServices.aspx&data=05%7C01%7CJeoffreyFischer%40ssw.com.au%7C5bb3c77ef19e4a27a34708dbecbcbc40%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638364067582700653%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fRgfY6gM3LyR9aRqbO9435iLvH7Bf9yLlUKqD52i0JQ%3D&reserved=0)
I opened this page on my computer and the images loaded properly. It must have been a transient error.
To myself,
Let’s get this page converted
1.	Copy page into a Word document and save it in a safe place (Microsoft Teams channel and/or SharePoint)
2.	Put my own notes with yellow highlighting.
3.	Ask Gordon and add extra notes
4.	Call Adam and check his notes
5.	Read rule about “How to handle unexpected request”: [ssw.com.au/rules/unexpected-requests/](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Frules%2Funexpected-requests%2F&data=05%7C01%7CJeoffreyFischer%40ssw.com.au%7C5bb3c77ef19e4a27a34708dbecbcbc40%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638364067582700653%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iucNi%2BTv98ovEGHohf8Zq3QLH%2FSyx7FtygD0vRFrb3E%3D&reserved=0)

```[tasklist]
### Tasks
- [x] Issue 1 - Rules 1 to 14: #1841
- [x] Issue 2 - Rules 15 to 34: #1842
- [x] Issue 3 - Rules 35 to 50: #1843
- [x] Issue 4 - Rules 51 to 65: #1844
- [ ] Reply 'Done' to all emails mentioned in this PBI and @mention the sender with 'Done'
```

**Comment by GordonBeeming** [comment]
@jeoffreyfischer shouldn't this issue be in the rules content repo?

**Comment by jeoffreyfischer** [comment]
Hi @adamcogan,

https://www.ssw.com.au/ssw/Standards/Rules/RulesToBetterSQLReportingServices.aspx

As per our conversation, I haven't migrated the content at the top of this page because the links don't exist anymore. 

![image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/52624efb-78fc-4e2f-8c28-5633cae5847f)
**Figure: This content has not been migrated**

**Comment by jeoffreyfischer** [comment]
As part of this work, I have created a Wiki page: [Editing Old Rule Pages in Archive](https://github.com/SSWConsulting/SSW.Website/wiki/Editing-Old-Rule-Pages-in-Archive)

**Comment by jeoffreyfischer** [comment]
https://www.ssw.com.au/archive/standards/rules/rules-to-better-sql-reporting-services.html

As per my conversation with Adam, I will:
- [x] indent the emoji lines
- [x] add a line break between each rules in the list

**Screenshot**
![Image](https://github.com/user-attachments/assets/ba1055fc-893c-4fc3-8965-cb32909e139c)
**Figure: add indent and line breaks for each listed rule**

**Comment by jeoffreyfischer** [comment]
✅ Done - I have indented the emoki lines and added linebreaks between each listed rule

**Screenshot**
![Image](https://github.com/user-attachments/assets/b985fe41-6118-4c7b-a34e-b14c23bfed33)
**Figure: added indent and line breaks for each listed rule**
