### ISSUE TITLE
💸 Tech Debt - Remove Old Playwright Installation

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1821]
cc @bradystroud @amankumarrr 

At the moment, we have 2 separate `playwright.config.ts` files, which could be simplified so that there is only 1 Playwright installation in the project.

```[tasklist]
### Tasks
- [ ] Remove the `playwright.config.ts` in the root directory
- [ ] Remove dependencies in the main `yarn.lock` file
- [ ] Ensure all tests still run
```
