### ISSUE TITLE
Add Custom Link component for all links

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1832]
Implement a conditional rendering strategy using either next/link or <a> based on the URL type (external or internal). This approach aims to prevent client-side exceptions during data prefetching for external sites by choosing the appropriate link component dynamically.

```[tasklist]
### Tasks
- [x] Create a Custom Link Component
- [x] Replace all links with this component
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/963
```

**Comment by amankumarrr** [comment]
Done - CustomLink component has been added to replace anchors and links.
