### ISSUE TITLE
🧪 Testing - Add Unit Testing

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1871]
Note: Only action once all pages have been migrated

As per my conversation with @wicksipedia, it would be good to add a testing framework (i.e. Jest) to the SSW Website. 
Storybook should also be considered alongside Jest to also allow visual testing and a visual database of the components in the project.

```[tasklist]
### Tasks
- [ ] Investigate whether to add Jest and/or Playwright and/or other testing framework to the project
- [ ] Add the chosen framework 
- [ ] Add a way to measure code coverage using these unit testing frameworks
```

Links:
https://nextjs.org/docs/pages/building-your-application/optimizing/testing#jest-and-react-testing-library
https://storybook.js.org/docs/writing-tests/test-runner
