### ISSUE TITLE
🐛 Bug - Non-required Fields Causing Error

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1897]
As per my conversation with @sethdailyssw, a deployment failed due to a nullable field being not filled.

![MicrosoftTeams-image (5)](https://github.com/SSWConsulting/SSW.Website/assets/20507092/78a7c462-9a88-4aa3-8bce-ef067ed0df8a)
**Figure: Fields not filled out in the events booking block**

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/559b1192-b3b0-4553-be4b-391e2c5f32a6)
**Figure: Error logs from the build**

```[tasklist]
### Tasks
- [ ] Add null safety to the `/events` pages
- [x] Make fields required in event booking block
- [ ] Check other events blocks to ensure the correct fields are required
```

**Comment by bradystroud** [comment]
PR auto closed - reopening as there are some tasks remaining
