### ISSUE TITLE
✨ Testimonials - Make them reorderable and filterable 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2008]
Subject: RE: Kiriana left a review for SSW Sydney - Enterprise Software Development
CC: @tiagov8 @bradystroud @wicksipedia @sethdailyssw @UlyssesMaclaren @ae-cher-ssw @adamcogan 
 
URL: https://www.ssw.com.au/company/testimonials

> 1.	Is there anything we can do to move the most relevant testimonials to the top? E.g. organize them from recent to oldest
>2.	Some testimonials on this page are from SSW’ers and are not relevant since the goal of this page is to build trust with social proof > from what our clients have to say about us. 
Can we filter them from this page?
> 3.	Are the testimonials from SSW employees being shown on a page that is not relevant? i.e. outside of the Brainstorming consulting page

**Describe the solution you'd like**
- Filter out SSW's employees from testimonials 
- Add date/sequence or Tina reordering to make testimonials orderable 

```[tasklist]
### Tasks
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/2038
- [x] Make Testomonials reorderable
```

**Comment by tiagov8** [comment]
cc @camillars 

Hi @amankumarrr 

Assuming we won't want to show 1, 2, 3, 4 star ⭐️ reviews... I think we should remove/hide this funcionality (aka not have ratings in testimonials)

- [x] 1. Please discuss with the team and product owner if we should remove OR just hide these stars

Cheers,

**Comment by camillars** [comment]
> cc @camillars
> 
> Hi @amankumarrr
> 
> Assuming we won't want to show 1, 2, 3, 4 star ⭐️ reviews... I think we should remove/hide this funcionality (aka not have ratings in testimonials)
> 
> * [x]  1. Please discuss with the team and product owner if we should remove OR just hide these stars
> 
> Cheers,

agreed ✅

**Comment by amankumarrr** [comment]
@tiagov8 @camillars 

I've made the testimonials consistent by removing the stars from all of them. Additionally, I've integrated a feature in Tina to filter out any undesired testimonial types from the list. Now all the testimonials are filtered. 

**Screenshots:** 
<img width="362" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/2d6d2c99-005d-428e-ba84-9bd5a0a7e8db">

**Figure: Tina Field to hide the testimonials'**

**Comment by tiagov8** [comment]
Hi @amankumarrr 

- [x] 1. Can you make all testimonials' categories consistent in casing? (e.g. "brainstorming" is lowercase)

- [x] 2. How many categories do we have? How do we know where the testimonials go? 
        Please create a new page "Testimonials" here https://github.com/SSWConsulting/SSW.Website/wiki/ to add this info
        
- [x] 3. Less is more - Can we implement on https://www.ssw.com.au/company/testimonials ?
        Please liaise with @camillars / @UlyssesMaclaren to remove the superfluous?
        E.g. I think these don't add any value to us:
        
       > Bill Russell, Pioneer Solutions Group
        Thanks. The new download [of SSW Access Reporter] is exactly what I needed. Awesome Product!

       > Henry Khosasih
        Thanks guys for organizing the meetup. [The topic] looks like the perfect solution for my use case. I'll give it a go 🙌
        
       > Arashu Goto
         People with various knowledge levels come and create a worthwhile session

- [x] 4. This min-height set to 6rem is exagerated. Please change it to 4rem instead:
   <img width="1055" alt="Screenshot 2024-01-15 at 10 50 39 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/3ab4b79c-1807-49f4-91fb-32f2c70beed4">

**Comment by amankumarrr** [comment]
@tiagov8 @camillars 

### Ordered Testimonials
- `/events/*`
**Number of testimonials**: first 3 on specificized category in `Tina`
**Test**: https://ssw.com.au/events/clean-architecture-workshop





- `/training/*`
    **Categories** - `Internship`
    **Number of testimonials**: first 3
**Test**: https://ssw.com.au/training/internship-fullstack
- `/company/testimonials`
**Categories excluding**: `Internship` and `Brainstorming` from `Tina` 
**Test**: https://ssw.com.au/company/testimonials

### Random Testimonials
- `/offices`
**Categories excluding**: `Internship` and `Brainstorming`
**Number of testimonials**: 1
**Test**: https://ssw.com.au/offices
- `/offices/*`
**Categories excluding**: `Internship` and `Brainstorming`
**Number of testimonials**: 1
**Test**: https://ssw.com.au/offices/brisbane 
- `/netug/`
**Categories**: `User Group` and specified in `Tina`
**Test**: https://ssw.com.au/netug/brisbane
- `/company/about-us`
**Test**: https://ssw.com.au/company/about-us


- `/consulting/*`
**Number of testimonials**: 3
**Test**: https://ssw.com.au/consulting/angular

✅ Consolidated testimonial files into a single file.
✅ Enabled testimonial ordering functionality.
✅ Successfully improved loading time for testimonials (`/company/testimonials`) from 5-6 seconds to under 1 second.

❌Testimonials can't have any embedded components

**Screenshot:**
<img width="934" alt="Testomonial-Editable-Tina" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/eb579f69-2fc3-475e-a100-ef07e18b9065">
**Figure: "Testimonials can be ordered in Tina now"**

### WIKI - [Testimonials - Categories](https://github.com/SSWConsulting/SSW.Website/wiki/Testimonial-%E2%80%90-Categories)

**Comment by amankumarrr** [comment]
As per my conversation with @UlyssesMaclaren, we decided to remove all the testimonials @tiagov8 has mentioned in this thread and updated some of the content for the testimonial as follows:

For **David Blacketer**
From: 
        1. aproved 
        2. before June 2021
 To: 
    1. Approved 
    2. soon 

And For **S. Somasegar**, I removed the "Dear Adam"

**Comment by amankumarrr** [comment]
TODO: Done video

**Comment by camillars** [comment]
Hi @amankumarrr 
confirming you have only removed the superfluous ones mentioned by @tiagov8 ?

cheers.

**Comment by amankumarrr** [comment]
@camillars  
Yes all these are removed 
  > Bill Russell, Pioneer Solutions Group
  Thanks. The new download [of SSW Access Reporter] is exactly what I needed. Awesome Product!

 > Henry Khosasih
  Thanks guys for organizing the meetup. [The topic] looks like the perfect solution for my use case. I'll give it a go 🙌
  
 > Arashu Goto
   People with various knowledge levels come and create a worthwhile session

**Comment by tiagov8** [comment]
Hi @amankumarrr 

- [x] 1. Please add the extra info about ordering to https://github.com/SSWConsulting/SSW.Website/wiki/Testimonial-%E2%80%90-Categories

- [x] 2. Change the name of the Wiki section to "Testimonials - Pages and Categories

- [x] 3. Replace all HTML `<br>` for double spaces (this is how you break a line in Markdown :) )

- [x] 4. Then separate the wiki section by page, following this template:

> 1. {{ PAGE }}
>    - Shows {{ X }} testimonials ( {{ RANDOM/ORDERED}} ) from {{ CATEGORY }} category
> 2. {{ PAGE }}
>    - Shows {{ X }} testimonials ( {{ RANDOM/ORDERED}} ) excluding {{ CATEGORY }} category
   
 Ping me on Teams if in doubt ;)

**Comment by amankumarrr** [comment]
Hi @tiagov8,

All done - Please review - https://github.com/SSWConsulting/SSW.Website/wiki/Testimonial-%E2%80%90-Pages-and-Categories

thanks,

**Comment by tiagov8** [comment]
> Hi @tiagov8,
> 
> All done - Please review - https://github.com/SSWConsulting/SSW.Website/wiki/Testimonial-%E2%80%90-Pages-and-Categories
> 
> thanks,

Hi Aman, 

looks good, but few things:

- [x] 1. For the page link, can you replace code with an actually link to each of the pages? Or an example when it need to be
- [x] 2. For the number, type, and category name, can you replace `code` for **bold**? I think it makes more sense semantically
- [x] 3. Please reorder making 13, 12, and 11 the be 1, 2, and 3 respectively? So /* will be the 1st etc
- [x] 4. Please include a screenshot of the homepage testimonials at the end, with a caption: Figure: Example of testimonials being shown on the website

**Comment by amankumarrr** [comment]
All done - https://github.com/SSWConsulting/SSW.Website/wiki/Testimonial-%E2%80%90-Pages-and-Categories

Thanks

**Comment by amankumarrr** [comment]
Here is the done video - https://youtu.be/UR-PCeOaNZY (2:48 secs)

**Comment by jeoffreyfischer** [comment]
✅ Test Pass - Good intro and outro, and you clearly explained the pain and the solution 👍
