### ISSUE TITLE
💄UG Pages | Fix UI

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2060]
Based on the email chain
**From**: @adamcogan 
**Sent**: Monday, January 15, 2024 4:12 PM
**To**: @jeoffreyfischer 
**Cc**: @bettybondoc; @wicksipedia; @tiagov8 
**Subject:** SSW - Brisbane Full Stack User Group 

**Description**
On https://www.ssw.com.au/netug/brisbane
The page contains several small UI fixes listed below

**Tasks**

- [x] Make the breadcrumb shorter by updating the name to "Brisbane's .NET User Group".
- [x] Change the body text to 1rem instead of the current 1.125rem.
- [x] Fill the empty space in the "Event description" section. Ask @tiagov8 what his preferred solution is.

**Extra**

In the "When & Where" section at the bottom of the page
- [x] Add top padding on the Google map

**Acceptance criteria**

- [x] Reply 'Done' to the email and also @mention Adam in the PBI with 'Done'
Note: This PBI is paired with #2061 

**Screenshots**

![PBI-UG-Brisbane-UI](https://github.com/SSWConsulting/SSW.Website/assets/106663901/9fc148b7-4394-4c41-901a-d7174aa2ed5a)
**Figure**: UI issues to fix on the UG Brisbane page

![PBI-UG-Brisbane-UI-2](https://github.com/SSWConsulting/SSW.Website/assets/106663901/0b3e88a8-422c-4480-8840-10697eef01d4)
**Figure**: Extra - add padding there

**Comment by tiagov8** [comment]
- [x] 1. "Join the crowd" button height is wrong. h-12 should be h-10. Please fix
- [x] 2. I would also reduce the size of the GitHub icon... from 80 to 60 maybe

<img width="973" alt="Screenshot 2024-01-16 at 9 17 38 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/6ba3b7ef-6378-4375-8bff-0f9334756a01">

**Comment by tiagov8** [comment]
- [x] 3. "Presenter" heading is missing margin/padding on mobile. Please fix

<img width="1067" alt="Screenshot 2024-01-16 at 9 33 53 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/b0b9cf65-80f5-43ee-a4aa-76e5308658bd">

**Comment by jeoffreyfischer** [comment]
In the same PR, also fix issue #1798

**Comment by JackDevAU** [comment]
CC @tiagov8 
I was also just looking at this page and found a lot of white space in the community section: 

1. Can this space be reduced 

![image](https://github.com/SSWConsulting/SSW.Website/assets/57518417/6244afbd-3806-4fa6-a759-f3353ffc4393)
**Figure: Community section: https://www.ssw.com.au/netug/brisbane**

**Comment by tiagov8** [comment]
Hey @JackDevAU 

> CC @tiagov8 I was also just looking at this page and found a lot of white space in the community section:
> 1. Can this space be reduced

as per chat with @jeoffreyfischer 

I think the best way is to :

1. Move the WHERE and AGENDA up, to be where the white space is. This means these 2 sections are 1 row above
2. Invert positions between PRESENTER and GITHUB
3. Move the ORGANIZER to be on the dark section, next to WHAT IS (because the ORGANIZER is related to the UG in general, not that specific session, I think this makes sense semantically)

From
![image](https://github.com/SSWConsulting/SSW.Website/assets/12601228/582ead0f-1c91-4ffc-a36d-5e51bd396657)

To

![image](https://github.com/SSWConsulting/SSW.Website/assets/12601228/c80d18b6-dabd-4037-8e69-d30e6c6a5e36)


**Note:** The ORGANIZER section is missing on the "To" because I would have to spend too much time fixing the text colors, spaces etc on mockup... I think it's easier if we do straight on the code

**Comment by tiagov8** [comment]
> CC
> I was also just looking at this page and found a lot of white space in the community section:
> 
> Can this space be reduced

Hi @JackDevAU 

The Community screenshot you sent apparently didn't load part of the content.

Normally you shouldn't see the blank area:

<img width="1277" alt="Screenshot 2024-01-30 at 6 51 54 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/6a040f76-6272-4a6a-94a0-320f7fcc278b">

**Comment by wicksipedia** [comment]
There were a couple of issues with the Community section.

1. The Twitter widget wasn't working - would return 404 (looks like Elon blocked it)
2. The Facebook widget doesn't load in Arc (at least this is how I was able to repro it) - since this is code from Facebook and not us, not sure if there's anything actionable at this time

**Comment by amankumarrr** [comment]
As per my conversation with @tiagov8, we are also going to make these changes for the sponsor's block 

<img width="771" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/ef379896-b2fc-4c3c-a215-ea443a0cc8bd">

**Figure: Sponsor's section with wide image and a button without heading** 

And also to add "read more" functionality for the event's description just like we have for the presenter. 

<img width="459" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/8ed3e191-09d2-4502-9852-09a5e84e14c8">

**Figure: Event's description has too long text**

**Comment by tiagov8** [comment]
> There were a couple of issues with the Community section.
> 
> 1. The Twitter widget wasn't working - would return 404 (looks like Elon blocked it)
> 2. The Facebook widget doesn't load in Arc (at least this is how I was able to repro it) - since this is code from Facebook and not us, not sure if there's anything actionable at this time

@wicksipedia thanks for the info

Hey @amankumarrr 
As per our conversation, I think this social embedding problem (Twitter not working + Facebook not working on Arc) should be treated in its own Issue. I don't see as a high priority for the moment

- [ ] 1. Please create the new Issue and add the link here

**Comment by wicksipedia** [comment]
Hey @tiagov8 
I've already gotten @amankumarrr to remove the Twitter widget since it was test failed on other browsers
When there is PO feedback it generally gets actioned straight-away

**Comment by amankumarrr** [comment]
All done 

### **User Group page - Before**
![before_user_group_styling](https://github.com/SSWConsulting/SSW.Website/assets/71385247/1c34a0b6-6c44-4c92-943b-31be81792de2)

**Figure: Brisbane User Group page issues** 

### **User Group page - After**
![user_group_styling](https://github.com/SSWConsulting/SSW.Website/assets/71385247/38ef9896-af1b-417e-b750-98d5e2c16d36)


**Figure: Brisbane User Group page** 


**### Mobile View - Before** 
![image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/cb764838-1a88-423d-bc35-63b081c62609)

**Figure: Brisbane - User Group page in mobile view**

**### Mobile View - After** 
![image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/cc93d035-a313-4445-9dfa-976dab943004)

**Figure: Brisbane - User Group page in mobile view**
