### ISSUE TITLE
🐛 UG Pages | Fix presenter image size

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2061]
Based on the email chain
**From**: @adamcogan 
**Sent**: Monday, January 15, 2024 4:12 PM
**To**: @jeoffreyfischer 
**Cc**: @bettybondoc; @wicksipedia; @tiagov8 
**Subject:** SSW - Brisbane Full Stack User Group 

**Describe the bug**
On https://www.ssw.com.au/netug/brisbane
The presenter image in the banner has a different size on different screens.

**To Reproduce**
1. Open https://www.ssw.com.au/netug/brisbane
2. Observe the presenter image size in the title banner

**Expected behavior**
The presenter image should have consistent size regardless of the screen resolution.

**Tasks**

- [x] Make the presenter image size the same regardless of screen resolution.
- [x] Make the presenter image size fill the title banner.
- [x] Once fixed, add a note in the SugarLearing instructions and in Sharepoint that states the preferred image size - work with @sethdailyssw 

**Acceptance criteria**

- [x] Reply 'Done' to the email and also @mention Adam in the PBI with 'Done'. 
Note: This PBI is paired with #2060 

**Screenshots/Video**

![PBI-UG-Brisbane-ImageSize](https://github.com/SSWConsulting/SSW.Website/assets/106663901/009131a8-1ace-4f3f-95be-af276a0370a9)
**Figure**: Presenter image on screen A - baby JK

![PBI-UG-Brisbane-ImageSize1](https://github.com/SSWConsulting/SSW.Website/assets/106663901/ca7e0402-d3e1-48e9-97ce-1cb88730069a)
**Figure**: Presenter image on screen B - giant JK

**Comment by sethdaily** [comment]
Hi Jeoffrey
FYI - this change should be made for all the UG pages, not just Brisbane (I assume they all come from the same place anyways).
But maybe change the title
   From
      UG | Brisbane | Fix presenter image size
   to
      UG Pages | Fix presenter image size

**Comment by jeoffreyfischer** [comment]
Hi @sethdailyssw 

      >But maybe change the title
✅ Done - the PBI title has been fixed

**Comment by amankumarrr** [comment]
@sethdaily @jeoffreyfischer 

Presenter's image size has been fixed, now we will have a fixed header and image on the header.
- The minimal height should be `1000 px` as stated in https://my.sugarlearning.com/SSW/items/10632/events-adding-events-on-ssw-events-page
- Title should remain within a range of `10 to 15` words
<img width="836" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/14ea0d6b-399c-497d-8053-fcb510a4b5ae">

**Figure: Presenter's image on the User Group page**

**Comment by jeoffreyfischer** [comment]
On SugarLearning https://my.sugarlearning.com/SSW/items/10632/events-adding-events-on-ssw-events-page the instructions now read:
- "In the title field, input the event name (10 to 15 words max)"
- "Note: for the speaker image, we need a torso image with a height of at least 1000 pixels, with a transparent background."

On Sharepoint, the instructions now read: 
- for the Presenter Torso Image: "Torso image (min height 1000 px)"
Link: https://sswcom.sharepoint.com/sites/Events/Lists/Presenters/AllItems.aspx
- for the Event name: "Title (10-15 words max)"
Link: https://sswcom.sharepoint.com/sites/Events/Lists/Events/AllItems.aspx

**Comment by Calinator444** [comment]
@jeoffreyfischer could you close this if it's no longer applicable please?
