### ISSUE TITLE
✨ UG - Add Gold Coast page

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2074]
**From**: @camillars 
**Sent**: Wednesday, January 17, 2024 7:30 AM
**To**: @jeoffreyfischer 
**Cc**: @PennyWalker @amankumarrr 
**Subject**: Gold Coast UG page missing from ssw.com.au

**Is your feature request related to a problem? Please describe.**
We are missing a page on the website for the Gold Coast UG [https://www.meetup.com/gold-coast-azure-net-user-group/events/298451887/](https://www.meetup.com/gold-coast-azure-net-user-group/events/298451887/)

**Describe the solution you'd like**
On the website, add a new page for Gold Coast and add it to the MegaMenu.

**Tasks**

- [x] Create the Gold Coast UG page.
- [x] After the page is created, add it to the MegaMenu.
- [x] Get it checked by another Dev.

**Acceptance criteria**

- [x] Reply 'Done' to the email and also @mention Camilla in the PBI with 'Done'

**Comment by jeoffreyfischer** [comment]
**Additional task**

- [x] on https://www.ssw.com.au/netug, add a component that links to the new Gold Coast page, as it is done for the other locations (Sydney, Melbourne, etc.)

**Screenshot**
![image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/ee1a123c-d361-4e5f-9662-fd04dcff6cc8)
**Figure: /netug page where a link to the Gold Coast page should be created**

**Comment by amankumarrr** [comment]
@camillars @PennyWalker @jeoffreyfischer 

As per my discussion with @sethdaily, I will add Adam as an organizer on this page. We've also discussed to retain the page title as `Gold Coast Azure .Net User Group`. While it deviates from our usual naming convention for other User Group pages (i.e., {City} {`Single Technology} {User Group}`), in this case, it follows `{City} {2 Technologies }{User Group}`.

**Comment by camillars** [comment]
@Penny Walker ***@***.***>

Should Adam be the organizer for all for MVP purposes?

Cheers.

**Comment by amankumarrr** [comment]
All done - Please see below 
<img width="1170" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/92373872-f4b6-411d-9ec8-98aba5fd28d8">

**Figure: Gold Coast UG on in megamenu**
