### ISSUE TITLE
🎨 Client Stories - Improve UI

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#2125]
cc @bettybondoc @tiagov8 @adamcogan @jeoffreyfischer @amankumarrr @camillars 

On https://www.ssw.com.au/company/clients

```[tasklist]
### Tasks
- [x] Add breadcrumb
- [x] CTA - Our Clients’ Stories – Top of the page (button)
- [x] CTA - Our Clients’ Stories – Bottom of the page (section with copy and button)
- [x] CTA - Inside the client’s Case Study page – Bottom of the page (section with copy and button)
- [x] Reply done to email - Re: SSW Website - Clients page - Inconsistent button UX
- [x] Case Study list - delete "Stuck on legacy technology" buttons
```

**Comment by wicksipedia** [comment]
(Copy of email - not the whole thread for brevity)

From: Betty Bondoc [SSW] < BettyBondoc@ssw.com.au>
Date: Tuesday, 6 February 2024 at 9:51 am
To: Jeoffrey Fischer [SSW] <JeoffreyFischer@ssW.Com.au>
Cc: Adam Cogan [SSW] < AdamCogan@ssw.com.au>, Matt Wicks [SSW] <MattWicks@ssw.com.au>, Aman Kumar [SSW]
<AmanKumar@ssw.com.au>, Tiago Araujo [SSW] < TiagoAraujo@ssw.com.au>, Camilla Rosa Silva [SSW]
<CamillaSilva@ssw.com.au>
Subject: Re: SSW Website - Clients page - Inconsistent button UX

(Checked by Tiago)

Hi Jeoffrey,

> 1. Should this button be added or removed for all clients ?

+1 to Tiago’s suggestion of putting the button at the top

As per our conversation last Friday, adding the same button to every single client on this page may be redundant and may add clutter to the UI.

I recommend having the CTA in 3 places:

- Our Clients’ Stories – Top of the page (button)
- Our Clients’ Stories – Bottom of the page (section with copy and button)
- Inside the client’s Case Study page – Bottom of the page (section with copy and button)

This ensures that the CTA is encountered by users at key moments: upon arriving at the "Our Clients’ Stories" page, after exploring the collection of stories, and after engaging with a story in depth, offering a seamless user experience without being intrusive.

Please see placements below using one of Tiago’s recommended positive wordings – Ready for a tech upgrade?

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/45e72389-7984-479e-aeb4-9a64c7a63d81)
Figure: Top of the page

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/2217f125-217a-4728-9a76-2dede8175319)
Figure: Sample section with new CTA that leads to the “Are you stuck?” page

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/1d6c61d1-cb66-4ec5-b714-393dc73e8576)
Figure: Bottom of the page

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/436286ff-80bc-41e0-9b75-a737ebc95216)
Figure: Inside the client’s case study page

> 2. Get it checked by Tiago

Done

Thanks!

**Comment by amankumarrr** [comment]
For this issue, I'm waiting for the revised content for this page from @sethdaily as per email with the subject "SSW Website - Clients page - Outdated content" 

<img width="649" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/fceccda1-fb5a-468c-bcba-61a4e3266ae5">

**Comment by amankumarrr** [comment]
All done - content is not updated as part of this issue, a new PR will be created once we get revised content. 

Also removed some uneven spacing between clients

**Screenshot:**

<img width="1219" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/cf45ebc8-4863-444d-a79d-29bb29c959ef">

<img width="1267" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/7d21acd2-927f-442e-8719-13ca3501bc11">

**Figure: New section under client and case study template**
