### ISSUE TITLE
🧪 Test coverage

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2129]
**Description**
As a developer, we would like to know how much testing is covered on the Website so that we can assess if we need more testing. Currently, there are no unit tests running on the Website.

**Documentation**
https://nextjs.org/docs/pages/building-your-application/testing
https://www.ssw.com.au/rules/what-unit-tests-to-write-and-how-many/

```[tasklist]
### Tasks
- [x] Explore available options (testing libraries) to perform code coverage
- [x] Choose the preferred option and get it approved by Matt W
- [x] Run the chosen code coverage option on SSW Website and check whether it detects the existing Integration Tests
- [x] Create a Unit Test on SSW Website (as currently no Unit Test exist)
- [x] Run the chosen code coverage option on SSW Website and check whether it detects the Unit Test created in the previous task
```

- [ ] ~Update https://www.ssw.com.au/rules/test-your-javascript - adding Vitest, Playwright, Cypress, etc to make it more applicable to modern testing frameworks~ Since we decided to use Jest which is already recommended option for testing

**Comment by wicksipedia** [comment]
can we get any stats from our existing integration tests first?

**Comment by jeoffreyfischer** [comment]
@wicksipedia ✅Done - I have included your proposed task and reorganised the others. 
Are you happy with it now?

**Comment by jeoffreyfischer** [comment]
@amankumarrr and myself have created a simple unit test with Jest - which is a recommended testing library in NextJS https://nextjs.org/docs/app/building-your-application/testing

Depending on the parameter set in the jason file, we get different results:
- with "jest", we have a list of the successful/failed tests. In the current case we purposedly set the test to fail.
- with "jest coverage" we have a list of files checked (371 here), test match and test ignore patterns.


![Image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/9140c372-4105-49cf-b900-7a370f364e39)
**Figure: Output of the Jest testing library**

**Comment by amankumarrr** [comment]
@wicksipedia @jeoffreyfischer @Harry-Ross 

I experimented with code coverage using the Vitest library, and here are my observations:

✅ **With minor adjustments, existing Playwright tests can be run.**
✅ The syntax is more straightforward and readable compared to JEST.
✅ Native support for React from @vitejs/plugin-react.
✅ Visual reports are available through the Vitest UI.

❌ One downside is the space it occupies; visual reports generate multiple files as it scans through the code.


![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/60ed5622-6b8a-4c07-82ef-fbc9371bcf2d)

**Figure: Code Coverage UI report for all the files from Vitest** 



![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/f1170eef-b169-4b66-8986-1fa8b327c45b)

**Figure: Code Coverage for test component with partial conditional component rendering**

**Comment by Harry-Ross** [comment]
As per my conversation with @amankumarrr, I tested Jest working with the project, and while there are first party integrations (i.e. `next/jest.js`) there doesn't seem to be any functional difference between using Jest and Vitest. Vitest seems like a better solution due to it being a more modern testing framework that is faster to run and is at feature parity for our purposes.

**Comment by wicksipedia** [comment]
Can we get a rule added/modified as a result of this work?

**Comment by Harry-Ross** [comment]
> Can we get a rule added/modified as a result of this work?

I think it would be a great idea to revamp this rule (adding Vitest, Playwright, Cypress, etc.) https://www.ssw.com.au/rules/test-your-javascript/ to make it more applicable to modern testing frameworks. 

Should I send myself an email task for this?

**Comment by wicksipedia** [comment]
> Should I send myself an email task for this?

Added this to the AC for this PBI instead

**Comment by amankumarrr** [comment]
@wicksipedia should we integrate Vitest into our website?

**Comment by jeoffreyfischer** [comment]
Something to keep in mind before we make a decision: Jest is widely more adopted than Vitest according to Google Trends.

![image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/93bdbb46-ed32-4ddd-ab81-bd0fefdf135c)
**Figure: Jest vs Vitest in Google Trends, showing that Jest is widely more adopted than Vitest**

**Comment by amankumarrr** [comment]
As per my conversation with @wicksipedia, @Harry-Ross and @jeoffreyfischer, we've decided to opt for the Jest library for code coverage. Although Vitest is faster, given the relatively straightforward scenarios for our website, the popularity and familiarity of Jest make it a suitable choice.

**Comment by amankumarrr** [comment]
@wicksipedia @jeoffreyfischer @Harry-Ross 
Done 

✅ Tests - Added unit tests for the `/helpers/dates.ts`
✅ Pipeline - Configured to run tests and generate report for PRs
✅ Pipeline - Configured to comment on PR for code coverage and compare the results
✅ Pipeline - Configured to run tests and generate report for main branch

<img width="924" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/d831b34f-49ed-47bc-b284-c8f98530a8ca">

**Figure: Coverage summary report on main build pipeline**
