### ISSUE TITLE
🐛 Bug - Hydration Issues + `/events` broken `setState`

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#2212]
![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/740ffa45-e49b-45fd-a565-6ec953781d3a)
**Figure: error message on the dev server on `/events`**

![MicrosoftTeams-image (7)](https://github.com/SSWConsulting/SSW.Website/assets/20507092/23cb95d5-04ca-42da-8292-c0e9fad43a36)
**Figure: hydration errors shown on homepage + `/events` which only occur on the development server**

```[tasklist]
### Tasks
- [x] Fix hyrdration issues with Chatbase
- [x] Fix broken setState on `/events`
- [x] Fix hydration issues on `/events`
```

**Comment by Harry-Ross** [comment]
As per my conversation with @jeoffreyfischer, I realised the issue was with a timezone mismatch between the server and the client, which is why it wasn't occurring on the dev server. You can see this behaviour happen in real time, as when you load the page the relative time flickers from 9 days to 10 days.

**Comment by Harry-Ross** [comment]
Before: 

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/a708f64a-cbc5-4ae0-b645-4723e26969b0)
**Figure `/events` on production**

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/faffedfe-ab0e-4e7a-bbd1-29bba2c070bd)
**Figure: `/events` on dev**

After:

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/ffb7bee0-700e-486f-b241-938fc32719c0)
**Figure: `/events` on dev**

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/20ad2ccd-b809-4582-a702-0e473ee7ae75)
**Figure: `/events` on staging env**
