### ISSUE TITLE
💄 UI - Error Page Designer Review 

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#2239]
cc @tiagov8 @jaydenalchin 

As per https://github.com/SSWConsulting/SSW.Website/issues/1587, new error pages were created, replicating the design of the current 404 page: 

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/c5b4d220-ec87-4583-838c-f63af0c43ea9)
**Figure: Current 404 page**

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/5bfd4401-8c1d-4c45-8c56-888bc240fa7d)
**Figure: The newly added 500 page**

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/b0ad78a5-5de3-4504-9b51-01f90d264f04)
**Figure: the new behaviour on a standard React error (example here is when `next/link` is misued)**

```[tasklist]
### Tasks
- [ ] Consult with designers on a new design that aligns more closely to Rules or SugarLearning 
```

**Comment by tiagov8** [comment]
Hi @Harry-Ross 

The description of the task is a bit vague, as the current design is already aligned with Rules. The other Issue https://github.com/SSWConsulting/SSW.Website/issues/1587 doesn't say anything about design...

I am not the biggest fan of this error page design, but I am OK with it (don't see a redesign as a priority). 
Did the Product Owner requested a new design for these pages?

--

From what I see in your 3 screenshots, the only thing I would fix is the button "see details":

- [ ] 1. Add padding to button (e.g. 0.5rem)
- [ ] 2. Add margin-bottom to the button (e.g. 1rem)
- [ ] 3. Make the border lighter (e.g. same as text color)

**Comment by Harry-Ross** [comment]
cc @wicksipedia 

> The description of the task is a bit vague

Yep, this issue will be fleshed out more later, and then will be moved into "Ready" when it's more clear what the task is. 

> Did the Product Owner requested a new design for these pages?

Yes, Matt W requested a review of these error pages, but as a low priority item. 

>  3. Make the border lighter (e.g. same as text color)

Already done - there's no border on the button, this was just because it was selected:

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/03314a6d-22d0-419f-9576-c2a1627e1069)
