### ISSUE TITLE
📄Migration | Logo | Past Logos page

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2240]
URL: https://ssw.com.au/ssw/logo/Past.aspx

We need to migrate this logo page to our new website.

### Tasks
- [x] Ask @wicksipedia what the URL should be on the new website - maybe https://www.ssw.com.au/logo/past
- [x] Create the page
- [x] Add Front Door redirection from the old to the new page

**Screenshots**
![image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/5cc5f33e-6b83-4727-b072-bf876a52802a)
**Figure: Past Logos page**

**Comment by andrewwaltosssw** [comment]
Done - Migration completed for `logo/past`
Created new page using content from old site, created FrontDoor redirect and deployed both to prod:


![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/ac7c87fd-11d2-430c-97ad-3ca096397d0e)
