### ISSUE TITLE
📄Migration | Logo | Guideline page

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2241]
URL: https://ssw.com.au/ssw/logo/SSW/

We need to migrate this logo page to our new website.

### Tasks
- [x] Ask @wicksipedia what the URL should be on the new website - maybe https://www.ssw.com.au/logo/SSW
- [x] Create the page
- [x] Add Front Door redirection from the old to the new page

**Screenshots**
![image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/bf4c830d-5295-482e-a0b6-c1f8c093c2dc)
**Figure: Logo guidelines page**

**Comment by amankumarrr** [comment]
Done 

<img width="790" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/06959449-1505-46fb-bc40-79041fa1812f">

**Figure: SSW logo page for the larger screens**

![image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/c351b444-8b8a-4fc7-aa17-c683332ccdd5)

**Figure: SSW logo page for the mobile screens**
