### ISSUE TITLE
📄Migration | Logo | Index page

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2246]
URL: https://ssw.com.au/ssw/logo/Default.aspx

We need to migrate this logo page to our new website.

### Tasks
- [x] Ask @wicksipedia what the URL should be on the new website - maybe https://www.ssw.com.au/logo
- [x] Create the page
- [x] Add Front Door redirection from the old to the new page
- On Past Logos page:
  - [x] Change browser title and page title from "SSW Past Logo Index" to "SSW Past Logos"
  - [x] 'logo' in breadcrumbs to be capitalised from "logo" to "Logo"

**Screenshots**
![image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/4f17dc32-d21f-4e34-84c1-3570973a4bd0)
**Figure: Past Logos page**

**Comment by andrewwaltosssw** [comment]
![image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/af72aefa-93de-487f-aeee-a6ecf80e928f)
**Figure: Migrated Logo page on Website https://www.ssw.com.au/logo**
