### ISSUE TITLE
🔎 SEO - Make SEO Fixes

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#2248]
cc @jeoffreyfischer @wicksipedia @camillars 

As per Jeoffrey's conversation with Matt W, we have had a downturn in leads coming from Google. 

![MicrosoftTeams-image (8)](https://github.com/SSWConsulting/SSW.Website/assets/20507092/1303e429-966e-4552-8f06-385962ca9a49)
**Figure: Low search ranking on Google (14th on the list)**

```[tasklist]
### Tasks
- [ ] Run Semrush on the site, fix SEO issues
- [ ] Check all tags are performing
- [x] Fix Canonical URLs
- [x] Add codeauditor + redirects to robots
- [ ] Fix images on /events on SharePoint
```

**Comment by Harry-Ross** [comment]
I'm currently using, and fixing issues as I go:

1. Semrush - https://www.semrush.com/siteaudit/campaign/15984152/review/#overview
2. PageSpeed Insights/Lighthouse
3. SEOptimiser - https://www.seoptimer.com/www.ssw.com.au#hasFriendlyUrl43065015
4. SEO Site Checkup - https://seositecheckup.com/

Progress:

1. The first issue found was with the `/events` route, which was showing erraneous values on PageSpeed Insights:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/268b45e7-5514-4f93-a51b-b51181a49da4)
**Figure: https://pagespeed.web.dev/analysis/https-www-ssw-com-au-events/kecblc4tp8?form_factor=mobile**

I investigated this, and found it to be an issue with the size of the page, as when the accessibility plugin they use (Axe) parses a page that is too big, it will crash and return all the errors as seen above. I'm currently working on creating an infinite scroll on the events page to shrink the size of the page.

2. There was a small issue that I fixed as a part of issues with links on the main page:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/b41aa574-0a61-4fc7-bfed-ea3d8536a502)

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/66f3c749-dbc6-4415-be9b-1ca2c6821936)

Which was done by changing the value on SharePoint, and is now fixed.

3. There was also a problem with the megamenu flag icons: 

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/8ff5ada1-f720-400e-8c5c-864614f7e332)
**Figure: https://pagespeed.web.dev/analysis/https-www-ssw-com-au/vjmgwylfqf?form_factor=desktop**

This was fixed in https://github.com/SSWConsulting/SSW.MegaMenu/pull/84, and is now published as `ssw.megamenu@4.5.2`. 

4. I've also added `TTFB` and `FCP` to be tracked on App Insights, so we can get a better picture of these metrics over time. 

Overall, the primary focus has also been on increasing the performance score as set out in PageSpeed Insights, as many of the other tools haven't provided useful steps on fixing SEO. I will also be discussing including the `/history` sitemap in the main sitemap with Matt W.

**Comment by Harry-Ross** [comment]
By adding a placeholder div, I have reduced the CLS value to zero:

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/efdc2acf-7d76-4021-a47b-5346b6107d31)
**Figure: Before - https://pagespeed.web.dev/analysis/https-app-sswwebsite-9eb3-pr-2253-azurewebsites-net/u57eeavzrj?form_factor=desktop**

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/15827544-f253-4475-be20-e26bc54ba145)
**Figure: After - https://pagespeed.web.dev/analysis/https-app-sswwebsite-9eb3-pr-2253-azurewebsites-net/jlqi94j2wo?form_factor=desktop**

**Comment by Harry-Ross** [comment]
![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/2667e2bc-5f69-467b-b966-65a5410fe3fb)
![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/b907f0e0-c607-4fb7-b21b-85d9a3d2ef29)
**Figure: Before - https://pagespeed.web.dev/analysis/https-www-ssw-com-au/m1g663eo3u?form_factor=mobile**

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/0810231a-a5c5-4397-9803-482bdd7631fd)
![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/5749dca0-5702-4c42-8fee-66965f829f32)
**Figure: After - https://pagespeed.web.dev/analysis/https-www-ssw-com-au/bx4ao2ejjy?form_factor=mobile**
