### ISSUE TITLE
📄 Docs - Add SharePoint Documentation

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#2249]
As per my conversation with @amankumarrr, there is currently no guide in our repo on how to edit SharePoint events. 

```[tasklist]
### Tasks
- [x] Check with Camila and Seth if documentation already exists
- [x] If the documentation already exists, put a link to it in the wiki
- [x] I not, add information on how to edit SharePoint events on the repo wiki
```

**Comment by Harry-Ross** [comment]
Update: I've started working on the draft here: https://github.com/SSWConsulting/SSW.Website/wiki/SharePoint-Events

**Comment by Harry-Ross** [comment]
Update: I've written the first draft, will try to get a review from Camilla + a dev on the website team.

**Comment by Harry-Ross** [comment]
Done - Test Pleased by @camillars and @amankumarrr:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/f271bd66-8b31-4714-b22a-430fd89875e7)
**Figure: Test Pleased**
