### ISSUE TITLE
SEO - FrontDoor - Add HSTS headers

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#2255]
Address semrush audit error

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/192dec9c-b1dd-4281-9a60-6db4db849b9f)

```[tasklist]
### Tasks
- [x] Check 301 redirects
- [x] Implement 301 redirect
- [x] Check canonical tags
- [x] Implement headers - https://learn.microsoft.com/en-us/azure/frontdoor/standard-premium/how-to-add-security-headers
- [x] Re-run audit to check that error is removed
- [ ] Add HSTS header
```

**Comment by wicksipedia** [comment]
Front door is returning 302 redirects

![CleanShot 2024-03-11 at 10 11 15](https://github.com/SSWConsulting/SSW.Website/assets/600044/d0ad7d6d-bb96-4639-a59f-4579e06a1cb2)

**Comment by wicksipedia** [comment]
done

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/65b00cca-52a9-47c5-8619-6921bf6db151)
**Figure - http to https redirects are now 301s**

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/01ec84b5-b606-4051-aabf-a93b85d0bc5b)
**Figure: https responses now have a CSP header**

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/ba4d7c25-1cb4-486d-bb70-3cefd7b3c1d8)
**Figure: HSTS header present in responses**

**Comment by wicksipedia** [comment]
rolled back CSP header as it was causing prod issues
