### ISSUE TITLE
🔎 SEO - Create Core Web Vitals Workbooks

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#2266]
cc @wicksipedia @jeoffreyfischer 

As per https://github.com/SSWConsulting/SSW.Website/issues/2248#issuecomment-1990165140, we will be tracking `TTFB` and `FCP` using Next.js' `useReportWebVitals` hook and tracking this as a custom metric to App Insights.

```[tasklist]
### Tasks
- [x] Create custom App Insights workbook(s) that summarise this information (i.e. graphs for P95 of each metric (95th percentile), etc.)
- [x] Create a rule on learnings from this PBI i.e. how to use App Insights to monitor Core Web Vitals
- [x] Make a Done Video
```

**Comment by Harry-Ross** [comment]
Created a version of the workbook that works with the dev container (blocked for prod by https://github.com/SSWConsulting/SSW.Website/pull/2328):
https://portal.azure.com/#blade/AppInsightsExtension/UsageNotebookBlade/ComponentId/%2Fsubscriptions%2Fb8b18dcf-d83b-47e2-9886-00c2e983629e%2Fresourcegroups%2Fssw.com.au%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fappinsight-sswwebsite-dev-9eb3/ConfigurationId/%2Fsubscriptions%2Fb8b18dcf-d83b-47e2-9886-00c2e983629e%2FresourceGroups%2Fssw.com.au%2Fproviders%2Fmicrosoft.insights%2Fworkbooks%2Fc69500ca-08c7-4bfc-ab59-05332adfd067/Type/workbook/WorkbookTemplateName/Core%20Web%20Vitals



![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/5b18f40f-3278-435c-aa55-ded4d0b9ae10)
**Figure: The graph with varied performance scores aggregated (numbers are off because its the dev server)**

**Comment by Harry-Ross** [comment]
Workbook link: https://portal.azure.com/#blade/AppInsightsExtension/UsageNotebookBlade/ComponentId/%2Fsubscriptions%2Fb8b18dcf-d83b-47e2-9886-00c2e983629e%2Fresourcegroups%2Fssw.com.au%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fappinsight-sswwebsite-dev-9eb3/ConfigurationId/%2Fsubscriptions%2Fb8b18dcf-d83b-47e2-9886-00c2e983629e%2Fresourcegroups%2Fssw.com.au%2Fproviders%2Fmicrosoft.insights%2Fworkbooks%2Fc69500ca-08c7-4bfc-ab59-05332adfd067/Type/workbook/WorkbookTemplateName/Core%20Web%20Vitals

**Comment by Harry-Ross** [comment]
Done Video: https://youtu.be/ztIEY60ZssY
