### ISSUE TITLE
📄Migration | Logo | SSW TV page

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2276]
URL: https://ssw.com.au/ssw/logo/SSW-TV/

We need to migrate this logo page to our new website.

### Tasks
- [x] Ask @wicksipedia what the URL should be on the new website - maybe https://www.ssw.com.au/logo/SSW-TV
- [x] Create the page
- [x] Add Front Door redirection from the old to the new page

**Comment by andrewwaltosssw** [comment]
blocked - waiting on SVGs from designers. contacted Jayden to help

**Comment by andrewwaltosssw** [comment]
Page migrated:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/4fa52683-ade4-4512-a488-e2e857ee2a3a)
**Figure: SSWTV logo page on new website https://www.ssw.com.au/logo/ssw-tv**
