### ISSUE TITLE
✨ Newsletter - Create a JotForm for subscription 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2288]
URL: https://www.ssw.com.au/newsletters

**Additional context**
As per my conversation with @wicksipedia , we need to create a Jotform to address the validation issues present in the existing newsletters subscription.

```[tasklist]
### Tasks
- [x] Create a JotForm
- [x] Embed it with our website
- [x] Create a Power Automate to submit subscription into CRM
- [x] ~~ZZ old flow that caters the submission of the newsletter~~ To be carried out on task https://github.com/SSWConsulting/SSW.Website/issues/2409
```

Screenshot:
<img width="757" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/c8812534-9dd8-46ef-8f7c-7202b9dc8d6f">

**Figure: Newsletter's form**

**Comment by amankumarrr** [comment]
Hey @wicksipedia,

Currently, our Power Automate flow provides a response whenever there's a submission to our CRM, checking if the contact already exists. However, if we transition to using JotForm, this response won't be visible as the flow triggers only on JotForm submissions, and the current setup doesn't support sending the status/response.

1. Should we proceed with this change, even if we can't display the CRM response?

**Comment by Calinator444** [comment]
As per my conversation with @amankumarrr , Aman would like to discuss this PBI further with @wicksipedia before proceeding.

Here's a link to the jot form I've created so far:

https://www.jotform.com/build/240982184214052

**Comment by jeoffreyfischer** [comment]
Example of an existing subscription component on a different page
URL: https://ssw.com.au/live?liveStream=1

**Screenshot**
![Image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/9de49b64-71b2-43d9-b793-b6a3ddfdaa22)
**Figure: Subscription component**

**Comment by andrewwaltosssw** [comment]
- UI checked by designer https://github.com/SSWConsulting/SSW.Website/pull/2451#issuecomment-2058102984

JotForm created and embedded into our website:
![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/2729a2ff-b917-463d-9cfb-b9f73c5864fd)
**Figure: Screenshot of the form on newsletters page**

**Comment by andrewwaltosssw** [comment]
![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/83fa1b63-782e-4c26-94bd-d1d568b8f203)
**Figure: Donegif of email validation and submission**

**Comment by andrewwaltosssw** [comment]
JotForm created using info@ssw.com.au credentials in Keeper.

Form can be found here: https://www.jotform.com/240991361342051

Wiki updated to show instructions for editing this form: https://github.com/SSWConsulting/SSW.Website/wiki/Editing-the-website#updating-newsletter-sign-up-form
