### ISSUE TITLE
📄SSW Website v1 - Investigate any page that links to Booking form 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2339]
Subject: Old website crawled pages with a form - any missed opportunities?
CC: @wicksipedia @PennyWalker @uly1 @sethdaily 
FROM: @camillars 
 
> As per my conversation with Matt W, I just got a phone call from a client based in Sunshine Coast looking for a HoloLens experience. 
He mentioned he only called because the form on the website did not work, and it got me wondering if there are any relevant pages on the old website with a form that doesn’t work that could be leading to missed opportunities.

```[tasklist]
### Tasks
- [x] Investigate if we have any missing leads log
- [x] Investigate if there are any other pages that are still accessible and has that form
- [x] Add redirect/migrate where necessary
```

**Comment by amankumarrr** [comment]
@camillars @wicksipedia 

I've reviewed the Raygun logs for the past six months, but I couldn't find any errors apart from one 405 error. Unfortunately, this error didn't contain any useful payload or meaningful information for our Website v1.

<img width="823" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/e60dfa74-c701-4ddc-b641-a348bffb5ab9">

**Figure: Raygun logs for past 6 months - https://app.raygun.com/crashreporting/iushhj?range=180+day#active**

I've implemented the Front Door redirection for the page https://www.ssw.com.au/ssw/Events/HoloLens-experience.aspx, so it's no longer accessible.

**Comment by amankumarrr** [comment]
@camillars @wicksipedia 

Upon investigating the SSW Website v1, I found some more pages that still have broken booking forms:

https://ssw.com.au/ssw/consulting/Vault.aspx (Possibly migrate this page)
https://ssw.com.au/ssw/consulting/Video-Production/Default.aspx (Add Front Door redirection to /video-production)
https://ssw.com.au/ssw/Hosting/Default.aspx (Undecided)

**Comment by amankumarrr** [comment]
@wicksipedia @camillars 

All the pages mentioned above are now inaccessible and have been redirected as follows:

- https://ssw.com.au/ssw/consulting/Vault.aspx ➡️ https://ssw.com.au/consulting/security
(This was approved by @tiagov8)

- https://ssw.com.au/ssw/Hosting/Default.aspx ➡️ https://ssw.com.au/consulting/azure
(This was approved by @william-liebenberg)

- https://ssw.com.au/ssw/consulting/Video-Production/Default.aspx ➡️https://ssw.com.au/consulting/video-production
(No approval is needed for this as we've already migrated this page. This is just an additional request path for the redirection: /Default.aspx)

**Comment by camillars** [comment]
@UlyssesMaclaren @miichaelsmedley FYI - fixed

**Comment by amankumarrr** [comment]
@camillars @wicksipedia @Harry-Ross @UlyssesMaclaren @miichaelsmedley 

I'm reopening this issue because there are several pages containing a Booking form, even if they are under the /history section and considered archived. This could potentially cause us to lose clients who land on these pages.

If you Google 'Hololen experience in Australia', you'll find links to both our archived and old pages. Although we've implemented a redirection for the old page, it still appears because we've archived it under 'history/'. The issue is that it's not clear from the archived page how a client should proceed.

![Hololen-History-Page](https://github.com/SSWConsulting/SSW.Website/assets/71385247/00889600-556b-444c-934b-f210bc43aaa9)

**Figure: Google result on Hololen experiernce** 


Upon further investigation, I discovered that there are booking buttons on the pages we've already archived, listed as follows:

https://www.ssw.com.au/history/events/2007-net/default.html
https://www.ssw.com.au/history/events/2009-uts-sql/default.html
https://www.ssw.com.au/history/events/2010-uts-sql/default.html
https://www.ssw.com.au/history/events/training/advanced-tsql.html
https://www.ssw.com.au/history/events/training/brain-quest-vs-tfs-sharepoint.html
https://www.ssw.com.au/history/events/training/qut-angular-2.html
https://www.ssw.com.au/history/events/training/vs-2012.html

**Comment by amankumarrr** [comment]
@camillars @miichaelsmedley @Harry-Ross 

As per discussion with @wicksipedia, we consider this a lower priority. We can either disable or hide the "book now" button, but it's important to maintain it for SEO purposes
