### ISSUE TITLE
🔎 Semrush - Weekly track and improve SEO #1

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2343]
https://www.semrush.com/siteaudit/campaign/16078651/review#overview
Pain: The website performance is good but not great.
Solution: use Semrush to track issues and fix them
```[tasklist]
### Tasks
- [x] Fix broken internal links
- [x] Fix canonical on history pages
- [x] Fix toxic backlinks as per convo with Seth
- [ ] Fix canonical URLs on rules
- [x] Remove external URLs from sitemap
- [x] Fix broken canonical links on Website
```

**Comment by Harry-Ross** [comment]
As per my reply to @camillars's email, canonical URLs were fixed for all `/history` pages and the "Soft 404" issue was fixed by removing a page that had no content:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/bec45a70-176d-4996-8e04-1435ffb96803)

Commit to fix sitemaps on archived pages: https://github.com/SSWConsulting/SSW.Website-v1-Progress/commit/0dc2c2e6276c1497beabdd59dc49ee335d2ac853

**Comment by Harry-Ross** [comment]
1. Semrush found a bunch of broken links on SSW Rules, this was fixed in https://github.com/SSWConsulting/SSW.Rules.Content/pull/8266.

2. Semrush found broken canonicals with history pages + a "soft 404" was detected with an old events page on Search Console, so I fixed those in https://github.com/SSWConsulting/SSW.Website-v1-Progress/commit/0dc2c2e6276c1497beabdd59dc49ee335d2ac853

3. As per my conversation with Seth, toxic backlinks were found and removed as a part of Semrush, and uploaded to the Google Disavow list. More links are to come, but this is a start for now as I'd like to see the effect on SEO first. Semrush generates a list of toxic links as a txt file, which can be imported into Google.

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/168bfc91-dc07-46c0-ae79-b17b64533d29)
**Figure: List of toxic backlinks you can choose to disavow in Semrush**

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/5cd3ee7f-9094-4bfd-9c30-e7670ef31640)
**Figure: Addition of toxic backlinks**

4. There was an issue on Google Search Console relating to SSW rules canonical links, I initially thought it was to do with use of Helmet instead of the Gatsby head API, but then I realised it was just due to the rules being able to be accessed without www, so this is a non-issue. 

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/60ddc4d6-bf0f-49d0-a569-5609010a18e7)
**Figure: "Broken" canonicals**

5. Google also complained about external URLs being in the sitemap file:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/e37759c2-067a-44f4-942e-9b6758d19582)
**Figure: External URLs in sitemap**

These was removed in the SEO improvement PR. 

6. There were general fixes to weird canonical links as a part of the linked PR
