### ISSUE TITLE
📄 Website v1 - Redirect links | Migrate pages that are used

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#2374]
Following on from #2372

Note: number of links to migrate will influence implementation

Important: Only start this PBI after 20 April 2024

```[tasklist]
### Tasks
- [x] Review GA stats for `/ssw/redirect`
- [x] zz the redirect pages that received 0 hits
- [x] Migrate the remaining links to Website v3 - None to migrate
```

**Screenshot**

![Image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/cb076b20-0086-4eb2-8aaf-f24a4e330a29)
**Figure: Location of the /Redirect folder in the Repo**

**Comment by jeoffreyfischer** [comment]
Note: I have written a script that tests the status code returned by all of the pages located in the /Redirect folder.
Below is the result I got: 

![Image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/3c77e67a-4c1e-4834-8c0f-c1a524392540)
**Figure: Count of status Code obtained for all the /Redirect pages**

**Comment by andrewwaltosssw** [comment]
@jeoffreyfischer @Calinator444 
I had a look at GA for the required results. You can view this incl filters i used [here](https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com/about/analytics/#/p264047466/reports/explorer?params=_u..nav%3Dmaui%26_r.explorerCard..seldim%3D%5B%22landingPageMinusQueryString%22%5D%26_r..dataFilters%3D%5B%7B%22type%22:1,%22fieldName%22:%22landingPage%22,%22evaluationType%22:3,%22expressionList%22:%5B%22ssw%252Fredirect%22%5D,%22complement%22:false,%22isCaseSensitive%22:true,%22expression%22:%22%22%7D%5D%26_r.copa-filter-builder..filter-to-edit%3D%5B%7B%22type%22:1,%22fieldName%22:%22landingPage%22,%22evaluationType%22:3,%22expressionList%22:%5B%22ssw%252Fredirect%22%5D,%22complement%22:false,%22isCaseSensitive%22:true,%22expression%22:%22%22%7D%5D%26_u.comparisonOption%3Ddisabled%26_u.date00%3D20240406%26_u.date01%3D20240420&r=landing-page&ruid=landing-page,life-cycle,engagement&collectionId=5215403492)

![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/b37ad93f-71aa-4f05-977d-ab474b75d5e4)
**Figure: Screenshot of hits for `/ssw/redirect*` for a 2 week period**

**Comment by wicksipedia** [comment]
As per my conversation with @adamcogan, we agreed to **_not_** migrate the `/redirect` pages since the telemetry says that they are not used (enough to warrant the effort).

**Comment by andrewwaltosssw** [comment]
All redirect files in v1 migration progress repo have been zz'd.
