### ISSUE TITLE
📄 Migration | Sharepoint Benefits page

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2380]
Migrate the following page to the new SSW website: https://www.ssw.com.au/ssw/Consulting/NewSharePointBenefits.aspx

```[tasklist]
### Tasks
- [x] Check with @JeanThirion whether he want this page migrated
- [x] Migrate the page to `/history/consulting/new-sharepoint-benefits`
- [x] Create FrontDoor Redirect
```

**Comment by JeanThirion** [comment]
Hey Jeo,


  1.  Is CrashPlanPro still a product ?
  2.  How good does it compare to N-ebable or similar backup product we currently use ?
  3.  Curious – why ask me ? SysAdmins would know better about backups (although I’m happy to make the call)

If it’s vastly outdated and no longer useful, we can migrate the page as-in and archive it straight away for record keeping, but no value in keeping it alive.

Cheers










Jean Thirion   |   SSW France CEO + Solution Architect<http://www.ssw.com.au/People/Jean-Thirion?utm_source=emailsignature>   |    +61 402 924 179<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Ping me on ***@***.***>

From: Jeoffrey Fischer [SSW] ***@***.***>
Sent: Wednesday, March 27, 2024 5:55 PM
To: SSWConsulting/SSW.Website ***@***.***>
Cc: Jean Thirion [SSW] ***@***.***>; Mention ***@***.***>
Subject: [SSWConsulting/SSW.Website] 📄 Migration | Sharepoint Benefits page (Issue #2380)


Migrate the following page to the new SSW website: https://www.ssw.com.au/ssw/Consulting/Crash-Plan-Pro.aspx

  *   [ ] Check with @JeanThirion<https://github.com/JeanThirion> whether he want this page migrated
If yes:
  *   [ ] Migrate the page
  *   [ ] Create FrontDoor Redirect

**Comment by wicksipedia** [comment]
@JeanThirion - wrong url in original description, its for a SharePoint page

**Comment by JeanThirion** [comment]
@wicksipedia Gotcha

Well, SharePoint 2016 is no longer supported and is soon reaching end of extended support:
https://techcommunity.microsoft.com/t5/microsoft-sharepoint-blog/what-s-new-for-sharepoint-server-march-2024/ba-p/4082490 (last bullet point)

I would say we can migrate as-is and archive if we care about the information for future generations, but I don't think this is going to drive much traffic. 
I'm happy for it to be simply killed if you want - no real value to me.

**Comment by wicksipedia** [comment]
ok, since we aren't deleting content - we'll migrate it to `/history/consulting/new-sharepoint-benefits`

updated description to match

**Comment by Calinator444** [comment]
@wicksipedia I may not get this done before the sprint review. I've migrated the page, fixed any broken links and previewed the changes in VS Code. I'm hoping to have @Harry-Ross review my [PR](https://github.com/SSWConsulting/SSW.Website-v1-Progress/pull/27) before merging because the files being pushed to the v1 repo (which he owns).

![Sharepoint benefits page in vs code preview window](https://github.com/SSWConsulting/SSW.Website-v1-Progress/assets/65635198/02017653-5c5f-469b-a84d-472747b3ce89)

**Comment by Calinator444** [comment]
@wicksipedia 

I double-checked to make sure the Front Door redirect was working correctly this morning correctly. That was the last step so I'm marking this as done.



![Image](https://github.com/SSWConsulting/SSW.Website/assets/65635198/3aed1340-6bc1-46d4-af6d-f717bb21d015)
