### ISSUE TITLE
🔎 Semrush - Weekly track and improve SEO #2

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2383]
```[tasklist]
### Tasks
- [x] Remove /history sitemap
- [x] Validate robots.txt
- [x] Fix structured data on main page
- [ ] Investigate downturn from Search Console
```
