### ISSUE TITLE
Consulting - Improve INP score for mobile

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#2385]
After reviewing https://search.google.com/u/1/search-console/core-web-vitals/drilldown?resource_id=sc-domain%3Assw.com.au&item_key=CAUQAhgD

Consulting pages are failing core web vitals for mobile

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/8dd1bcc8-6191-46bc-bfc9-4325e4b73a76)

```[tasklist]
### Tasks
- [ ] Improve score for index page
- [ ] Improve score for consulting template
- [ ] Search console - validate fix
```

**Comment by Harry-Ross** [comment]
Update: this issue has disappeared in Google Search Console. Parking for now. 

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/9a5d9223-f65f-4031-a6c0-0ee27ef32f88)
