### ISSUE TITLE
✨ Add a Github action to automate pushing archived files to blob storage

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#2435]
As per my conversation with @fenix2222 

CC: @amankumarrr @bradystroud @andrewwaltosssw @Harry-Ross @johnxu16 @jeoffreyfischer @KristenHu 

The [archiving repo](https://github.com/SSWConsulting/SSW.Website-v1-Progress/pull/24) has a script for pushing archived pages to blob storage whenever a new page is migrated. running this script manually each time a new page is added can be repetitive. Running the whenever a pull request is merged can easily be automated using a GitHub Action.

```[tasklist]
### Tasks
- [x] Add a GitHub action that runs the upload script on a merge event
- [x] Modify the script to allow it to be [manually run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)
```

- [x] Approved by @wicksipedia

**Comment by Calinator444** [comment]
@wicksipedia Could you review this PBI please? Creating it for the record

**Comment by Calinator444** [comment]
@wicksipedia 

@Harry-Ross and I tested the action and it's uploading the files to blob storage when run manually.
