### ISSUE TITLE
⛓️ Industry - broken link in breadcrumb

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#2437]
cc: @adamcogan @SSWConsulting/sswmarketing 

According to SEMrush, there is a broken link on https://ssw.com.au/industry/non-profit

The link going to https://ssw.com.au/industry results in a 404 as the page doesn't exist.

```[tasklist]
### Tasks
- [x] Add page for `/industry` with links to child routes (get content from @sethdaily)
- [x] On `/industry/educational`, add breadcrumb similar to `non-profit`
- [x] On `/industry/finance`, add breadcrumb similar to `non-profit`
```

**Comment by Calinator444** [comment]
@wicksipedia 

Done,

Here's a link to the live page: 
https://www.ssw.com.au/industry

**Note**: this is modifiable through tina
