### ISSUE TITLE
📄 Move events from /history/events to /events archived

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#2465]
@wicksipedia 

CC: @adamcogan  @fenix2222 @tiagov8 

As per my conversation with @fenix2222 , we want archived pages that were previously under the `/events` route to be stored in their own separate directory on the website rather than in the`/history` directory.

```[tasklist]
### Tasks
- [ ] Update migration script to move events to the `events/archived/xxx` directory
- [ ] Move all previously migrated events to the new directory
- [ ] Add new `events/archived/xxx` route
```

- [ ] Checked by Wicksy

**Comment by Calinator444** [comment]
@wicksipedia Could you please check this PBI?

**Comment by wicksipedia** [comment]
As per conversation with @adamcogan, this can be done after all the pages have been archived. Otherwise it will delay shutting off the vm
