### ISSUE TITLE
✨ Implement video schema on ssw.com.au

### ISSUE THREAD

**Issue by camillars** [SSWConsulting/SSW.Website#2537]
cc @wicksipedia @tiagov8 @landonmaxwell @bahjatalaadelssw 

**Is your feature request related to a problem? Please describe.**
Adding video schema to the website will help search engines better understand and display your video content in search results.

**Describe the solution you'd like**
Implement a video schema - https://www.semrush.com/blog/video-schema/ and https://developers.google.com/search/docs/appearance/structured-data/video

**Describe alternatives you've considered**
I don't believe there are any alternatives since this is a best practice for SEO.

**Additional context**
Pages with a video will look like this on a Google search:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/53064613/98034a6e-d4fd-4e4b-a379-de764d9935cf)

```[tasklist]
### Tasks
- [ ] Understand how to implement it across the website
- [ ] Implement on ssw.com.au
- [ ] Open issue to replicate this on /rules and /people next
```
