### ISSUE TITLE
Product Support page: outdated content and references unsupported SSW products

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Website#258]
The Product Support page at https://www.ssw.com.au/ssw/Standards/Support/BugReportOrEnhancement.aspx needs a refresh of its content:

```[tasklist]
### Tasks
- [ ] Remove references to unsupported SSW products,  eXtreme Emails and SSW Diagnostics.
- [ ] Remove references to other old products, e.g. Fullshot
- [ ] Fix links to rules and KB articles
- [ ] Decide what we really want customers to provide us with in terms of information and build new content accordingly (to include new screenshots, etc.)
```
