### ISSUE TITLE
📄 Add meta descriptions to all pages with placeholders

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#2594]
CC: @calumjs, @wicksipedia, @UlyssesMaclaren, @sethdaily, @camillars,@wicksipedia

### Description 
As per my conversation with Ulysses, Seth and Camilla it should be possible to replace all of the placeholder meta descriptions with. AI generated meta descriptions using API Calls 

**Note**: 

### Steps
- [ ] Create a script that will run through each markdown file on the site and generate a meta description (If the page doesn't already have one)
- [ ] The meta descriptions for each page should be generated using an Open AI API call
- [ ] Export all of the modified meta descriptions in a XLSX file using the following format for each row:

old meta description|updated meta description|Page title|checked by camilla|Page URL

**Additional context**
The rules pages also have a number of duplicate meta descriptions. The intention is to perform these changes to the rules page as well

**Video**

https://github.com/SSWConsulting/SSW.Website/assets/65635198/d3f37eb5-587d-49f0-af98-04da9dde90ac

**Comment by Calinator444** [comment]
https://www.youtube.com/watch?v=VUvyYBOMnDA

**Comment by Calinator444** [comment]
The work in this PBI was completed in this PR

https://github.com/SSWConsulting/SSW.Website/pull/2746
