### ISSUE TITLE
🐛 Unable to edit newly created pages in Tina 🐛

### ISSUE THREAD

**Issue by andrewwaltosssw** [SSWConsulting/SSW.Website#2643]
cc: @amankumarrr @wicksipedia @samsmithssw @scottgallant
**Describe the bug**
When creating a new page via Tina Admin on production site, I am unable to edit the page due to getting a 500 and/or 404 error

**To Reproduce**
1. Go to www.ssw.com.au/admin and login
2. Create a new branch
3. Tina Menu | Consulting - Pages
4. Click "Create New +"
5. Add a filename and click "Save"
6. After auto-reload find the newly created file and click it
7. Preview shows 500 error and sometimes 404 error

**Additional Info**
This behaviour does not happen when adding a page from Tina Admin on a PR slot URL

**Acceptance Criteria**
- see the newly created file to make my content edits
- get the fix on TinaCloud starter

```[tasklist]
### Tasks
- [x] ~Add a draft mode OR ISR setting to pages that allows visual editing for newly added pages (see what works).~ Enabled dynamic Routing
- [ ] If successful, update the Tina.io documentation to include a tutorial on how to achieve this effect (I believe it would be a common complaint with the editorial workflow).
- [ ] If successful, notify the Tina.io team of the workaround (they have had a similar problem) and work with them to set up the fix.
```

Note: If this suggested solution doesn't work, work with Jack P to find a fix.

**Screenshots/Video**
![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/6fe8ddf2-1249-466e-ae70-2ccbbafdf855)
**Figure: The error i'm seeing**

**Comment by andrewwaltosssw** [comment]
As per discussion with @JackDevAU, This behaviour is present on the Tina.io repo on production. Further investigation to be done by TinaCMS team

[link to issue on TinaCloud repo - not everyone will have access.](https://github.com/tinacms/tina-cloud/issues/2012)

**Comment by isaaclombardssw** [comment]
This might be possible if we try and leverage Next.js's draft mode.

See this convo...

![Image](https://github.com/user-attachments/assets/556b3963-aa77-4b74-abd4-199f6f6802ec).

Linked info...

https://nextjs.org/docs/app/building-your-application/configuring/draft-mode

https://tina.io/docs/drafts/overview

We should prioritise this as it directly impacts Louis ability to make the new consulting pages.

**Comment by isaaclombardssw** [comment]
Matt suggested looking into ISR as a solution for this 

https://nextjs.org/docs/app/building-your-application/data-fetching/incremental-static-regeneration

**Comment by amankumarrr** [comment]
@wicksipedia @isaaclombardssw @Calinator444 @andrewwaltosssw @scottgallant @JackDevAU 


I have investigated this issue and identified a more effective solution.

**❌ Solution 1 - ISR (Incremental Static Regeneration)**

ISR allows us to update pages that were generated at build time. However, it does not support new routes, as the page must already exist for ISR to fetch and update its data using `generateStaticParams()` on build time. Therefore, this approach does not resolve our issue.

**Drawbacks:**

- Does not support new, undefined routes.
- Only updates pages that were pre-generated during the build.

**✅ Solution 2 - Draft Mode**

Draft Mode can address the problem, but It negatively impacts the performance of both TinaCMS and non-TinaCMS modes, as we observed during the workaround for migrating to App Routing. 

**Drawbacks:**

- Slows down both TinaCMS and non-TinaCMS modes.
- Renders all content on every request, leading to slow load times.
- If left enabled in the user's browser, it can cause persistent performance issues until the user clears their application data.

**✅ Solution 3 - Dynamic Params (Recommended)**

The most effective solution is leveraging Dynamic Params, as tested in [this PR](https://github.com/SSWConsulting/SSW.Website/pull/3642). This approach ensures that existing routes are pre-built at build time, while any new, previously undefined routes are dynamically generated when requested. This resolves our issue while maintaining performance.


**Benefits:**

- Pre-builds existing routes at build time.
- Dynamically generates new routes on demand 
- Easy to implement

**Drawbacks:**
- Increased Server load time for new requests
- Performance Impact on Initial request 

### @wicksipedia Should we proceed with the recommended approach?

**Comment by wicksipedia** [comment]
Go with option 3

It looks like that will still support https://nextjs.org/docs/14/app/api-reference/functions/revalidatePath This will be good for when TinaCloud implements webhooks as we will then be able to invalidate updated urls that changed straight away.

Can we get stats on when routes get revalidated and compare the stats (server cpu load/memory) before/after implementation as well.

Since the manage up lacked some of the important details - here's some deep research on some of the option https://chatgpt.com/share/67c1021d-4634-800d-afc8-f4f77c67a925

**Comment by amankumarrr** [comment]
@wicksipedia @isaaclombardssw @Calinator444 @andrewwaltosssw @scottgallant @JackDevAU @ncn-ssw 

I have enabled dynamic routing for our site, but it seems there is now an issue with TinaCloud. It is unable to fetch records via GraphQL for some reason. However, with the same settings, we can create and edit pages on the PR slots without issues. I suspect the problem lies with TinaCloud, where it fails to insert records for newly created pages into the GraphQL API/database when the branch is protected.

![Image](https://github.com/user-attachments/assets/ce42c588-5eaa-4adf-8986-e91e19b2b43f)
**Figure: A newly created page gives 500 error on the production slot**

**Comment by ncn-ssw** [comment]
@amankumarrr 
There was a branch created with the same name ('test-delete-me') in Sep 2023, which didn't complete its indexing.
As I do not have logs from that time, I do not know why it failed.
I recommend deleting the branch to force TinaCloud to clear the branch from its database and trying again.

**Comment by ncn-ssw** [comment]
@amankumarrr @wicksipedia 
Further investigation has found that the editing interface was querying the 'main' branch of the Project rather than the edited branch.

**Comment by amankumarrr** [comment]
@wicksipedia @ncn-ssw 
After investigation, we found that the issue lies with TinaCMS's CMS switcher functionality. When switching between branches, the GraphQL API continues to call the same API as the parent. For instance, when switching from Branch A to Branch B, the backend Graph API still calls Branch A’s API, causing the issue. @JackDevAU is currently looking into this with the following issue: https://github.com/tinacms/tinacms/issues/5575 

- [ ] Update the Tina package once the PBI has been resolved.

**Comment by amankumarrr** [comment]
❌ this one is blocked until this issue gets resolved - https://github.com/tinacms/tinacms/issues/5575

**Comment by amankumarrr** [comment]
@wicksipedia @ncn-ssw @JackDevAU 

❌This is still blocked

I tested it with the latest version using the provided solution. While the solution works, it relies on cookies, which prevents the pages from being statically generated. As a result, every page is loaded dynamically, causing delays on the client side, which is not ideal for our SEO. Therefore, we cannot use it until we find a better way to handle this.

**Comment by amankumarrr** [comment]
this issue can be resolved with this approach - https://github.com/SSWConsulting/SSW.Website/issues/2643

**Comment by adamcogan** [comment]
Hi @JackDevAU 
1. Can you check if this can be properly fixed in TinaCMS
2. Review this TinaCMS issue that shows a 404 (or 500 if dynamicparam is enabled) for newly created pages on the website
 https://github.com/tinacms/tinacms/issues/5834

Hi @amankumarrr 
1. In the meantime, can you document the work around?

Hi @Calinator444 
1. Implement the work around on SSW Website
2. Compare and confirm it is consistent on SSW Rules 
3. Same for SSW Products

-a

**Comment by Calinator444** [comment]
Hi @adamcogan 

> 1. Implement the work around on SSW Website
> 2. Compare and confirm it is consistent on SSW Rules
> 3. Same for SSW Products

✅ All Done - I have rolled out the work around for yakshaver.ai (i.e. ssw.products) as well as the SSW Website
