### ISSUE TITLE
✨ Events - add EOI form to capture user interest

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#2653]
cc @uly1 @Levijj22 @camillars @sethdaily @landonmaxwell 

For events that we run (but there is no date for the next event) - we need to be able to grab expressions of interest.

**Describe the solution you'd like**

Ideally, on an event page, instead of showing the cities/dates - there would be a form that users can submit and we can get back to them when there is a firm date.

```[tasklist]
### Tasks
- [x] Jotform - Create JotForm to capture details (including url that the form is on - this form should be generic and not just for events)
- [x] CRM - Check with sales/marketing if we want the user details added to CRM/Newsletter
- [x] TinaCMS - Add setting for events to either set dates or have EOI form
```

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/90db135f-581f-44b6-a2d3-3aae9f8a543f)

**Comment by camillars** [comment]
[https://outlook-1.cdn.office.net/assets/reaction/like.png]     Camilla Rosa Silva [SSW] reacted to your message:




[cid:ssw-circle(1)_4c7259a6-23f6-49e5-b933-230ca304562e.png]

Camilla Rosa Silva
SSW Marketing Manager
Stalk: SSW People<https://www.ssw.com.au/people/Camilla-Rosa%20Silva?utm_source=emailsignature>   |   Walk: SSW Sydney<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Talk: +61 426 007 665<https://www.ssw.com.au/ssw/Company/ContactUs.aspx>
[cid:youtube-icon_b8b5cda9-a973-4973-8763-cf3d4922e060.png] <https://www.youtube.com/c/SSWTV>    [cid:linkedin-icon_b153ac9a-eb66-47d9-9c51-ad20b42b8a0a.png]  <https://www.linkedin.com/company/ssw/>    [cid:twitter-icon_16ddd2de-0a0c-4b56-9986-6c5968e517d2.png]  <https://twitter.com/SSW_TV>    [cid:teams-icon_552803c2-9c44-4267-b563-7fe1a7a0e589.png] ***@***.***>


        Level up your AI game at the SSW AI 2-day Workshop<https://www.ssw.com.au/events/ai-workshop?utm_source=emailsignature>

________________________________
From: Matt Wicks [SSW] ***@***.***>
Sent: Monday, May 20, 2024 1:00:33 AM
To: SSWConsulting/SSW.Website ***@***.***>
Cc: Camilla Rosa Silva [SSW] ***@***.***>; Mention ***@***.***>
Subject: [SSWConsulting/SSW.Website] ✨ Events - add EOI form to capture user interest (Issue #2653)


cc @uly1<https://github.com/uly1> @Levijj22<https://github.com/Levijj22> @camillars<https://github.com/camillars> @sethdaily<https://github.com/sethdaily> @landonmaxwell<https://github.com/landonmaxwell>

For events that we run (but there is no date for the next event) - we need to be able to grab expressions of interest.

Describe the solution you'd like

Ideally, on an event page, instead of showing the cities/dates - there would be a form that users can submit and we can get back to them when there is a firm date.

### Tasks
- [ ] Jotform - Create JotForm to capture details (including url that the form is on - this form should be generic and not just for events)
- [ ] CRM - Check with sales/marketing if we want the user details added to CRM/Newsletter
- [ ] TinaCMS - Add setting for events to either set dates or have EOI form


CleanShot.2024-05-20.at.10.53.56.png (view on web)<https://github.com/SSWConsulting/SSW.Website/assets/600044/90db135f-581f-44b6-a2d3-3aae9f8a543f>

**Comment by Calinator444** [comment]
@wicksipedia 

CC: @bradystroud @amankumarrr @andrewwaltosssw 

⛔ **Blocked**: We can't work in this until we discuss purchasing more licenses with someone from the JOTform team. I can book a meeting with someone from the sales tomorrow team to discuss pricing. Or even today at 3:45 if we don't need Matt.

**Comment by Calinator444** [comment]
As per my conversation with @sethdaily  and @camillars, all submissions will be added to our contacts list. The registrations of interest themselves will be viewed using the JotForms submissions.

**Comment by Calinator444** [comment]
@camillars @sethdaily 

As per my conversation with @wicksipedia the registration of interest form will add new contacts but won't update old ones (i.e. if Jon Doe and Jane Doe both register with doecorp@example.com only the first registration will be added as a contact). 

New registrations of interest for events will still be captured in JotForms regardless of which whether the user is added to our contact list or not.

**Comment by Calinator444** [comment]
Need to check with @zl24622 that this flow will work as expected when it hits prod

**Comment by Calinator444** [comment]
Couldn't get this approved. Had a build error at the last minute it's fixed but will need a re-review.

Other than that this should work.

**Comment by Calinator444** [comment]
@wicksipedia 

Sorry, forgot to update this. The pr for this has been merged and the power automate flow for adding the contacys to CRM when the form is submitted is in prod.


Here's how the form looks


![ROI button Tina](https://github.com/SSWConsulting/SSW.Website/assets/65635198/cde2dc84-aefe-4304-a4d3-14ce5faf1205)
**Figure**: **Registration of Interest button being edited in Tina**


![Registration of Interest Form](https://github.com/SSWConsulting/SSW.Website/assets/65635198/240f7d21-ca99-4c1c-898a-90430a2f9ea6)
**Figure**: **Registration of interest form**



![image](https://github.com/SSWConsulting/SSW.Website/assets/65635198/1c87bd54-bbd8-4125-a542-811669ae52e8)
**Figure**: **Registration of interest form in Tina**

**Comment by Calinator444** [comment]
@wicksipedia 

As per the feedback from the last sprint review I've created a done video for this

(2:04)

https://youtu.be/eom5FhSH0bc

**Comment by wicksipedia** [comment]
Test pass with changes:

1. 0:21 - have TinaCMS pre-loaded to avoid dead air
2. 0:40 - looks like there is a 'Book Now' button for the old event - I assume this should be changed to TBA
3. 0:48 - change component name to `Expression of interest form` and add a preview image of the modal
4. 1:18 - capturing the page that they are on - show a filled in form in JotForm so we can see the result with the URL of the page
5. Outro - remember to sign off with "This is Caleb from SSW, thanks for watching"
