### ISSUE TITLE
Migrate Standards internal

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#2660]
#### Description

Some of the Standards Internal pages were concealed behind an auth guard and did not get ported. As per my conversation with @adamcogan these pages still need to be ported.

```[tasklist]
### Todo
- [x] Host the v1 website locally
- [x] Disable the auth guard
- [x] Use the migration script to port all of the Standards Internal pages that haven't been touched
- [x] Fix any broken links on the Standards Internal pages after porting them
```

**Comment by Calinator444** [comment]
I just want to give @fenix2222 a shout-out for managing to run the v1 repo locally so that we could port these pages. You honestly saved my gravy man.

**Comment by Calinator444** [comment]
The following new routes have been added 


archive/standards-internal/computer-setup
archive/standards-internal/developer-general
archive/standards-internal/developer-network-phone
archive/standards-internal/developer-products-hosting
archive/standards-internal/developer-sql-server
archive/standards-internal/employment
archive/standards-internal/general-administration

**Comment by Calinator444** [comment]
I've got a done video for this but it hasn't been test passed

https://www.youtube.com/watch?v=uLTHt9ATkao
