### ISSUE TITLE
🚶 Events - migrate SharePoint list data to Tina

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#2694]
Currently the Events are sourced from a SharePoint list - this isn't ideal since:

- we need to query an external source
- it makes it harder to create a new event
  first add an image to the website, then add data to a list
  if you do it too quickly, it can cause tests to fail on deployment due to broken images
- this will help perf stats as next will be able to optimise them

```[tasklist]
### Tasks
- [x] Create `event` collection
- [x] Write script to export SharePoint event list and presenter data
- [x] Standardise event thumbnail location (in schema)
- [x] Reference TinaCMS event data for events and Live UG
- [x] Remove unused environment variables from build
- [x] Update marketing standard (give Camilla a video)
```

**Comment by Calinator444** [comment]
@wicksipedia 

There's a bug in the staging slot. The initial list of events isn't being pulled using Static Site Generation, causing performance to take a nose dive. This needs to be fixed before we finish this.

**Comment by Calinator444** [comment]
I have created a video describing the new editing workflow. Currently waiting for approval from Seth.

https://www.youtube.com/watch?v=F42rMIpvAZM

**Comment by Calinator444** [comment]
@wicksipedia I got a text pass from @sethdaily on the how to video for adding events in Tina. 

However I haven't updated the readme to explaining how to do this yet.

Seth has already updated the standard for adding events.


How to video for adding events in Tina:

https://youtu.be/bhrzB2xGxb8

**Comment by Calinator444** [comment]
@wicksipedia I still need to 

As per the feedback from the sprint review I've created a v2 done video for this. Test @PennyWalker .

(2:24) https://youtu.be/bhrzB2xGxb8

I've also updated the wiki. 

https://github.com/SSWConsulting/SSW.Website/wiki/Editing-the-website#adding-new-events

**Comment by Calinator444** [comment]
The video I mentioned above was test passed by @PennyWalker
