### ISSUE TITLE
☁️ Cloudflare - Add Redirects for /archive routes

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2699]
**Description:**
We need to add redirects for all /archive from v1 to our new routes on Azure storage containers.

```[tasklist]
### Tasks
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/2714
- [x] Add /archive redirects
- [x] Add redirects for /newsletters content from v1
- [x] Add redirects for /ssw
- [x] Add same routing on ssw.com.au
```

**Comment by andrewwaltosssw** [comment]
For newsletter asset redirects please see link at https://github.com/SSWConsulting/SSW.Website/issues/2617#issuecomment-2136275918

**Comment by amankumarrr** [comment]
@wicksipedia @SSWConsulting/ssw-website-maintainers 

**Redirects Status for tfs365.com (Staging site) Domain:**

All redirects (total of 1,026) have been tested and added successfully for the following routes:

  ✅ legacy-redirects
  ✅ case-studies
  ✅ consulting
  ✅ events
  ✅ static
  ✅ archive
  ✅ Website-redirects
  ✅ Newsletters content

**Remaining Redirects to be Implemented:**

For the following domains, redirects are still pending:

❌ dory-redirects.json: Redirects for the `sswdory.com` domain are yet to be set up.
❌ prod-dotcom-redirects.json: Redirects for the `ssw.com` domain are not yet implemented.
❌ staging-dotcom-redirects.json: Redirects for the `staging.ssw.com` domain are pending.

Here is the repo - https://github.com/SSWConsulting/SSW.Cloudflare

Download this to view the result - https://github.com/SSWConsulting/SSW.Cloudflare/blob/main/test-scripts/url_redirect_report.html

**Comment by amankumarrr** [comment]
@wicksipedia @chrisschultzssw @bradystroud @andrewwaltosssw @Calinator444 

As we are unblocked now to move forward with this task, we need to add worker routes for `ssw.com.au` in order to soft-turn off the VM.

Note: If we implement the route, our website v1, will not be accessible at all from `/ssw`.

Tasks:

- [ ] Update the App Insights instrumentation key to Prod (it's currently pointing to DEV).
- [ ] Update the 404 page, which currently just says "page not found."

**Comment by Calinator444** [comment]
@amankumarrr I ran the URL redirect status report and I noticed a number of the redirects for `/archive` were returning 403s or 421s (806 pages affected)

Is this expected behaviour?

![Image](https://github.com/SSWConsulting/SSW.Website/assets/65635198/814312cb-8df4-4fd2-aacb-90b0cff1be97)
**Figure**: **400 level responses for archive pages**

**Comment by Calinator444** [comment]
Nevermind, just tried rerunning the build and deploy workflow https://github.com/SSWConsulting/SSW.Cloudflare/actions/workflows/main.yml

**Comment by amankumarrr** [comment]
In the past 24 hours, these are stats for Cloudflare on route `/ssw/*`

![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/0f42cad4-b901-4d32-91d4-df5bb4a45d19)

**Figure: Stats from Cloudflare**

**Comment by amankumarrr** [comment]
@wicksipedia @jeoffreyfischer 

We can add redirects logs in App Insight.

![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/f2855fec-e6a7-4aee-960b-18800493e28f)

**Figure: Logs in App Insight for redirects from worker**

**Comment by amankumarrr** [comment]
@jeoffreyfischer 

Hey @wicksipedia ,

Could you please review the plan for implementing redirects through the Worker?

In the attached screenshot:

- Black lines represent the current flow.
- Red lines indicate changes planned for Phase 1.
- Purple lines show updates for Phase 2.

![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/37eafcda-e6e5-4301-b246-8f5fbb251c4d)

**Figure: Plan for the redirects and moving away from Front Door**

**Comment by jeoffreyfischer** [comment]
As per my conversation with @wicksipedia, I will improve the drawings and discuss the plan with him and @amankumarrr on Friday.

**Comment by jeoffreyfischer** [comment]
As per our conversation with @wicksipedia and @amankumarrr, the Cloudflare migration will be performed in 2 steps:
- Step 1: Redirects are stored in Workers and actioned by Front Door (see figure)
- Step 2: Redirect are stored and managed in Workers (see figure)

Before pushing Step 1 to Prod, @amankumarrr will update the README and make a Done Video about how to use Cloudflare. This is to ensure that anyone can use it.


About Step 2, @amankumarrr and @jeoffreyfischer will investigate several FREE options and then discuss with @wicksipedia  about which one we will go with.

**Screenshots**

![Image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/90317c6d-004b-474d-be76-d53dddd0fb33)
**Figure: Step 0 - Current workflow** 

![Image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/e94a8d48-f50e-4660-ab4f-17c72ef45d96)
**Figure: Step 1 - Transition workflow** 

![Image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/b96e168f-abbe-4d1c-aa59-3548ef064937)
**Figure: Step 2 - Final workflow**

**Comment by jeoffreyfischer** [comment]
As per my conversation with @wicksipedia and @amankumarrr, I have investigated some CDN options:

## CloudFlare Workers (Recommended)
#### Link to doc
https://developers.cloudflare.com/workers/platform/limits/
#### Price
FREE (paid options available)
#### Tech details
- Number of env variables: 50 per Worker
- Worker size: 1 MB
- Request body limit: 100 MB
- Number of requests per Worker: 100,000 per day - 1,000 per min
- Worker memory: 128 MB
- Calls (get(), put(), etc.) per request: 50
- Number of routed zones per Worker: 1,000
- Log size: 128 kB

## Google Cloud CDN
#### Link to doc
https://cloud.google.com/cdn/pricing
#### Price
Pay by usage
- Cache data transfer out: $0.10 per GiB
- Cache fill: $0.02 per GiB
- HTTP/HTTPS cache lookup requests: $0.0075 per 10,000 requests
#### Tech details
Not Found

## Fastly
#### Link to doc
https://www.fastly.com/pricing/
#### Price
Lowest Tier: 1500$/month
#### Tech details
- Number of requests: 100,000 per month
- Number of TLS domains: 20

**Comment by jeoffreyfischer** [comment]
Below are the total **monthly hits** in June 2024 on:
- **SSW Website: 9,541,592**
- .../rules: 2,239,154
- .../people: 374,925
- .../archive: 42,018

**Screenshot**
![Image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/39b1ca5a-95a3-4f2c-872d-975bfb34f7ba)
**Figure: Monthly hits count on SSW Website, rules, people and archive**

**Comment by jeoffreyfischer** [comment]
### Summary
As per my conversation with @wicksipedia , I have investigated the limits for a **$5/month** plan with **CloudFlare**.
✅ All lights are green.
⚠️ The only slight warning is about the **Routes** (see below).

### Requests
- Number: 10 million included per month + $0.30 per additional million
Note: In June 2024, **SSW Website** had **9.5 million** requests (see previous comment)
- Number of calls per request: 1000

| Requests  | Price            | Likelihood on SSW Website |
|------------|--------------|--------------------------------|
| 10 million | $5/month   | High                                      |
| 20 million | $8/month   | Medium                                |
| 50 million | $17/month | Low                                       |

**Table: Projection (if we ever exceed the 10 million requests cap)**

### Workers
- Number: 500
- Size: 100 MB

### Routes
- Number of routes per zone: 1000
ℹ️ Note: a "zone" refers to a specific domain or subdomain that has been added to our Cloudflare account for management.
⚠️ Warning: This can be an issue given ssw.rules has around 3500 rules. 
✅ Solution: We can separate ssw.rules into several workers.


### Environment variables
- Number: 128/Worker
- Size: 5 KB

### Useful links
- Link to Pricing doc: https://developers.cloudflare.com/workers/platform/pricing
- Link to Limits doc: https://developers.cloudflare.com/workers/platform/limits

**Comment by Calinator444** [comment]
@wicksipedia 

We exceeded the request limit when the Cloudflare worker went live on production.

Had a look through the pricing doc. If we were to switch to the standard pricing plan our limit would increase to 10 million requests per month (or approximately 333,0000 requests per day over the previous 100,000)

I've included the pricing model below


![Image](https://github.com/user-attachments/assets/aca600ca-c122-47be-a8db-ee257a6fe71e)

**Comment by jeoffreyfischer** [comment]
In the previous comment, I've pointed out that the current number of requests on SSW Website is about **9.5 millions/month**.
So I recommend going for the **8$/month plan** to allow for a maximum requests number of **20 million/month**.

![Image](https://github.com/user-attachments/assets/c52ffabe-b767-4ba0-b192-66fb7a156384)
**Figure: SSW Monthly requests + Cloudflare pricing plan (copied from previous comment)**

**Comment by Calinator444** [comment]
We can't push this into prod until the purchase please gets approved. 

See email - Purchase Please - Request for Cloudflare workers standard (⚠️ High priority)

**Comment by Calinator444** [comment]
@wicksipedia 

The purchase please has been approved and the Cloudflare worker is now in production. (You can test the redirects at ssw.com.au/archive in the left hand side)

@chrisschultzssw said he was going to add a billing alerts just in case we exceed the estimate of $146.45 per year.

I also added a staging workflow for testing redirects before pushing to prod. The done video for that is below (same as the done video I did in the PBI this week)

https://youtu.be/wdZql8oAawA

**Comment by chrisschultzssw** [comment]
> @chrisschultzssw said he was going to add a billing alerts just in case we exceed the estimate of $146.45 per year.

Done.

![Image](https://github.com/user-attachments/assets/a3882161-eb96-4708-b11d-a46378dd81ff)
