### ISSUE TITLE
📄 Footer - add TinaCMS

### ISSUE THREAD

**Issue by sethdaily** [SSWConsulting/SSW.Website#2711]
cc: @adamcogan @bettybondoc @tiagov8 @wicksipedia @anastasiacogan @camillars @PennyWalker 
As per email subject: RE: SSW - Powered by TinaCMS 🦙

URL: N/A - footer

**From:**

BUILT ON THE MICROSOFT AZURE PLATFORM

**To:**

(see image for design)
[BUILT ON MICROSOFT AZURE](https://www.ssw.com.au/consulting/azure) | [POWERED BY TINACMS](https://tina.io)

**Tasks**

```[tasklist]
### Tasks
- [ ] Make the change
- [ ] Ping Seth with the task 'send a 1-month FollowUpThen to reply to the email: RE: SSW - Powered by TinaCMS 🦙'
```

download tina logo https://tina.io/press/

**Screenshots**

![Image](https://github.com/SSWConsulting/SSW.Website/assets/130118701/df57c935-0b2e-4e6e-8d91-5595bf36849d)
**Figure: use this design - checked by Betty and Tiago**

**Comment by sethdaily** [comment]
@wicksipedia consider pulling this into the next Sprint - easy win for Tina

**Comment by tiagov8** [comment]
Hi @wicksipedia ,
 
Looks good, but I think we should make the llama logo the very same height as the Azure one (30px).
 
Right now they have the same width (30px) but height is 41px 

- [ ] 1. Please action

![Image](https://github.com/SSWConsulting/SSW.Website/assets/12601228/74304f9f-fbf0-4bdb-8080-f0fb7f8aff98)

Cheers,

**Comment by tiagov8** [comment]
Hi Matt, 

as per my message on Teams... the feature in this Issue is not currently showing

- [ ] 1. Can you implement it back?

Also, to make SSW.Website consistent with Rules and People...

- [ ] 2. Add after the logos, the sentence "**We ❤️ open source. Loving SSW Website? [Star us on GitHub.](https://github.com/SSWConsulting/SSW.Website)**" + the Star count

E.g.:

<img width="585" alt="Image" src="https://github.com/user-attachments/assets/121a1c86-8059-4800-bc28-b6c9c706d8b7" />

**Comment by wicksipedia** [comment]
closing since this was done in a previous Sprint
new requests are in a new issue
