### ISSUE TITLE
✨ Add "Stay in Touch" for SSW Newsletter subscription to the SSW Homepage

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#2712]
@Tanya-Leahy @leahy268 @bettybondoc @joshbermanssw @PennyWalker 

### Is your feature request related to a problem? Please describe
As per @adamcogan 's **Re: SugarLearning - SSW Newsletters - Know our external content**:

> The “Subscribe here for the SSW Newsletter” should not have a deep link, it should be to the home page (and then they find it intuitively like a normal user)

Users currently don't have a way to sign up for the newsletter from the homepage. They need to go to https://ssw.com.au/newsletters

---

## Tasks

- [ ] 1. Create a solution (see below)
- [ ] 2. Get approved by @adamcogan 
- [ ] 3. Implement
- [ ] 4. Update the link on https://my.sugarlearning.com/SSW/items/14765/ssw-newsletters-know-our-external-content to point to the homepage

---

### Describe the solution proposed

@adamcogan seems happy with something similar to [TinaCMS](https://tina.io/): 

![Image](https://github.com/SSWConsulting/SSW.Website/assets/12601228/190d68e1-7d50-4add-acb1-3c1889553e4c)

---

### Describe alternatives you've considered

I think having it at the very top adds extra complexity to the website   

I would recommend adding it above OR below this section... keeping the very same styling and elements from the [Newsletter page]( https://ssw.com.au/newsletters):

![Image](https://github.com/SSWConsulting/SSW.Website/assets/12601228/196f2cc1-ec01-4bcd-a493-2f8381e517ca)

---

### Additional context

- During the previous days before a UG, we already get another top section... (If everything is important - to be at the top - then nothing is important)

   ![Image](https://github.com/SSWConsulting/SSW.Website/assets/12601228/ebd4684e-511c-4a65-b2e3-e99de638accf)

- Currently SSW Newsletter's subscribtion also asks for name and surname...while Tina asks just for email. That's 3 fields vs 1.
