### ISSUE TITLE
Pages - Consulting - Remaining pages

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#273]
Remaining pages to be converted to markdown:

(skipping terms and conditions as it is a special case dealt with in a different issue)

```[tasklist]
### Tasks
- [x] Document remaining consulting pages
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/296
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/301
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/300
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/299
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/298
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/297
```
