### ISSUE TITLE
✨ New SSW Articles - Create page template and index

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#2763]
cc @uly1 @andrewwaltosssw @samsmithssw @amankumarrr @wicksipedia @camillars 

As per @miichaelsmedley 's **Re: Improve our SEO for .net 8 migrations**

We want to have a new "SSW Articles" page under https://ssw.com.au/articles 

> This will be a series of SEO friendly articles that answer questions or provide insightful opinions that will be engaging to decision makers designed to answer questions being asked earlier in the decision cycle whilst the person is researching their solutions.

### Tasks 

- [x] 1. Create a new page template for Articles, based on this mockup: https://www.figma.com/design/oLCYGpRBbkzASrChz4k88D/SSW-Website---Articles?node-id=1-2&t=qHd7Zot9xYlzxc2s-0
   **Note:** Every content element (headers, lists, etc) should follow the standard used on other pages (E.g. [About SSW](https://www.ssw.com.au/company/about-us))

- [x] 2. Create an index to navigate through those pages as per the mockup in the same file

- [x] 3. Create a sidebar element to promote microservices (using mockup details as example). We should be able to create more of those and add to different pages.

- [x] 4. Use [this article example on Loop](https://sswcom.sharepoint.com/:fl:/g/contentstorage/CSP_6740aeb4-c61a-4502-af8e-572569ca2e93/EZqvSbVoSg9FtW2tKpM_LVUBnzicqjgZLLJzvrtuXMdksw?e=5f22gR&nav=cz0lMkZjb250ZW50c3RvcmFnZSUyRkNTUF82NzQwYWViNC1jNjFhLTQ1MDItYWY4ZS01NzI1NjljYTJlOTMmZD1iJTIxdEs1QVp4ckdBa1d2amxjbGFjb3VrNU5aU3o2T0YzMU9sc05KZi1wUUh4blFZc0JSZlNtMVFJVXdUOXl2UkdOaSZmPTAxQ040VlVGNDJWNUUzSzJDS0I1QzNLM05ORktKVDZMS1YmYz0lMkYmYT1Mb29wQXBwJnA9JTQwZmx1aWR4JTJGbG9vcC1wYWdlLWNvbnRhaW5lciZ4PSU3QiUyMnclMjIlM0ElMjJUMFJUVUh4emMzZGpiMjB1YzJoaGNtVndiMmx1ZEM1amIyMThZaUYwU3pWQlduaHlSMEZyVjNacWJHTnNZV052ZFdzMVRscFRlalpQUmpNeFQyeHpUa3BtTFhCUlNIaHVVVmx6UWxKbVUyMHhVVWxWZDFRNWVYWlNSMDVwZkRBeFEwNDBWbFZHTkZST1VVbEtUbFZJU1UxQ1IwdEpRVk5PTTFKTVVFdFhXbG8lM0QlMjIlMkMlMjJpJTIyJTNBJTIyNWZiMzU2MWItOWQxOS00N2RjLTkxMzgtYjg1ZjNmMmVmZTBkJTIyJTdE) for the 1st article. 
   **Note:** Please get access permissions from @miichaelsmedley 

- [x] 5. Get a test pass from Mike + Uly

- [x] 6. Tell Mike to create some new articles

- [x] 7. Add the new page "Articles" to **Main menu | About Us | Our Blogs**

---

**Note:** Any conceptual concerns should be clarified with @miichaelsmedley. Any design questions, please ask @tiagov8 

---

![Image](https://github.com/SSWConsulting/SSW.Website/assets/12601228/0ba5478f-9cbc-4f68-92a0-c82f111763c6)

**Comment by Calinator444** [comment]
@tiagov8 

I think you have these page templates labelled the wrong way around



![Image](https://github.com/SSWConsulting/SSW.Website/assets/65635198/e98dbd1f-0983-4ca7-9264-5a6c208ba083)

**Comment by Calinator444** [comment]
Link to the mockup templates 

https://www.figma.com/design/oLCYGpRBbkzASrChz4k88D/SSW-Website---Articles?node-id=0-1&t=qHd7Zot9xYlzxc2s-1

**Comment by tiagov8** [comment]
> I think you have these page templates labelled the wrong way around

You're right.
I already fixed in Figma, but since it's not crucial I won't update here

**Comment by wicksipedia** [comment]
Note: this should be done with the new app router implementation so we avoid more page router debt

**Comment by wicksipedia** [comment]
@Calinator444 - you may need to take this over to clean up linting issues

pls check that the index page implementation is the same as the event index page. @Harry-Ross worked hard on that one to use react query

**Comment by Calinator444** [comment]
@wicksipedia 

I added a "Load More" button while I was adding the prefetch for articles to the index page (which is working btw). I figured the number of articles will grow quite quickly.

**Note**: To show off the effect I had it prefetch 1 article and load 1. This is obviously bad UX and I'm planning to prefetch and then load 10 events at a time.

![Image](https://github.com/user-attachments/assets/4b514f0e-f623-4d44-89c7-6e9cf3615cf7)

**Comment by Calinator444** [comment]
I've tested this, got a done video here https://youtu.be/CUzjmOlmAik

I did see a broken link for Calumn's profile picture while adding a test article and just need to verify that this won't break in staging.

**Comment by Calinator444** [comment]
@wicksipedia 

Merged, but Micheal Smeadly requested some changes

**Comment by Calinator444** [comment]
I've captured the feedback that Michael left here:


**Article template changes:**
- Add a date of publication for articles
- Add add a call to action at bottom
- remove padding for sidebar on smaller screens
- Remove the padding for the sidebar on smaller screens
- improve notes for video embed (Overflow prop? what does that mean)



Tina Feedback
- Not sure how to create new branches when creating articles
- Doesn't fix headings when copying and pasting
- Can't create new branches when on a feature branch in Tina
- It's confusing losing the article when you go to edit the author field
