### ISSUE TITLE
Events - add endpoint to return upcoming events

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#2785]
Discovered whilst migrating SSW.People to blob storage - this will block switching off the VM

There is a call to the v1 website that returns upcoming events - https://github.com/SSWConsulting/SSW.People/blob/f81d9de4965d0fd3622b4befdad302aa2e1a2237/src/helpers/eventHelper.js#L4

We need a similar endpoint on v3

### Tasks
- [x] Create an API endpoint that can query the most recent events
- [x] add the route `api/events/upcoming/:presenter` for getting upcoming events by presenter
- [x] add the route `api/events/past/:presenter` for getting past events by presenter

### Acceptance criteria
- [x] Endpoints are implemented using the app router

**Comment by Calinator444** [comment]
I needed to add a new filtering because there was a call on the home page that returns the first 50 events.

**Comment by Calinator444** [comment]
CC: @wicksipedia 

**Note**

As discussed with @bradystroud  I've replaced the `Url.Description` property that was returned by the old API with the title of the event because it wasn't ported. The prop was originally used as alt text on SSW People but wasn't ported during the Tina SharePoint migration.
