### ISSUE TITLE
✨ Newsletters

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#282]
Replace functionality on <https://www.ssw.com.au/ssw/NETUG/SSWUpdatePrevious.aspx>

Page that generates the list: https://dev.azure.com/ssw2/SSW.Website/_versionControl?path=%24/SSW.Website/trunk/SSW.Website.WebUI/NETUG/SSWUpdatePrevious.aspx

List of previous emails: https://dev.azure.com/ssw2/SSW.Website/_versionControl?path=%24/SSW.Website/trunk/SSW.Website.WebUI/NETUG/SSWUpdate

New URL: `/newsletter`

```[tasklist]
### Tasks
- [x] New collection for newsletter
- [x] `/newsletter` lists previous newsletters
- [x] `/newsletter` has component to sign up to the newsletter
- [x] component is able to be used on other Tina pages
- [x] migrate past newsletters
```

**Comment by johnxu16** [comment]
About past newsletters migration:

1. Some past newsletters are rendered with .cs template files and even include some internal links, so we need to crawl some websites for getting what exactly they look like if we want to fully get rid of Website V1.

**Comment by PothieuG** [comment]
**As per my conversation with @bradystroud, here are the different stages of my development:**

- Modification of `subNewLettersButton.tsx`:
	- Creation of the subscription form:
		- 2 inputs: name and email
		- registration button
	- Visual indicator of registration ("Subribing..." message)
	- Error management with error message in the frontend
	- Fixing dynamic CRM messages that were not working
- Creation of `add-contact-to-newsletters.ts` with Next.js API to handle the call to the backend
- Creation of the Power Automate flow in the development environment that will save the information sent by the frontend to the "Contact" table in the Marketing List "Newsletters" in Dynamics
- Rework of components displaying the newsletter table:
	- Removal of existing components `newsTable.tsx` and `sswTable.tsx` and `table` folder as well
	- Creation of a `newslettersTable.tsx` component:
		- Refactoring of the two previous components
		- Management of newsletter display via Tina CMS .json files (more details below)
		- Error and loading management
		- Creation of a link with TinaCMS to modify the title
- Management of newsletters via TinaCMS:
	- Removal of the API call (`get-newsletters.ts`) that fetched the list of newsletters from the old repository
	- Creation of a .json file for each year of newsletters with information such as description, year, URL, and month for each of them
		- All values are strings, except for the year and month, which are numbers, making sorting for display easier
	- Creation of a `newsletters` folder at `/content/newsletters`subfolders by year containing the .json files reflecting each year
	- Creation of a `newsletters` folder at `/public/newsletters` with subfolders by year containing all newsletters (.html and .htm)
	- Creation of the `newsletters` collection at `/.tina/collections/newsletters`that will link with TinaCMS
	- Creation of a services (`utils.service.ts` and `date.service.ts`) at `/service` and method for importing multiple .json files into a component to process and create the newsletter table efficiently and easily
- To address the comment above from JohnXu:
	- As we no longer want any newsletter links pointing to the old repository, I modified all image links in all newsletters (phew) to point to the public folder of the new application
	- I modified the header metadata links (scripts, CSS files...) to point to an `oldNewslettersHeaders` folder that i have create at `/helpers`, where I imported the necessary scripts and files. I'm not sure if I placed it in the right place
		- I updated the broken imports and links of these files
	- Unsure about this, on a separate branch, I imported all images required to fully generate all newsletters since 2000. The image folder size increased from 30MB to 370MB...
- Lastly, I reviewed all newsletters and fixed those that were not functional.

**Here are the remaining questions, reflections, and todos:**
- In the Power Automate flow, we must set a value for the "rating" field to save a contact. According to Callum, this field is probably not mandatory in production, but I have no way of knowing, as I don't have access to the production environment
- I still need to have my flow reviewed by Callum when we can meet
- Add the URL of the Power Automate flow's call to an environment variable.
- I corrected the image links in newsletters to ensure the visual identity of the document, but what should we do about links pointing to .cs files in the old repository (as John pointed out)?
- To create my .json file import method, I had to use the `context` method of `NodeRequire`. TypeScript didn't let me use this method for webpack configuration reasons. As I didn't want to modify the webpack configuration file, I created `webpack-require-context.d.ts` file at the project root, allowing me to use the `context` method. I wanted to know if there was a better solution, or if someone could guide me in modifying the webpack configuration?
- I placed the scripts and other metadata files of the old newsletters headers in the `helpers` folder, but I'm not convinced about it.
- I still need to write documentation for Penny, explaining how to add a newsletter to the site. In short:
	- Add the .html file to the year folder in `/public/newsletters/year`
	- Go to `TinaCMS | Newsletters | the correct .json file corresponding to the year`, and add a new entry with the description, URL (the name of the HTML file), and the number corresponding to the month


**Following where the newsletters are located and the structure of the .json files, followed by the TinaCMS section for simplified editing:**



![Image](https://user-images.githubusercontent.com/45673557/234248524-146cee5d-d1ca-4aa4-a014-dd48bd3d1d77.png)
  

![Image](https://user-images.githubusercontent.com/45673557/234248662-b2bad4ff-af4f-4b22-9b91-66fdda948a1d.png)  
  

![Image](https://user-images.githubusercontent.com/45673557/234248799-785d94a5-0843-4b8c-9181-b5e27e2b926a.png)
  
  
![Image](https://user-images.githubusercontent.com/45673557/234248841-9cbe5ee4-b1d8-4e4c-b817-6f3d2c730c7d.png)


![Image](https://user-images.githubusercontent.com/45673557/234249081-d654135b-18d3-4a35-a954-5231e33d9570.png)

**Comment by PothieuG** [comment]
Update:
In terms of development, the branch is ready to be merged after review; however, there are still some blocking points:

- after talking with @bradystroud  and @amankumarrr , in order to store the Power Automate flow URL (which allows saving a contact in the CRM) in the key vault, we must first wait for Aman's developments to be completed (https://github.com/SSWConsulting/SSW.Website-v3/issues/502)
- The flow is ready to be deployed in production, but we must wait for Lu's availability to do so. We will get in touch on Tuesday, 9/5.  

Regarding document upload in TinaCMS:

- uploading a file via Media Manager does not allow targeting subfolders. There is already an issue on the TinaCMS repo: https://github.com/tinacms/tinacms/issues/3813
- on a separate branch, I have started developments to implement file uploading in a custom component. The developments on this branch are almost finished.  

In the future:

- there are a lot of URL redirections in the newsletters (for example: https://www.ssw.com.au/ssw/Consulting/Power-Platform.aspx), which will need to be updated as pages are migrated.

To finish :
- @bradystroud  suggested doing a demonstration for Penny and recording the Teams video call so that it can be kept as documentation. In any case, written documentation will need to be created once all developments have been validated.
