### ISSUE TITLE
💸 Presenter has needlessly nested props

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#2839]
@jeoffreyfischer @wicksipedia 

**Description**  
The `presenter` collection in tina has a nested `presenter` attribute that contains props that should be part of the main collection. This makes the collection confusing to work with because the presenter's name would be accessed from `presenter.presenter.name`

**Proposed solution**  

```[tasklist]
### Todo
- [ ] Update the collection so that `name` and `presenterProfileURL` are both part of the presenter collection
- [ ] Remove the `presenter` attribute from the `presenter` collection
- [ ] Update all of the existing presenters in tina to use this new schema]
- [ ] Update seeding on people repo to put presenter attributes in the correct place (see issue https://github.com/SSWConsulting/SSW.Website/pull/2916)
```

**Screenshot**

![Image](https://github.com/user-attachments/assets/03802f97-3330-43a5-81dc-9a5d5ebeb781)
