### ISSUE TITLE
Consulting - Terms and Conditions

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#285]
Migrate <https://www.ssw.com.au/ssw/Consulting/Terms-and-Conditions/>

Same URL `consulting/terms-and-conditions`

```[tasklist]
### Tasks
- [ ] Consulting schema - Add a layout picker for consulting pages
- [ ] Existing consulting pages use existing layout
- [x] T&C page uses layout similar to existing website
- [x] Add T&C content
- [x] T&C content needs a CODEOWNER
```
