### ISSUE TITLE
📈Investigate failed requests /files/sdk.m

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#2851]
@wicksipedia 

### Description

There are a large number of failed request being sent to `/files/sdk.min.js` on the site right now. Were unaware of this path existing on the main site.

### Todo 

```[tasklist]
- [ ] Investigate whether `/files` points to anything on the live site
- [ ] Investigate whether `/files` appears on the sitemap
- [ ] Fix the issue 
```

### Screenshot
![Image](https://github.com/user-attachments/assets/36b93df9-bf3a-4a83-95ba-98cdd4a60bdb)

**Comment by Calinator444** [comment]
Tip: try to find sdk.min.js on semrush
