### ISSUE TITLE
🐛 Cloning repo - Fix duplicate files with different casing

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2853]
**Describe the bug**
When cloning the Website repo on a local machine, a list of unstaged files appears

**To Reproduce**
1. Go to [github.com/SSWConsulting/SSW.Website](https://github.com/SSWConsulting/SSW.Website)
2. Clone the repo to your local machine
3. Open the repo and observe the unstaged files

**List of unstaged files**
- C:\Repos\SSW\SSW.Website\public\images\company-logos\AIHackday_BW_preview.png
- C:\Repos\SSW\SSW.Website\public\images\company-logos\AngularHackday_BW_preview.png
- C:\Repos\SSW\SSW.Website\public\images\company-logos\MAUIHackday_BW_preview.png
- C:\Repos\SSW\SSW.Website\public\images\company-logos\ssw-logo-preview.png
- C:\Repos\SSW\SSW.Website\public\images\partners\logo-control4.jpg
- C:\Repos\SSW\SSW.Website\public\images\partners\logo-identityserver.jpg
- C:\Repos\SSW\SSW.Website\public\images\partners\logo-microsoft.jpg
- C:\Repos\SSW\SSW.Website\public\images\partners\logo-octopus.jpg
- C:\Repos\SSW\SSW.Website\public\images\partners\logo-zendesk.jpg

**Tip**
This seems to be due to duplicate files with different casing:
- "AIHack**d**ay_BW_preview" vs "AIHack**D**ay_BW_preview"
- "AngularHack**d**ay_BW_preview" vs "AngularHack**D**ay_BW_preview"
- "MAUIHack**d**ay_BW_preview" vs "MAUIHack**D**ay_BW_preview"
- "**ssw**-logo-preview" vs "**SSW**-logo-preview"
- "**P**artners" vs "**p**artners" folders

**Expected behavior**
The list of unstaged files should be empty

**Tasks**
- [x] figure out which duplicate files and/or folders can be removed safely
- [x] if duplicates are being called separately, edit the call so that only the same one is being called
- [x] remove the duplicates

**Screenshots/Video**
![Image](https://github.com/user-attachments/assets/f8e6b939-1072-4075-b8e6-9a3da032f89d)
**Figure: List of unstaged files that appear after the Website repo has been cloned**

**Comment by bradystroud** [comment]
## ✅ Done

@jeoffreyfischer and I paired up on this one.

We renamed all the images and folders that were not working.

This blog was helpful
https://www.hanselman.com/blog/git-is-casesensitive-and-your-filesystem-may-not-be-weird-folder-merging-on-windows
