### ISSUE TITLE
💄 Homepage - Logos fine tuning and alignment

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2861]
URL: https://www.ssw.com.au/

As per my conversation with @bettybondoc, some company logos on the homepage need a bit of redesign.
For instance, the CISCO logo is taller than the others; some of the logos also look slightly misaligned.
We need a designer's eyes to clean this up and ensure all logos are properly resized and aligned.

Note: The Events logo is not perfectly white

**Tasks (Designer)**
- [x] Resize and realign all logos consistently
- [x] Fix Events logo background colour to be perfectly white

**Tasks (Dev)**
- [x] Upload the new logos

**Screenshots**
![Image](https://github.com/user-attachments/assets/43b16bc8-e54c-4c33-8d95-ad134ea06e91)
**Figure: Logos that need to be redesigned**

**Comment by micsblank** [comment]
Please See https://www.figma.com/design/MoIHv08pADh7dzQdH4mTNi/SSW-Design-Library?node-id=2839-2711&t=gF2Oa8tGgEdiQpds-1 

<img width="1029" height="556" alt="Image" src="https://github.com/user-attachments/assets/b900d428-b922-450d-9d2a-f1460b88b74f" />
Figure: screenshot of SSW website figma.

**Comment by micsblank** [comment]
Additionally: 

https://www.figma.com/design/MoIHv08pADh7dzQdH4mTNi/SSW-Design-Library?node-id=236-632&t=gF2Oa8tGgEdiQpds-1

<img width="703" height="421" alt="Image" src="https://github.com/user-attachments/assets/9e8a9792-4efb-4bb3-b8e6-971a41c37110" />
Figure: Screenshot of logos within figma

**Comment by jeoffreyfischer** [comment]
<img width="3822" height="1736" alt="Image" src="https://github.com/user-attachments/assets/1c993dab-c9ad-40eb-8565-5a39c70e454c" />

**Figure: Before - ❌ Bad logo sizes**

<img width="3817" height="1738" alt="Image" src="https://github.com/user-attachments/assets/76b0991b-b769-4881-8bda-dac1b02f66e2" />

**Figure: After - ✅ Good logo sizes**

**Comment by micsblank** [comment]
Sharepoint location of images
https://sswcom.sharepoint.com/:f:/r/sites/SSWDesigners/Shared%20Documents/General/Project-SSWWebsite/External%20Company%20Logos?csf=1&web=1&e=7CkD4q

**Comment by jeoffreyfischer** [comment]
✅ Done - the new client logos are now live on https://www.ssw.com.au/

<img width="3803" height="1730" alt="Image" src="https://github.com/user-attachments/assets/7937a45d-0103-462c-95a8-ecacc1b498ad" />

**Figure: new client logos uploaded**
