### ISSUE TITLE
📄 Locations - Link to France and China

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Website#2862]
Cc: @adamcogan, @Calinator444, @jeoffreyfischer, @amankumarrr, @wicksipedia, @bradystroud, @UlyssesMaclaren 

Source: Email from Adam SSW.com.au to France and China  🇫🇷  🇨🇳

URL: 
- https://www.ssw.com.au/
- https://ssw.cn/
- https://ssw.fr/

1. As per SMS from Cameron he wants a link to SSW France and China here
2. And visa versa

We should have all of our locations referenced on all of our sites in the "Contact Us" page.

```[tasklist]
### Tasks
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/2867
```

Add all SSW Locations to:
- [x] AU
- [x] CN (Already done)
- [x] FR (Workaround until #1865)

**Screenshots**

![Image](https://github.com/user-attachments/assets/69e6b484-80cc-4801-b256-3e881c2a5164)
_**Figure: Why no reference to SSW France**_

**Additional context**

**Comment by wicksipedia** [comment]
dupe of #1865

**Comment by tkapa** [comment]
Hey @wicksipedia,

I closed #2867 as the dupe of #1865. I think it's possible for the accordion to still hold the content without needing to update the map.

**Comment by tkapa** [comment]
Done - This is now implemented on AU, CN and FR sites.
