### ISSUE TITLE
✨ New Template - Packaged Services

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#2870]
from email subject `Re: 👑 IMPORANT -  .NET MAUI Mobile Application: 3-day Assessment – Microsoft Azure Marketplace`

This is where all the new Azure Marketplace consulting services can live.

```[tasklist]
### Tasks
- [ ] Create the new collection schema
- [ ] Create the new page template
- [ ] MegaMenu - Add it somewhere under Services. could be a button next to View All Services, or a 3rd column
- [ ] Get a checked by from @samsmithssw @miichaelsmedley @uly1
```
