### ISSUE TITLE
✨ Sitemap - Add a page compiling all links on the site

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#2913]
CC: @tiagov8, @wicksipedia @sethdaily 

### Pain
There's a sitemap for the website, but we need a nice way of visualizing the content on the site.

### Solution
We should have a page that lists out all of the pages on the site

### Tasks Marketing

- [x] ~Update the XML sitemap: https://www.ssw.com.au/sitemap.xml~
- [x] ~Upload the new XML to Google~

### Tasks Development

- [ ] Create a sitemap page with a full list of pages on the site 
       ✅ A good example is https://www.nasa.gov/sitemap/ - It's a list of pages divided by sections in 3 columns. We can use that strucure at SSW
- [ ] Use the updated XML as a datasource 

#### Acceptance Criteria
- [ ] New page test passed by a designer
- [ ] Make sure the page placeholder with TODO: is removed (ssw.com.au/sitemap)

**Comment by tiagov8** [comment]
**Note:** We still need an XML sitemap to be submitted to Google ([more info](https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap))

The link https://www.ssw.com.au/sitemap.xml only has 4 pages, so it needs to be updated before-hand (I just added a task for that)

![Image](https://github.com/user-attachments/assets/87823b3f-b81e-4f52-9195-dbab4af20d3b)

**Comment by wicksipedia** [comment]
> **Note:** We still need an XML sitemap to be submitted to Google ([more info](https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap))

the sitemap above covers all pages - sitemaps can link to other sitemaps

**Comment by tiagov8** [comment]
as per @wicksipedia I marked the "Marketing" tasks as done
