### ISSUE TITLE
🗻Cloudflare Redirects Epic Part 1 - catch all routes for popular routes

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#2929]
```[tasklist]
- [x] Check Semrush to find routes with newer variants (e.g. /ssw/events should go to /events)
- [x] If applicable, add catch all redirects to the newer pages for these routes
```

### Acceptance criteria
- [ ] The existing cloudflare redirects under these routes should not be affected

**Comment by Calinator444** [comment]
I've had Aman review my PR but we don't want to push until Monday.

all traffic under ssw/employees will go to /people by default
all traffic under ssw/consulting will go to /consulting by default
all traffic under ssw/standards/rules will go to /rules by default
all traffic under ssw/events will go to /events by default
all traffic under /ssw/kb (previously our knowledge base page) will go to https://pdi-ssw.zendesk.com/hc/en-us


@amankumarrr I'm happy to have you merge on Monday but I won't be here

**Comment by jeoffreyfischer** [comment]
✅ Done - link to PR: https://github.com/SSWConsulting/SSW.Cloudflare/pull/21
