### ISSUE TITLE
🗻 Cloudflare Redirects Epic Part 2 - Investigate missing routes from front door/missing pages

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#2931]
### Description

Using the SEMrush audit, find any additional broken links on our site.

I've kept track of some of the pages that weren't archived while competing #2929 . Ideally this PBI should be completed after the work in #2929 is complete. This will filter out a lot of the noise from pages with newer variants (e.g. /ssw/standards/rules)

https://sswcom-my.sharepoint.com/:x:/g/personal/calebwilliams_ssw_com_au/EbpPe8y-5MVCujAk-cR5xagBnpCU8o2rLTX2W03KFkDe8A?e=HId1bD

**Comment by Calinator444** [comment]
@wicksipedia 

I won't be in until Thursday next week so I've created a spreadsheet of the broken internal links that we know of that haven't been fixed already. I've included the reason they return a 404 and my recommendations for fixing them. I'm hoping someone will be able to take this task over so that we can still achieve the sprint goal.

**Comment by Calinator444** [comment]
@wicksipedia 


There are a couple of pages that will need to be archived before we add redirects. I've kept track of these pages in the spreadsheet.

https://sswcom-my.sharepoint.com/:x:/g/personal/calebwilliams_ssw_com_au/EbpPe8y-5MVCujAk-cR5xagBnpCU8o2rLTX2W03KFkDe8A?e=HId1bD

For now I've added the following redirects that were missing according to the way back machine records since these changes could be immediately actioned.


/ssw/accessreporterforiis ➡️ /archive/access-reporter/default.html
/ssw/accessug ➡️/netug
/ssw/consulting/webapplications.aspx ➡️/consulting/web-applications
/ssw/database ➡️/consulting
/ssw/netug/ugevaluationsurvey.aspx ➡️/archive/netug/evaluation-survey/default.html
/ssw/netug/sswupdatepast.asp ➡️/newsletters
/ssw/sqldeploy/ ➡️https://www.sqldeploy.com/
/ssw/standards/developerdotnet/ ➡️/rules/rules-to-better-net-projects/
/ssw/standards/developersqlserver/ ➡️/rules/rules-to-better-sql-databases-developers/
/ssw/standards/developersqlserver/sqlserverstandard_2_storedprocedurenaming.aspx ➡️/rules/use-a-sql-server-stored-procedure-naming-standard/
/ssw/standards/developersqlserver/sqlserverstandard_4_indexesnaming.aspx ➡️/rules/use-a-sql-server-indexes-naming-standard/
/ssw/standards/developersqlserver/sqlserverstandard_5_relationshipnaming.aspx ➡️/rules/use-a-sql-server-indexes-naming-standard/
/ssw/standards/developergeneral/ ➡️/archive/standards/developer-general/the-best-3rd-party-tools.html
/ssw/standards/rules/rulestobettertechnicaldocumentation.aspx ➡️/rules/rules-to-better-technical-documentation/
/ssw/training/bi2010.aspx ➡️/archive/training/bi-the-glory.html
/ssw/training/sharepointforbusiness.aspx ➡️/archive/access-reporter/default.html
/ssw/news/news.aspx ➡️/company/news

**Comment by Calinator444** [comment]
@wicksipedia 

Hoping to get a decision from PO about whether to restore these pages. Haven't been able to get a hold of Adam, will try Ulysses next:


https://web.archive.org/web/20190322233320/https://www.ssw.com.au/ssw/WebServices/PostCode/

https://web.archive.org/web/20060303220010/http://www.ssw.com.au/ssw/methodology/XPDM.aspx


For now I'm restoring ssw.com.au/ssw/lookout which was deleted by mistake

**Comment by Calinator444** [comment]
As per our conversation in the daily I will:

- [x] Redirect this page to /products [https://www.ssw.com.au/ssw/WebServices/PostCode/](https://web.archive.org/web/20190322233320/https://www.ssw.com.au/ssw/WebServices/PostCode/)
- [x] Check the app insights logs to see if this page is being hit [http://www.ssw.com.au/ssw/methodology/XPDM.aspx](https://web.archive.org/web/20060303220010/http://www.ssw.com.au/ssw/methodology/XPDM.aspx)

**Comment by Calinator444** [comment]
As per my conversation with @wicksipedia I have ported the following pages and will add redirects


- [x] [http://www.ssw.com.au/ssw/methodology/XPDM.aspx](http://www.ssw.com.au/ssw/methodology/XPDM.aspx)

- [x] https://www.ssw.com.au/ssw/NETUG/DeveloperLinks.aspx

**Comment by Calinator444** [comment]
@wicksipedia 

Done - I used the way back machine to determine where the broken links I found previously redirected to. From there I restored the redirects I could find. For detailed information about why each redirect points to where it does please consult the [spreadsheet](https://sswcom-my.sharepoint.com/:x:/g/personal/calebwilliams_ssw_com_au/EbpPe8y-5MVCujAk-cR5xagBnpCU8o2rLTX2W03KFkDe8A?e=HId1bD).


### New Redirects
- https://www.ssw.com.au/ssw/Standards/Rules/RulesToBetterTechnicalDocumentation.aspx =>  https://www.ssw.com.au/rules/rules-to-better-technical-documentation/

- https://www.ssw.com.au/ssw/Standards/DeveloperDotNet/ =>https://www.ssw.com.au/rules/rules-to-better-net-projects/

- https://www.ssw.com.au/ssw/SQLDeploy/ => https://sqldeploy.com

- https://www.ssw.com.au/ssw/consulting/webapplications.aspx => https://www.ssw.com.au/consulting/web-applications
 
- https://www.ssw.com.au/ssw/Company/AboutUs.aspx => https://www.ssw.com.au/company/about-us
 
- https://www.ssw.com.au/ssw/Methodology/XPDM.aspx => https://www.ssw.com.au/archive/methodology/xpdm.html

- https://www.ssw.com.au/ssw/AccessUG => https://www.ssw.com.au/netug

- https://www.ssw.com.au/ssw/NETUG/DeveloperLinks.aspx => https://www.ssw.com.au/archive/netug/developerlinks.html

- https://www.ssw.com.au/ssw/NETUG/UGEvaluationSurvey.aspx => https://www.ssw.com.au/archive/netug/evaluation-survey/default.html

- https://www.ssw.com.au/ssw/Download => https://www.ssw.com.au/products

- https://www.ssw.com.au/ssw/Database/ => https://www.ssw.com.au/consulting

- https://www.ssw.com.au/ssw/NETUG/SSWUpdatePast.asp => https://www.ssw.com.au/newsletters

- https://www.ssw.com.au/ssw/LookOut/ => https://www.ssw.com.au/archive/look-out/default.html

- https://www.ssw.com.au/ssw/AccessReporterforIIS => https://www.ssw.com.au/archive/access-reporter/default.html

- https://www.ssw.com.au/ssw/Standards/DeveloperSQLServer/SQLServerStandard_5_RelationshipNaming.aspx => https://ssw.com.au/rules/use-a-sql-server-indexes-naming-standard

- https://www.ssw.com.au/ssw/news/news.aspx => https://www.ssw.com.au/company/news

- https://www.ssw.com.au/ssw/Standards/DeveloperSQLServer/SQLServerStandard_4_IndexesNaming.aspx => https://www.ssw.com.au/rules/use-a-sql-server-indexes-naming-standard/

- https://www.ssw.com.au/ssw/Standards/DeveloperGeneral => https://www.ssw.com.au/ssw/Standards/DeveloperGeneral/TheBest3rdPartyTools.aspx

- https://www.ssw.com.au/ssw/Standards/DeveloperSQLServer => https://www.ssw.com.au/rules/rules-to-better-sql-databases-developers/

- https://www.ssw.com.au/ssw/Training/bi2010.aspx => https://www.ssw.com.au/archive/training/bi-the-glory.html

- https://www.ssw.com.au/ssw/WebServices/PostCode/ => https://www.ssw.com.au/products

- https://www.ssw.com.au/ssw/Standards/DeveloperSQLServer/SQLServerStandard_2_StoredProcedureNaming.aspx => https://www.ssw.com.au/rules/use-a-sql-server-stored-procedure-naming-standard/

### New archived pages
- https://www.ssw.com.au/archive/look-out/default.html
- https://www.ssw.com.au/archive/methodology/xpdm.html
- https://www.ssw.com.au/archive/netug/developerlinks.html
