### ISSUE TITLE
🔍 Code Auditor - Daily Scan

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#3041]
**Description**
As per my conversation with @adamcogan, we will use Code Auditor on a daily basis to reduce the broken pages count on https://www.ssw.com.au/
We will work with @tiagov8

**Note**
I have updated the Code Auditor GH action cron job:
From: Weekly
To: Daily

**Tasks**
- [x] Look at the daily Code Auditor result: https://codeauditor.com/explore
- [x] Work with @tiagov8 to fix some broken pages
- [x] Repeat

**Acceptance criteria**
- [ ] Code Auditor finds 0 broken pages on https://www.ssw.com.au/

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 28 Aug 2024
**Broken Links:** 1,092
**Note:** All broken links are coming from the VM - ssw.com.au/ssw/...
They should be fixed once we switch off the VM

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 29 Aug 2024
**Broken Links:** 533
**Note:** 50% less than yesterday 🥳 
Aman has excluded the `/ssw/Redirects/*`
Reason: we have excluded those from our SEMrush audit
TODO: ask Tiago if he worked on it

**Comment by tiagov8** [comment]
Hi @jeoffreyfischer 

I have added a task for this and will work once a week on it:


ID | Work Item Type | Title | State | Effort | Iteration Path | Assigned To
-- | -- | -- | -- | -- | -- | --
96577 | Task | [Fix some CodeAuditor for SSW.Website](https://ssw.visualstudio.com/SSW.Design/_workitems/edit/96577) | To Do |   | SSW.Design\Sprint 431 | Tiago Araujo

**Comment by jeoffreyfischer** [comment]
**Scanned on**: 30 Aug 2024
**Broken Links**: 530

**Comment by jeoffreyfischer** [comment]
⚠️ CodeAuditor scans are failing
I have created the following PBI to be fixed by @zacharykeeping : #3055

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 5 Sept 2024
**Broken Links**: 502

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 6 Sept 2024
**Broken Links:** 506

**Comment by jeoffreyfischer** [comment]
**Scanned on**: 9 Sept 2024
**Broken Links**: 508

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 10 Sept 2024
**Broken Links:** 506

**Comment by jeoffreyfischer** [comment]
As per my conversation with @tiagov8, he will fix some broken links this week

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 10 Sept 2024
**Broken Links:** 498

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 12 Sept 2024
❌ The build failed twice today
@zacharykeeping can you please work on this PBI: https://github.com/SSWConsulting/SSW.Website/issues/3055

**Comment by jeoffreyfischer** [comment]
**Scanned on**: 13 Sept 2024
**Broken Links**: 496

**Comment by jeoffreyfischer** [comment]
**Scanned on**: 16 Sept 2024
**Broken Links**: 493

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 17 Sept 2024
**Broken Links:** 496

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 18 Sept 2024
**Broken Links:** 495

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 19 Sept 2024
**Broken Links:** 478

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 20 Sept 2024
**Broken Links**: 468

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 23 Sept 2024
**Broken Links:** 468

**Comment by jeoffreyfischer** [comment]
**Scanned on**: 24 Sept 2024
**Broken Links**: 468

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 26 Sept 2024
**Broken Links:** 472

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 26 Sept 2024
**Broken Links:** 469

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 30 Sept 2024
**Broken Links:** 468

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 2 Oct 2024
**Broken Links:** 447

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 3 Oct 2024
**Broken Links:** 462

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 4 Oct 2024
**Broken Links:** 467

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 9 Oct 2024
**Broken Links:** 460

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 10 Oct 2024
**Broken Links:** 457

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 16 Oct 2024
**Broken Links:** 448

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 21 Oct 2024
**Broken Links:** 441

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 22 Oct 2024
**Broken Links:** 441

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 23 Oct 2024
**Broken Links:** 441

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 23 Oct 2024
**Broken Links:** 433

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 25 Oct 2024
**Broken Links:** 432

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 4 Nov 2024
**Broken Links:** 433

**Comment by jeoffreyfischer** [comment]
CodeAuditor has been failing on Website for a few weeks.
I created a PBI for @zacharykeeping 
Link to PBI: https://github.com/SSWConsulting/SSW.CodeAuditor/issues/948

As per my conversation with Zach, he is on client work and can't work on it at the moment.

**Comment by jeoffreyfischer** [comment]
✅ Done - Caleb fixed the bug 🥳
Link to PBI: https://github.com/SSWConsulting/SSW.CodeAuditor/issues/948

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 14 Jan 2025
**Broken Links:** 363

Note: 66 broken links on /consulting

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 16 Jan 2025
**Broken Links:** 362

Note: 66 broken links on /consulting

**Comment by tiagov8** [comment]
cc @adamcogan @Calinator444 

Hi @jeoffreyfischer 

CodeAuditor is saying that all link on Consulting index have a duplicate folder "consulting/consulting/..." in them...

But if you go to the page and click, they are working fine... (see images below)

Looking at the code, it also seems all good: https://github.com/SSWConsulting/SSW.Website/blob/main/content/consulting/index/index.json

I believe this is a CodeAuditor bug... 

- [ ] 1. Can you have a dev look, and if confirmed, open an Issue to fix CodeAuditor?

### CodeAuditor showing wrong links

<img width="1099" alt="Image" src="https://github.com/user-attachments/assets/2655f592-943a-487e-ac69-3af861037532" />

---

### Real Consulting index page gives correct ones

<img width="1010" alt="Image" src="https://github.com/user-attachments/assets/e98f8811-ca86-4155-98ac-a91d8d6f81a9" />

**Comment by isaaclombardssw** [comment]
Scanned on: 26 Jan 2025
Broken Links: 363

Note: 66 broken links on /consulting

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 3 Feb 2025
**Broken Links:** 363

Note: 66 broken links on /consulting

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 4 Feb 2025
**Broken Links:** 360

Note: 66 broken links on /consulting

**Comment by jeoffreyfischer** [comment]
**Scanned on:** 10 Feb 2025
**Broken Links:** 332

Note: 66 broken links on /consulting

**Comment by babakamyljanovssw** [comment]
Scanned on: 23 Feb 2025
Broken Links: 322

Note: 65 broken links on /consulting

**Comment by babakamyljanovssw** [comment]
Scanned on: 3 March 2025
Broken Links: 334

Note: 65 broken links on /consulting

**Comment by babakamyljanovssw** [comment]
Scanned on: 9 March 2025
Broken Links: 327

Note: 65 broken links on /consulting

**Comment by babakamyljanovssw** [comment]
Scanned on: 17 March 2025
Broken Links: 261

Note: 0 broken links on /consulting

**Comment by babakamyljanovssw** [comment]
Hi @tiagov8

Broken links on /consulting are fixed and currently there is none broken links on /consulting

**Comment by babakamyljanovssw** [comment]
Scanned on: 25 March 2025
Broken Links: 141

Note: 0 broken links on /consulting

**Comment by babakamyljanovssw** [comment]
Scanned on: 30 March 2025
Broken Links: 97

Note: 0 broken links on /consulting

**Comment by babakamyljanovssw** [comment]
Scanned on: 8 April 2025
Broken Links: 73

Note: 0 broken links on /consulting

**Comment by babakamyljanovssw** [comment]
Scanned on: 13 April 2025
Broken Links: 48

Note: 0 broken links on /consulting

**Comment by babakamyljanovssw** [comment]
Scanned on: 21 April 2025
Broken Links: 50

Note: 0 broken links on /consulting
