### ISSUE TITLE
✨ User Group Page - Live UG

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.Website#334]
~~⛔Do not proceed until the re-design mockup is added here.~~

Migrate https://www.ssw.com.au/ssw/Live/

![Image](https://user-images.githubusercontent.com/16027480/222402165-e01a04eb-b09a-4641-a976-11ad7e9bb6fb.png)

_Updated on Mar 7th 2023_
As per conversation with the TV team, this page needs a re-design to improve user experience.

```[tasklist]
### Tasks
- [x] Migrate page
- [x] Use SSW Google Account from Keeper to get YouTube API keys (maybe one of the accounts already has YouTube API provisioned)
- [x] Create a file in the services folder to fetch data from the YouTube API, then use in the `getStaticProps` function
- [x] Use [Incremental Static Regeneration](https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration) in a `live.tsx` page file to fetch latest videos in the UG playlist
- [x] Display "Upcoming Session Details" from SharePoint data (to also be fetched in getStaticProps using ISR) - same logic as in `netug/[[...filename]].tsx` and `events`
- [x] Display data under the "Upcoming Session Details" using `Event` in `events.tsx`
- [x] Update link of banner to point to the new page
- [x] Update Front Door
```

**Comment by jeoffreyfischer** [comment]
As per my conversation with Ken, I will also work on the following tasks: 

- [x] Use the [User Group banner](https://www.ssw.com.au/netug/sydney) (with grey background) for the Live page title
- [x] Use "see more" after 6 videos on the page (to avoid having too many videos).
- [x] Remove the "play" icon from the video component.

**Comment by jeoffreyfischer** [comment]
As per my conversation with Ken, I will also work on the following tasks:
- [x] Add a breadcrumb
- [x] Remove the "see more" button

**Comment by jeoffreyfischer** [comment]
- Description: The /live page needed to be migrated to the new Website. Each elements of the page is described in order in the Screenshots section below.

- Affected routes: /live

- Fixed #334 

- Done Video: https://www.youtube.com/watch?v=0Y5NF-NI1Lw

- Screenshots:

![live-page1](https://github.com/SSWConsulting/SSW.Website/assets/106663901/864ff3ab-7289-4007-9b91-db23091c0696)
**Figure**: The page title (can be changed using Tina). The breadcrumb is shown below the title.

![live-page2](https://github.com/SSWConsulting/SSW.Website/assets/106663901/d105570f-3258-4eed-b150-737eb7169f62)
**Figure**: The upcoming session section (Name can be changed in Tina - Content is loaded from SharePoint). The button at the bottom opens a new tab towards the [SSW TV channel](https://www.youtube.com/channel/UCBFgwtV9lIIhvoNh0xoQ7Pg).

![live-page3](https://github.com/SSWConsulting/SSW.Website/assets/106663901/384f79dd-5b14-472a-97ae-70ed947c7071)
**Figure**: The past sessions recordings (Name can be changed in Tina - Content is loaded from YouTube using Google API). Only the last 6 videos are displayed. The button at the bottom opens a new tab towards the [YouTube Playlist](https://www.youtube.com/playlist?list=PLpiOR7CBNvlpmhfwQeIVhbqZKxV-do0wY).

**Comment by jeoffreyfischer** [comment]
Done Video V2: https://www.youtube.com/watch?v=2HNSiR-Gw3c

**Comment by jeoffreyfischer** [comment]
Done Video V3: https://www.youtube.com/watch?v=t12RgV9q_UQ
