### ISSUE TITLE
✨ Add Microsoft Clarity Data Tracking Notification

### ISSUE THREAD

**Issue by louisroa8189** [SSWConsulting/SSW.Website#3349]
**Is your feature request related to a problem? Please describe.**
Currently, there is no clear disclosure to inform visitors about our use of Microsoft Clarity for website data analysis. This could lead to a lack of transparency and potential compliance concerns.
 
**Describe the solution you'd like**
Implement a one-time notification or header pop-up with the following text: "We use third-party tracking to improve our products and advertising by analyzing website usage. By using our site, you consent to data collection by us.".
The pop-up should be easy to dismiss (e.g., "Accept" or "Close" button) and appear only once per user session.
 
**Describe alternatives you've considered**
Only adding the footer disclosure without the notification, but this may not draw enough attention to the message. And also, not quite transparent (if I don't even see it, do I actually consent?).
 
**Additional context**
Ensure that the pop-up/banner is unobtrusive and aligns with the overall website design. Feedback on the best implementation approach is welcome.
 
**Tasks**
- [ ] Collaborate with a designer to create mockups for the pop-up
- [ ] Implement the pop-up
- [ ] Ensure the final implementation is test passed by @louisroa8189 , a designer, and any other relevant approvers (again, suggestions welcomed)

 
CC: [@uly1](https://github.com/uly1) [@wicksipedia](https://github.com/wicksipedia) [@bettybondoc](https://github.com/bettybondoc)
