### ISSUE TITLE
🐛 Megamenu - Discards prefetched data on load

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#3357]
CC: @wicksipedia 

### Description:
There's a useEffect hook that runs in the megamenu that gets used to update the links. The issue is that this is that this hook runs immediately when the component mounts (because of the empty dependency array), and it's asynchronous so it discards the prefetched data. It also uses the full API URL for the SSW mega menu endpoint, making it impossible to preview changes to the MegaMenu in staging.
![Image](https://github.com/user-attachments/assets/649017c3-f53e-4d40-adba-673b1cae6096)

### Todo:

- [ ] Remove the megamenu data fetch from the megamenu repo
- [ ] Communicate with the SSW Rules team to check whether the megamenu props on Rules are passed in statically
- [ ] Communicate with the SSW People team to check whether the megamenu props on Rules are passed in statically

**Comment by Calinator444** [comment]
Closed as duplicate

https://github.com/SSWConsulting/SSW.MegaMenu/issues/60
