### ISSUE TITLE
📦 Breaking out the components into a separate npm package

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#3416]
## Description
I want to **break out new components into a separate NPM package**.

## Tasks
- [x] Create the new NPM package structure.
- [ ] Refactor components into the package, ensuring separation of concerns.
- [ ] Update imports in the main project to use the new package.
- [ ] Set up CI/CD pipeline for the package.
- [ ] Write or update documentation for the package.
- [ ] Test the integration of the package with the main project.

## Acceptance Criteria

- [ ] A new NPM package is created and published under the organization's registry.
- [ ] Components are refactored out of the main project into the new package, maintaining full functionality.
- [ ] Documentation for the new package includes:
    - Installation instructions
    - Usage examples for each component
    - Versioning guidelines
- [ ] The main project is updated to consume the new NPM package instead of the local components.
- [ ] CI/CD pipeline is set up for the new package to handle:
    - Linting
    - Publishing to the registry

**Comment by isaaclombardssw** [comment]
Update – I've created the repo and based it off this package... https://github.com/pcode-at/tinacms-seo.

**Comment by Calinator444** [comment]
I've created a repo for building the component library using rollup based on the files @isaaclombardssw provided me with while working on this.

My plan is to get the components working in a state where I can easily import, customize and use them in the Tina starter repo and then publish the package to NPM.

There's still some work that needs to be done because the components don't work very well as standalone components. We also need  to make a decision as to whether we should take an opinionated or unopinionated approach to schema management as this will affect developers implement contextual editing.

https://github.com/Calinator444/ssw-consulting-component-lib


![Image](https://github.com/user-attachments/assets/918a8f5e-a1fa-41a1-b69b-cbdc8502a673)


Todo: Configure

- [x] Breadcrumbs
- [ ] Carousel
- [ ] Color Selector
- [ ] Image and text block
- [ ] Ripple button
- [ ] logo carousel

**Comment by Calinator444** [comment]
Todo: Configure

- [x] Breadcrumbs
- [ ] Carousel
- [ ] Color Selector
- [ ] Image and text block
- [ ] Ripple button
- [ ] logo carousel

**Comment by Calinator444** [comment]
TODO: add custom prefixes to custom tail classes

**Comment by jeoffreyfischer** [comment]
TODP - use custom prefix to avoid collision

**Comment by Calinator444** [comment]
As per my conversation with @wicksipedia I should publish the NPM package with some of the components soon for feedback. The CI/CD is a lower priority.

**Comment by Calinator444** [comment]
I've moved the repo for these components to SSW's GitHub. 

I've also created a GitHub token for hosting these using NPM and am planning to deploy the Breadrumb component for feedback ASAP. The Other two components in the repo (the card carousel and the logo carousel) don't have typing set up yet and aren't ready to be used.

https://github.com/SSWConsulting/SSW.TinaCMS.LandingKit.

**Comment by Calinator444** [comment]
I've released the logo carousel on NPM and updated the documentation to include it as well as the breadcrumb component

![Image](https://github.com/user-attachments/assets/488b1edc-16e6-4059-a184-5b4ceb4bb7b3)

**Comment by Calinator444** [comment]
@wicksipedia 

Here's how the Card Carousel is currently looking. I've extracted the "attached cards" field into it's own component and improved how it works. In production you need to modify the cards before you can bind them to a category group but for the NPM package you don't.

I'm struggling with making it customizable. These components were designed to look good on the consulting page which has a grey background but If we're going to be using them in the tina starter I think I should add settings to configure things like the button colors and card background.

The icon picker was tricky to get working, but I've allowed users to pass in their preferred icon library from React icons as a property. This should help with the bundle size.

![Image](https://github.com/user-attachments/assets/704ca016-ffac-4c13-9931-bb45a71b37f2)

**Comment by Calinator444** [comment]
I've published the following components to npm and updated the docs:

- CardCarouselPicker
- BreadCrumbs
- LogoCarousel

![Image](https://github.com/user-attachments/assets/39fb601d-52d1-45da-9e42-58f35de1e2d8)
**Figure**:**color picker freezing when imported through NPM**
There are still some issues though:
- The icon picker isn't working when imported as a node module (I tested it using PNPM link)
- The colors are missing from the color picker

![Image](https://github.com/user-attachments/assets/3fe05afe-3d89-4562-9a52-3441b143d9f1)
**figure**: **Primary should be red**

![Image](https://github.com/user-attachments/assets/933d6cf5-4cf0-4a34-9eeb-7d91e84739aa)

**Figure**: **Components imported from NPM**

**Comment by isaaclombardssw** [comment]
This PBI is oversized, we've split it up into

#3555 #3556 #3557 #3558
