### ISSUE TITLE
📄 Pages - Migrate Employment page

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#348]
Migrate https://www.ssw.com.au/ssw/Employment/default.aspx

```[tasklist]
### Tasks
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/445
- [x] Add component to show current opportunities (filter on the left, accordion of data on right)
- [x] Add page content
- [x] Add route to front door
- [x] Update megamenu link (if exisits)
- [x] Add done video + wiki page for adding/editing opportunities
- [x] Send a done email to Penny + anyone else who would edit this showing them the wiki and video
```
