### ISSUE TITLE
Update Infra - Adding secrets to keyVault

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#502]
### Description:
Currently, we are accessing secrets from GitHub secrets which are not accessible to Next server, therefore we decided to create a keyvault in order to get the secrets to our App Service config.

```[tasklist]
### Tasks
- [x] Create new vault for the Service App (when PR merges to the main)
- [x] Add secrets to the Vault (Manually)
- [x] Update the secrets from the GitHub secrets to reference it back to keyVault (Manually)
```
