### ISSUE TITLE
💄 Internship page style changes

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.Website#505]
As per my conversation with @hveraus, the following design changes need to be made to the internship page.

```[tasklist]
### Tasks
- [x] Font | Body should be Open Sans
- [x] Font | Headings should be Helvetica Neue
- [x] Buttons | Buttons should all with rounded corner
- [x] Hero Image | “Apply Now” button, please change to rounded corner without arrow icon
- [x] Hero Image | Tagline is too bold, please change to semi-bold, also check the library, H1 set to medium weight
- [x] Hero Image | Piers photo should be smaller and should not cut his elbow off
- [x] Hero Image | we might not need the paragraph under tagline
- [x] Hero Image | when scale down the page, Piers should be still visible
- [x] Who What When | Double check the bottom padding, seems too small
- [x] Who What When | the three red icons and grey checks seems not high res, and grey checks are too big
- [x] Who What When | Text under Who and What should be bold and use Helvetica
- [x] Who What When | More padding between “Starts every Monday” and “Next program”
- [x] Who What When | Figures on counter down should be Helvetica
- [x] What will you learn | logos needs to be updated
- [x] Popular courses | the video cards should be rounded corner
- [x] Popular courses | “Watch More Videos” button should be rounded corner
- [x] Popular courses | Play button should have a rounded corner triangle
- [x] Popular courses | titles should be Helvetica
- [x] What do people say | missing 5 stars
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/604
- [x] Trusted by… | title should be H2 instead of H1
```

**Comment by bradystroud** [comment]
Everything is done or moved to a new issue
