### ISSUE TITLE
📄 User group Page - Sydney + Template

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#512]
Migrate and redesign as per #997

URL:https://www.ssw.com.au/ssw/NETUG/Sydney.aspx

Ask @camillars about any content questions

```[tasklist]
### Tasks
- [x] Migrate with redesign
- [x] Get new design test passed by Camilla, then Matt W
- [x] Update megamenu link
- [x] Add redirect to Azure Front Door
- [x] Add new SharePoint process to marketing SugarLearning item at https://my.sugarlearning.com/SSW/items/10632/events-adding-events-on-ssw-events-page
- [x] Add torso image information to https://my.sugarlearning.com/SSW/items/14104/events-user-group-finding-and-reaching-out-to-speakers and the Microsoft Form
```

**Comment by Harry-Ross** [comment]
cc @hveraus 

As per my conversation with @jaydenalchin and @bradystroud, we will make the following modifications to the design:

* Move the about the user group to its own section on the page - "What is the .NET User Group?" (bottom of page)
* Make "Watch the trailer" a secondary button next to "Register for free"
* Put event description where "About the event" currently is

**Comment by Harry-Ross** [comment]
Front Door redirect is blocked by broken deployments

**Comment by Harry-Ross** [comment]
Completed as per @camillars email "RE: External Speakers Form Image Addition", updated on the Microsoft Form.
