### ISSUE TITLE
📄User group Page - Canberra 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#513]
Migrate and redesign as per #997

URL: https://www.ssw.com.au/ssw/NETUG/Canberra.aspx

Ask @camillars about any content questions

```[tasklist]
### Tasks
- [x] Migrate with redesign
- [x] ~Get new design test passed by Camilla, then Matt W~ (Design has already been checked for Sydney, Brisbane and Melbourne)
- [x] Update megamenu link
- [x] Add redirect to Azure Front Door
```

**Comment by amankumarrr** [comment]
Done

<img width="726" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/41fffaa6-d70a-44b4-b261-942278d0529b">
