### ISSUE TITLE
📄User group Page - Melbourne

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#514]
Migrate and redesign as per #997

URL: https://www.ssw.com.au/ssw/NETUG/Melbourne.aspx

Ask @camillars about any content questions

```[tasklist]
### Tasks
- [x] Migrate with redesign
- [x] ~Get new design test passed by Camilla, then Matt W~ (Design has already been checked for Sydney and Brisbane)
- [x] Update megamenu link
- [x] Add redirect to Azure Front Door
```

**Comment by amankumarrr** [comment]
Done 
<img width="800" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/9f51332d-97d8-4e69-8dc9-854febf990d1">

**Figure: Melbourne's UG page on production**
