### ISSUE TITLE
📄User group Page - Brisbane

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#515]
Migrate and redesign as per #997

URL: https://www.ssw.com.au/ssw/NETUG/Brisbane.aspx

Ask @camillars about any content questions

```[tasklist]
### Tasks
- [x] Migrate with redesign
- [x] Update megamenu link
- [x] Add redirect to Azure Front Door
```
