### ISSUE TITLE
🔊 Logging - App Insight in NextJs 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#555]
### Description:

We need to add logs into App Insight.

There are a lot of places we could add logging, and the important one is to log leads when external endpoints could fail.

```[tasklist]
### Tasks
- [x] Update env biceps to create App Insight
- [x] Add logging to front-end
- [x] Add logging to back-end
```
