### ISSUE TITLE
Visibility on secrets expiration 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#556]
### Description:

We must avoid situations where our external endpoints could break due to any expiration of secrets or passwords without any visibility or notifications. Therefore, we must work with SysAdmins to cater to this problem in the future. 

This particular problem caused huge issue for the enquiry forms failing silently. 

### Tasks:
- [ ] Reproduce the same bug by expiring or deleting the secret
- [ ] Add email notifications to SysAdmins prior to secret expiry 
- [ ] HTML - Confirm we do not show any error on the client side + link to rule explaining why   
- [ ] Investigate adding integration tests
- [ ] Investigate adding a health check for the website
