### ISSUE TITLE
📝  Video on how to edit a page

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.Website#581]
A video showcasing how to create / edit content would be nice to have alongside the wiki

```[tasklist]
### Tasks
- [ ] Film video
- [ ] Get checked by Brady
- [ ] Add to wiki
- [ ] Consider using for a CTF
```

**Comment by andrewwaltosssw** [comment]
A great video by Brady has been added to Wiki: https://github.com/SSWConsulting/SSW.Website/wiki/Editing-the-website

![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/fb21cb97-2005-4705-bc97-32060320464c)
**Figure: Screenshot of the video on the Wiki**
