### ISSUE TITLE
💄 Internship Page Feedback

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.Website#591]
Feedback from @adamcogan and @pierssinclairssw for the internship page

https://www.ssw.com.au/training/fullstack

```[tasklist]
### Tasks
- [x] Add breadcrumbs to Training page
- [x] Add training page link to megamenu  ![MicrosoftTeams-image](https://user-images.githubusercontent.com/25432120/236741675-b840b184-66e3-45db-8a44-498e42f15cc5.png)
- [x] Increase font size for the "Who, What, When" section  ![image](https://user-images.githubusercontent.com/25432120/236741951-eb618d0e-97ca-4cff-be91-91f466c7349d.png)
- [x] Fix header text capitalisation (e.g. from "Learn How To Be An" to "Learn how to be an")
- [ ] ~~Once done all tasks above, get checked by ~~Piers~~ then Adam~~
```

**Comment by PothieuG** [comment]
- I had to add a temporary "seo" description to the training .md to create the breadcrumbs waiting for the final description.
- i added a link in the megamenu, but I wasn't sure in which category and what text to use. Here is the PR : https://github.com/SSWConsulting/SSW.Website.Menu.json/pull/72

**Comment by PothieuG** [comment]
- The feature is ready for review.
- Piers and Adam also need to validate the feedback.

**Comment by PothieuG** [comment]
New PR : https://github.com/SSWConsulting/SSW.Website-v3/pull/686  
Closing the old one (merging problem, too much changes)

**Comment by bradystroud** [comment]
Hey @PothieuG 

> Increase font size for the "Who, What, When" section

Can you clarify what was changed for this item?

> Once done all tasks above, get checked by Piers then Adam

Was this done?

**Comment by PothieuG** [comment]
Hey @bradystroud 
That PR is no longer useful, we already merged all we needed here : https://github.com/SSWConsulting/SSW.Website-v3/pull/686

- The font-size of all the box "who", "when", "where" has been incresed, not only the words.
- I didn't find the time to check this page with Adam or Piers

**Comment by bradystroud** [comment]
Hey @PothieuG 

As per our conversation, you are going to get this checked by Adam while he's in France 🇫🇷

**Comment by bradystroud** [comment]
Closing as final task (crossed out) has been moved to #822
