### ISSUE TITLE
🐛 Sitemap not working

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#592]
Ensure our generated sitemap is live (so google can find it)

The sitemap is being generated, but for some reason it is not accessible.

```[tasklist]
### Tasks
- [x] Make sitemap accessible
- [x] Add to Google Search Console
- [ ] ~~Remove the old sitemap https://ssw.com.au/ssw/sitemap~~
```

**Comment by jimmidier** [comment]
Reopning for undone tasks

**Comment by jimmidier** [comment]
> Add to Google Search Console  

Done with the help of @bradystroud as below
<img width="2140" alt="MicrosoftTeams-image" src="https://github.com/SSWConsulting/SSW.Website-v3/assets/16027480/816f8354-d4cf-4c70-96a9-ff74c5f6eac0">

> Remove the old sitemap https://ssw.com.au/ssw/sitemap  

Not done - As per conversation with @bradystroud we should keep the old sitemap for now as we still need some of the old links
