### ISSUE TITLE
Epic - Events Pages

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#593]
![Image](https://user-images.githubusercontent.com/38869720/236738862-2f09cea9-7502-4a85-95d2-a9343f61c196.png)

The events pages should move to /events.

Converting the pages to this new style will mean some content might need to be removed, and new content will be needed.

Try get any new content from ChatGPT
If you remove any content, document what was removed
Remove any covid related stuff (in person /online)

```[tasklist]
### Training pages
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/594
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/595
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/598
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/596
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/602
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/597
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/599
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/1054
```

```[tasklist]
### Other pages
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/603
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/601
```

**Comment by amankumarrr** [comment]
As per my conversation with @bradystroud, this issue is not ready to work on as it requires some discussion because our current template `training/full-stack` doesn't support all the content from other training pages. 

We might need to create a new template for these pages but it would be under a different route.

**Comment by bradystroud** [comment]
As per my conversation with @amankumarrr and @camillars , all Superpowers, workshops and Super Skills pages should be under the route of /events and the Internship page will remain under /training.

**Comment by bradystroud** [comment]
Done - This issue was an epic for all the events pages which have been migrated
