### ISSUE TITLE
📄 Events - Angular Superpowers

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#594]
https://www.ssw.com.au/ssw/Events/Training/Angular-Superpowers-Tour.aspx 

move to `/training/angular-superpowers`

Sidebar - move to a row
Video - move to the carousel
Migrate all text content
Build the booking component

![Image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/982525ef-1ced-4c74-ba8a-60d8515c2aa9)

Ask @camillars if we need the Twitter component

Ask @camillars if we need the locations component

![Image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/2b6507ca-7712-406b-abbd-d9c209074541)

Ask @camillars if we need the past events section
![Image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/cc1d474a-64e4-49c5-8cee-30de4de8ff1c)

```[tasklist]
### Tasks
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/918
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/943
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/964
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/1003
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/1022
- [x] Mega Menu - Update route
```
- [ ] ~Front Door - Add redirect~

**Comment by camillars** [comment]
Hi @bradystroud 

thanks for this!

✅ we need this:
locations component

❌ we don't need these:
Twitter component
past events section

**Comment by amankumarrr** [comment]
@wicksipedia 

As per my conversation with @brydeno  and @camillars , all Superpowers, workshops and Super Skills pages should be under the route of `/events` and the Internship page will remain under `/training`.
Therefore, marking this task as done and removing the task for Front Door redirection from this issue and it will be catered by this issue #1054
