### ISSUE TITLE
📄 Events - Custom Training Options

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#601]
https://www.ssw.com.au/ssw/Events/Training/Training-Options.aspx
```[tasklist]
### Tasks
- [x] Migrate content from old page.
- [x] Add new banner
- [x] Update megamenu link
- [x] Add redirect to front door
```

**Comment by KristenHu** [comment]
- [x] Update megamenu link
**Done** - https://github.com/SSWConsulting/SSW.Website.Menu.json/pull/98

- [x] Add redirect to front door
**Done** - https://github.com/SSWConsulting/SSW.FrontDoor/pull/96
