### ISSUE TITLE
📄 Embed office walkthrough video

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#623]
(copied from email "Include SSW offices Walkthrough videos on each SSW office's webpage")
cc: @LuciaSirtori @adamcogan 

For each office page, embed the walkthrough video.

URLs
- https://www.ssw.com.au/offices/sydney
- https://www.ssw.com.au/offices/melbourne
- https://www.ssw.com.au/offices/brisbane
- https://www.ssw.com.au/offices/newcastle

```[tasklist]
### Tasks
- [x] Sydney: https://r.ssw.com/sswsydneytour
- [x] Melbourne: https://r.ssw.com/sswmelbournetour
- [x] Brisbane: https://r.ssw.com/sswbrisbanetour
- [x] Newcastle: https://r.ssw.com/sswnewcastletour (please replace old video from the webpage)
```

<img width="1382" alt="image" src="https://github.com/SSWConsulting/SSW.Website-v3/assets/38869720/22e0fe7a-fdaa-4d8a-bcfb-8a2a3c0d9624">
<b>Figure: Replace this video on the Newcastle page</b>

**Comment by PothieuG** [comment]
- The feature is ready for review.
