### ISSUE TITLE
💸 Tech Debt - 6000 items in public/images 

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#624]
cc @KristenHu 
**Description**  
The images folder on the website has 6000 items... mostly because of newseltters.

This makes the Media Manager on the TinaCMS pretty much unusable as there is no way to search, sort or filter.

```[tasklist]
### Tasks
- [x] Move the newsletter images to `public/images/newsletters`
- [x] Any other images in that folder - can they be moved to a subfolder?
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/808
```

**Comment by bradystroud** [comment]
All the newletter images have been moved to `/images/newsletters` and i have updated the references of these images in the newsletter files.

I found that there are a lot of images that are not used. I am going to remove them.
