### ISSUE TITLE
♻️ CodeAuditor report - Fix bad HTML code

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.Website#625]
Cc: @adamcogan @william-liebenberg @KristenHu @amankumarrr 

Hi @bradystroud 

### Pain

As per our conversation, we need to fix bad HTML code in SSW Website that are reported from CodeAuditor report and reduce the numbers. From latest scan on SSW Website, there are **14,984 code warnings** and **7,125 code errors** 

See https://codeauditor.com/latest/02ad5e57-04e6-4c4f-bdd4-1e62d495e6d5/ssw.com.au for latest scan on SSW Website

```[tasklist]
### Tasks
<!--Add GitHub tasks-->
- [ ] Check latest SSW Website scan from CodeAuditor to see full details of code errors and warnings
- [ ] Fix the HTML code in SSW Website accordingly
- [ ] Rerun the scan and check if code errors and warnings have gone down
- [ ] Give me an update
```

### Screenshots

![image](https://github.com/SSWConsulting/SSW.Website-v3/assets/67776356/ea93734f-549c-415f-9dcd-8ff0ed978ca5)

**Figure: Latest SSW Website scan report from [CodeAuditor](https://codeauditor.com/htmlhint/7fc92472-1baa-4fb6-aad6-5357396812a0)**

Thanks!

**Comment by BrookJeynes** [comment]
@adamcogan @william-liebenberg @KristenHu @amankumarrr @bradystroud 

Closing as this has been moved into 3 separate issues:
- https://github.com/SSWConsulting/SSW.Website-v3/issues/700
- https://github.com/SSWConsulting/SSW.Website-v3/issues/701
- https://github.com/SSWConsulting/SSW.Website-v3/issues/702
