### ISSUE TITLE
✨ Front door - Add routes for Educational page and GPT 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#640]
### Description:
We need to add front door routing for the `/educational`. Currently it is taking us to the old page and same for the GPT page.

```[tasklist]
### Tasks
- [x] Add Eductional
- [x] Add ChatGPT (once the new one is ready)
```

**Comment by KristenHu** [comment]
https://github.com/SSWConsulting/SSW.FrontDoor/pull/43
PR has been merged, this issue can be closed.

**Comment by bradystroud** [comment]
Front door changes need to be manually deployed, these changes have not been deployed.

- [x] Test in staging (tfs365.com)
- [x] Deploy to prod

**Comment by bradystroud** [comment]
Done - Both routes are live

| Old | New |
|-----|-----|
|  https://www.ssw.com.au/ssw/Consulting/Gpt.aspx  |   https://www.ssw.com.au/consulting/gpt  |
|  https://www.ssw.com.au/ssw/Educational/  |   https://www.ssw.com.au/educational  |


Old URLs redirect to the new ones
