### ISSUE TITLE
💸 Create lead - Power Automate flows' failure handling

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#641]
**Description**  
We need to explore options for receiving notifications in the event of a failure in the Power Automate flow.

```[tasklist]
### Tasks
- [x] Investigate the options
- [x] Propose the solution
- [x] Implement the solution
- [x] Flow failover - Deploy it to Production
```

**Comment by amankumarrr** [comment]
As per my conversation with @bradystroud, he passed the following email template for the event of any failure from the flow. However, it requires to get it passed from the Account Manager. 



![Image](https://github.com/SSWConsulting/SSW.Website-v3/assets/71385247/b8d6af1c-7f13-40c4-b209-4c55ec4d67f3)
**Figure: showing the email template from flow**

**Comment by amankumarrr** [comment]
As per my conversation with @Marxoz, he passed the following template.


![Image](https://github.com/SSWConsulting/SSW.Website-v3/assets/71385247/a63f5088-0d5c-4774-9011-5fc5a84258db)
**Figure: showing the email template from flow**

**Comment by amankumarrr** [comment]
@bradystroud @wicksipedia 
We have successfully deployed the failover handling for our create lead Power Automate flow on production. So in any case of failure due to connection string from the Powe Automate, all the Devs of SSW website v3 and Accounts manager will receive the email containing the warning and the content of the lead along with the URL of the flow.
