### ISSUE TITLE
🐛 - Newsletter Power Automate flow is failing for Production environment   

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#685]
**Describe the bug**
Our newly created endpoint on Power Automate flows is failing for our Power Apps' Production environment. However, it is working fine in the Dev environment.  

```[tasklist]
### Tasks
- [x] Investigate the error with the old endpoint where it was not working
- [x] Propose the solution
- [x] Test it on the Production endpoint
- [x] Ask the CRM team to replicate the prod environment on both Dev and UAT
```
**To Reproduce**
- Hit the endpoint with the payload 
`{
    "Email": "test@gmail.com",
    "FirstName": "Testing",
    "LastName": "Testing"
}`

**Expected behavior**
It should add the contact details into CRM 

Error Message:
<img width="608" alt="image" src="https://github.com/SSWConsulting/SSW.Website-v3/assets/71385247/e6f6a1ed-d204-4c90-b48c-6aa95dafe749">

**Figure: Error msg in raw json**

**Screenshots/Video**
<img width="953" alt="image" src="https://github.com/SSWConsulting/SSW.Website-v3/assets/71385247/b2c97c56-b0b6-438c-ba5e-c9157abbd42a">

**Figure: Error message on Power Automate GUI**

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud 
The newsletters endpoint was not working because the Company field was a required on Production whereas it was an optional field on the Dev environment.

While testing it on UAT, we also encountered a connection references issue on UAT, which also got resolved with the help of @AshAnil and @zl24622.

While testing we discovered that our Dev and UAT environments were not updated with Production.

- Now our Dev and UAT env are updated with Production
- We use UAT to test it before deploying it to Production
