### ISSUE TITLE
Newsletters - Configure Key vault Secrets

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#689]
```[tasklist]
### Tasks
- [x] Add secrets in the key vault for Dev and Prod endpoint
- [x] Update the App settings to accommodate new changes for the endpoint
- [x] Remove the hardcoded URL from the code
```
