### ISSUE TITLE
💄Newsletter Page- styling

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#707]
URL: https://ssw.com.au/newsletters

As per my conversation with @wicksipedia and @bradystroud, our current newsletters' design is not as per modern standards therefore we need to do the following changes to Newsletters component.

```[tasklist]
### Tasks
- [ ] Get designer feedback
- [ ] Newsletters - remove button from the component name
- [ ] Newsletters - Restyle based on Training page
- [ ] Add hero image (Testimonial style)
```

**Comment by KristenHu** [comment]
Reskin newsletter sign up component to look like

![image](https://github.com/SSWConsulting/SSW.Website/assets/52522913/21ea2b26-5492-40a4-a9cc-2736f15510e2)

Note: should be able to use Tina to drop component on other pages e.g. home page

**Comment by hveraus** [comment]
Hi guys, Test please for the Newsletter Page- styling, 

**New things:**

1. New banner area, with sign up form on top
- 2 options with image of Adam doing technews and polygon bg

2. New testimonial section
- 2 mockups with 3 people and 1

3. New table styling, more padding, margin and color


![image](https://github.com/SSWConsulting/SSW.Website/assets/4745861/edf27daf-e025-478d-953e-bb506f32d5dd)
![image](https://github.com/SSWConsulting/SSW.Website/assets/4745861/af41ef24-a0bb-4472-a6ed-dbf60e62d993)

See figma here - https://www.figma.com/file/6IU1jg9Stosfecs4YfawoR/SSW-Website-v3?type=design&node-id=2634-8585&t=Crm2v6i5Bcfa7mDm-4

**Comment by KristenHu** [comment]
Hi Guys, as per the conversation in Teams, this part will be removed.
![Weixin Screenshot_20230620152136](https://github.com/SSWConsulting/SSW.Website/assets/52522913/208a445d-0f4b-402a-a27e-9f8078da4647)
