### ISSUE TITLE
🎥 - Done Video - Create leads - logging and failover 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#708]
### Description:
We need to record a done video to show how are we logging and handling connection references error for our newly created Power Automate flow for leads.

```[tasklist]
### Tasks
- [x] Set up an environment where the flow can fail
- [x] Test pass the video
- [x] Reset the environment
```

**Comment by amankumarrr** [comment]
As per my conversation with @bradystroud, he passed my done video - https://www.youtube.com/watch?v=mMmCa0ZfxKo and after resetting the dev environment for the flow I will close this issue.

**Comment by amankumarrr** [comment]
closing this as I've completed all the tasks associated with it.
