### ISSUE TITLE
📄🎥 Newsletters - How to upload?

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#712]
Now that the newsletter page is complete, we need to train users (primarily Penny) on how to upload new newsletters.

```[tasklist]
### Tasks
- [x] On a Teams call with Penny, walk her through the upload process of the May newsletter (currently missing)
- [x] Record the call, answer any questions she has
- [x] Upload to youtube and add it to the Wiki
- [ ] Send email to stakeholders
```

**Comment by Harry-Ross** [comment]
Completed the demo video - https://youtu.be/lrgF3T7Y0Qs

**Comment by Harry-Ross** [comment]
As per the email from @adamcogan, here is his feedback:

1. Start with a tab of past newsletters
2. Start with a tab of Tina CMS
3. Start with a newsletter rule
3. Talk generically
4. Show a 2024-Jan newsletter 
5. Show creating a 2024-Feb newsletter 
6. I would have the branch name and PR name the same - doubt there is a need to be different (check with Brady and Wicksy)
7. Now you would send it with MailChimp or Campaign Monitor or Sendgrid ?
8. When recording try to have a TV guys + practice your intro and closing
9. Full screen at the start and the end
10. Record upstairs if it is noisy

Status: right now, I am blocked on completing a v2 - as @bradystroud and I plan to re-do a lot of the newsletter functionality as per #1070
