### ISSUE TITLE
🤖 Front Door - Route for newsletters

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#713]
Action once #712 is complete

```[tasklist]
### Tasks
- [x] redirect https://www.ssw.com.au/ssw/NETUG/SSWUpdatePrevious.aspx to https://www.ssw.com.au/newsletters
- [x] Deploy Front Door
- [x] Update the item in the megamenu
```

**Comment by KristenHu** [comment]
> redirect https://www.ssw.com.au/ssw/NETUG/SSWUpdatePrevious.aspx to https://www.ssw.com.au/newsletters

Ready to merge - https://github.com/SSWConsulting/SSW.FrontDoor/pull/47

**Comment by bradystroud** [comment]
Closing as all the work is done :)
