### ISSUE TITLE
💸 Tech Debt - App Insight throwing error 404

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#727]
**Description**  
We recently added App Insight logging for our application, and it seems like we are hitting files that don't exist anymore with their relative path, need to investigate this.

```[tasklist]
### Tasks
- [x] Investigate the cause
- [x] Fix the issue
- [x] Monitor after a fix to see there isn't any 404 error
```

<img width="1040" alt="dashboardErrors" src="https://github.com/SSWConsulting/SSW.Website-v3/assets/71385247/01fe6d09-9120-42dc-9f46-79ce63b8324c">

**Figure: AppInsight Dashboard showing the failure** 

<img width="1262" alt="Failures" src="https://github.com/SSWConsulting/SSW.Website-v3/assets/71385247/915876a5-1b59-40b4-b8b3-9b298c764487">

**Figure: AppInsight | Failures - Relative path of the files and occurrence of errors**

**Comment by bradystroud** [comment]
As discussed, I think this will be a problem with https://github.com/SSWConsulting/SSW.MegaMenu, not the website.

**Comment by bradystroud** [comment]
To fix, we should upgrade to the latest version of the megamenu

- [x] Update megamenu
- [x] Wait a day then check app insights, any errors?

**Comment by bradystroud** [comment]
Done - The MegaMenu was updated and this resolved most of the 404s

![](https://github.com/SSWConsulting/SSW.Website/assets/38869720/b941f486-331d-4235-ad0e-e12ebd00c4b3)
**Figure: Big drop in errors after updating the menu**

Remaining errors are a seperate issue.
