### ISSUE TITLE
✨ AppInsight - Add email alert for a critical exception 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#729]
### Description:
We have implemented exception handling and logging in our App Insight app. However, there is a possibility that we may not be able to promptly check exceptions if there are failures from third-party resources. To ensure timely awareness, it is crucial that we notify the SysAdmins and Dev team whenever high-severity exceptions occur.

```[tasklist]
### Tasks
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/736
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/724
- [x] Set up an email alert in App Insight
- [x] Done video for this alert emails
```

**Comment by amankumarrr** [comment]
cc @adamcogan @bradystroud 

I have tested a scenario where our Power Automate flow is turned off or our website is unable to communicate with the flow. I ensured error-free and logical handling for these situations. Notifications and alerts are set up to notify relevant developers and SysAdmins when the flow is inactive. 

Here is the done video and it test passed by @bradystroud - https://www.youtube.com/watch?v=6WjoI8D6m5o



![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/1a716bf9-6678-48ce-a76a-41d75c7a4a9a)
**Figure: Email template for Azure alert on exception**

**Comment by amankumarrr** [comment]
As per my discussion with @bradystroud, I've completed all the task of this issue and have sent out the email for the done video, therefore, I'm closing this issue.
