### ISSUE TITLE
💸 Tech Debt - Need to update the RECAPTHCA keys 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#759]
**Description**  
In our code, we currently have two variables, Google_RECAPTCHA_SITE_KEY and Google_RECAPTCHA_KEY, which are referencing the same site key. Additionally, we have another variable named Google_RECAPTCHA_KEY_v2, which holds the actual reCAPTCHA key. To ensure consistency, we should remove the version number and make the variable names consistent throughout the codebase.

```[tasklist]
### Tasks
- [x] Replace Google_RECAPTCHA_KEY key with Google_RECAPTCHA_SITE_KEY
- [x] Remove suffix in Google_RECAPTCHA_KEY_v2
- [x] Update the Biceps where we are adding them into our App Settings.
```
