### ISSUE TITLE
✨ Home template - Click to edit visual editing

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#839]
Feature: https://tina.io/docs/contextual-editing/react/#click-to-edit-experimental
URL: https://ssw.com.au
Route: `/`

#### Description:
Tina introduced a new exciting feature where user can edit the content by simply clicking on it, we need to implement this feature for our website and need to ensure that we follow this for our upcoming templates.

```[tasklist]
### Tasks
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/870
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/873
- [x] Component - About Us
- [x] Component - Content
- [x] Component - Built on Azure
```
