### ISSUE TITLE
📄 Consulting - Video Production Services 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#880]
We need a new template for these pages

Investigate if we can put these pages on

`consulting/video-production/*`

if not, we can put them on

`/video-production`

URL: https://www.ssw.com.au/ssw/Consulting/Video-Production/Video-Production-Product-Services.aspx

```[tasklist]
### Tasks
- [x] migrate this page.
- [x] Update links on https://www.ssw.com.au/consulting/video-production
- [x] Add redirect to Front Door
- [x] Check if there is a megamenu link to update
```
