### ISSUE TITLE
🐛 PR - Fix check to ensure main infra code works

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#897]
**Describe the bug**
There is a failing check https://github.com/SSWConsulting/SSW.Website/actions/workflows/pr-infra.yml

```[tasklist]
### Tasks
- [x] Fix the title
- [x] Fix the triggers (change to PR)
- [x] Add the missing parameters
```
