### ISSUE TITLE
💸 Tech Debt - Performance Issue due to 1st party scripts 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#910]
**Description**  
Reduce unused JavaScript and defer loading scripts until they are required to decrease bytes consumed by network activity.

<img width="630" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/168cde6f-07c2-4fd8-ab67-f1b1a9aa5294">

**Figure: 1st party javascript being loaded**  

```[tasklist]
### Tasks
- [x] Find the solution to remove unsed Javascripts
- [x] Fix the problem
- [x] Monitor it after implementing the solution
```

**Comment by Harry-Ross** [comment]
As per my conversation with @bradystroud, I am planning to remove `react-player`, as the bundle size for that package is unneedingly large for the simple task of displaying YouTube videos.

**Comment by Harry-Ross** [comment]
Done - here is the done video: https://www.youtube.com/watch?v=FR_2gzjm0xk
