### ISSUE TITLE
✨ Booking form - improve email sent to client

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#924]
When clients submit the initial meeting form, an email is sent to account mananger and the client.

The email looks like this

> Dear Account Managers,
> 
> 
> The relevant Account Manager (based on State) should call this client immediately.
> 
> Consulting enquiry from [https://www.ssw.com.au/educational](https://www.ssw.com.au/educational) 
> Company: test 
> Country: Australia 
> State: QLD 
> Name: Brady Stroud 
> Phone: 0437244049 
> Email: [bradystroud@me.com](mailto:bradystroud@me.com) 
> Note: test 
> 
> ----------This lead is generated from website enquiry form---------- 
> 
> [https://ssw.crm6.dynamics.com:443/main.aspx?etc=4&id=30907a4c-e516-ee11-9cbd-6045bd3df5f9&histKey=787371842&newWindow=true&pagetype=entityrecord](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fssw.crm6.dynamics.com%2Fmain.aspx%3Fetc%3D4%26id%3D30907a4c-e516-ee11-9cbd-6045bd3df5f9%26histKey%3D787371842%26newWindow%3Dtrue%26pagetype%3Dentityrecord&data=05%7C01%7Cbradystroud%40ssw.com.au%7C21600c7377b04e75232e08db7aa514c4%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638238621672921345%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=D9yZf8cj2ZLh2FEpZ6I39nbeBfdWAjKEBbdY2d38Ttw%3D&reserved=0) 
> 
> Dear Brady Stroud,
> 
> Thank you for your inquiry. 
> We will be in contact soon. In the meantime, please have a look at our [Consulting Services](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Fssw%2Fconsulting%2F&data=05%7C01%7Cbradystroud%40ssw.com.au%7C21600c7377b04e75232e08db7aa514c4%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638238621672921345%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ojx4BR16owLxu9iHMON6pkjnedOAgPaP2O10F2KWTp8%3D&reserved=0) and [People](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Fpeople%2F&data=05%7C01%7Cbradystroud%40ssw.com.au%7C21600c7377b04e75232e08db7aa514c4%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638238621672921345%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XaHKbJsCP%2FXLbGN6yJKbe%2FsCppNHNic0qrxVogfUnN0%3D&reserved=0).
> 

As per my conversation with @PennyWalker we agreee its strange for the client to receive this email.

```[tasklist]
### Tasks
- [x] Update the email format
```
- [ ] ~Send a different email to the client, format it nicer~
- [ ] ~Maybe include some marketing stuff e.g. video links~
- [ ] ~Checked by Penny~

**Comment by amankumarrr** [comment]
@wicksipedia 

As per my conversation with @UlyssesMaclaren and @PennyWalker, we've decided not to send a separate email to the client. Instead, we'll swap the sections, placing the client's information at the top and the Account Manager's details at the end. I'll collaborate with @tiagov8 to format it more nicely.

**Comment by tiagov8** [comment]
Hi @amankumarrr 

As per our conversation, to start, let's improve the email formatting as per below:

1. Change from: 

> **Subject: Consulting enquiry - Northwind – Tiago Araujo**

> Dear Account Managers,
> 
> 
> The relevant Account Manager (based on State) should call this client immediately.
> 
> Consulting enquiry from [https://www.ssw.com.au/company/contact-us](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Fcompany%2Fcontact-us&data=05%7C02%7CTiagoAraujo%40ssw.com.au%7Cd0d9723bdec34e8e398708dc3737dd4b%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638445960286070336%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=mEghD30y5bawD%2F%2BK7MJQWXCx71orJfpePcG9WSQFKcU%3D&reserved=0)
> Company: Northwind
> Country: USA
> State: Other
> Name: Tiago Araujo
> Referral Source: Other
> Phone: 6044458103
> Email: [tiagov8@gmail.com](mailto:tiagov8@gmail.com)
> Note: I would like to test this form response :)
> 
> ----------This lead is generated from website enquiry form----------
> 
> [https://ssw.crm6.dynamics.com:443/main.aspx?etc=4&id=d65588f2-8843-ee11-be6f-6045bd3df09b&histKey=787371842&newWindow=true&pagetype=entityrecord](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fssw.crm6.dynamics.com%2Fmain.aspx%3Fetc%3D4%26id%3Dd65588f2-8843-ee11-be6f-6045bd3df09b%26histKey%3D787371842%26newWindow%3Dtrue%26pagetype%3Dentityrecord&data=05%7C02%7CTiagoAraujo%40ssw.com.au%7Cd0d9723bdec34e8e398708dc3737dd4b%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638445960286076207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=zLlUkbriHXgchmndbuBVH1tVFgurlKmWGzP3HSpjLao%3D&reserved=0)
> 
> Dear Tiago,
> 
> Thank you for your inquiry.
> We will be in contact soon. In the meantime, please have a look at our [Consulting Services](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Fssw%2Fconsulting%2F&data=05%7C02%7CTiagoAraujo%40ssw.com.au%7Cd0d9723bdec34e8e398708dc3737dd4b%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638445960286082379%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Oh3DCWuGxNYTc121ZIh8e63HCDcRc%2BpMmKZb7petCF4%3D&reserved=0) and [People](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Fpeople%2F&data=05%7C02%7CTiagoAraujo%40ssw.com.au%7Cd0d9723bdec34e8e398708dc3737dd4b%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638445960286087993%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=L3sph6LD0CihBjCFPrHU81%2B5is%2Fs%2F0zbqpgNmmBRZDo%3D&reserved=0).

 
to

> **Subject: Consulting enquiry by Tiago Araujo Northwind**

> ### Hello Tiago,
> 
> Thank you for reaching out to us. Your interest in SSW is appreciated. We're eager to connect with you and discuss how we can assist you further.
> 
> In the meantime, check out our [Consulting Services](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Fssw%2Fconsulting%2F&data=05%7C02%7CTiagoAraujo%40ssw.com.au%7Cd0d9723bdec34e8e398708dc3737dd4b%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638445960286093536%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=3db2qCPnm8X4MuMwmmPDks23I1ojZiWMJ0GiV2BCLBE%3D&reserved=0) and meet our [People](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Fpeople%2F&data=05%7C02%7CTiagoAraujo%40ssw.com.au%7Cd0d9723bdec34e8e398708dc3737dd4b%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638445960286099030%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=cVkmk3Z3meLIu%2Bsw1Mt%2Ft58RsEuma%2F7wWXFTUwVEQwU%3D&reserved=0).
> 
> ### Hi Account Managers,
> 
> The {{ STATE }} Account Manager should call {{ CLIENT NAME }} ASAP to explore how we can best serve their needs.
> 
> **Name:** Tiago Araujo
> **Company:** Northwind
> **Phone:** 6044458103
> **Email:** [tiagov8@gmail.com](mailto:tiagov8@gmail.com)
> **Location:** USA
> **State:** Other
> **Referral Source:** Other
> **Message:** I would like to test this form response :)
> 
> See the [CRM lead generated from this contact form](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fssw.crm6.dynamics.com%2Fmain.aspx%3Fetc%3D4%26id%3Dd65588f2-8843-ee11-be6f-6045bd3df09b%26histKey%3D787371842%26newWindow%3Dtrue%26pagetype%3Dentityrecord&data=05%7C02%7CTiagoAraujo%40ssw.com.au%7Cd0d9723bdec34e8e398708dc3737dd4b%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638445960286104536%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=uT132DrLjc8itvjFdHvDrGXnrGe2icgYjOB94BVcd48%3D&reserved=0)

**Comment by amankumarrr** [comment]
Hi @tiagov8, 

Regarding the statement 
> The {{ STATE }} Account Manager should call {{ CLIENT NAME }} asap to explore how we can best serve their needs,  

I believe we should maintain the current version, as the state can also be "Other," where this version would make more sense.

Something like this 
> The relevant Account Manager (based on the state) should call {{ Tiago Araujo }} as soon as possible to explore how we can best serve their needs."

Additionally, I think it's essential to include the **Consulting enquiry source** in the lead email.

Please let me know your thoughts on these points.

Here is how it looks after those changes. 

![Tiago's Feedback Design](https://github.com/SSWConsulting/SSW.Website/assets/71385247/4ffc2757-4031-4c9e-84a1-b90c0236443d)

**Figure: Client lead email in the outlook**

**Comment by tiagov8** [comment]
@amankumarrr 

Yes, agreed with your points.

1. Can you add a link to Case Studies in the 2nd sentence...

E.g.
In the meantime, check out our **Consulting Services**, see our **Clients' Case Studies**, and meet our **People**.

**Comment by tiagov8** [comment]
1. For the last part.. I would change from

> ----------This lead is generated from website enquiry form----------
> See the [CRM lead generated from this contact form](#)

to

> --- [See the CRM Lead](#) generated by this SSW.Website inquiry ---


--

FYI 

ChatGPT:

_The words "enquiry" and "inquiry" are often used interchangeably, but there is a slight difference in usage depending on regional variations:
**Enquiry:** This spelling is more commonly used in British English and is often preferred in formal contexts. It refers to the act of asking for information or seeking clarification.
**Inquiry:** This spelling is more commonly used in American English but is also widely accepted in British English. It generally refers to an official investigation or formal inquiry into a matter.
In everyday usage, however, the distinction between "enquiry" and "inquiry" is minimal, and either spelling can be used regardless of regional differences. It's more important to be consistent with the chosen spelling within a document or communication._

**Comment by tiagov8** [comment]
2. Both "asap" and "ASAP" are acceptable, but "ASAP" is generally preferred in professional communication because it is an acronym for "as soon as possible." Using "ASAP" in uppercase letters emphasizes the urgency of the request or action, making it clearer and more formal.

Consider updating that part in the text

**Comment by amankumarrr** [comment]
@PennyWalker @UlyssesMaclaren @wicksipedia @bradystroud 

As per my conversation with @tiagov8, he is happy with the following email template and is also test passed by @UlyssesMaclaren 
<img width="765" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/169030ba-c8c7-4725-9aad-3054d7da49c5">

**Figure: lead email in outlook**

**Comment by amankumarrr** [comment]
Closing this issue as there is no further changes required for the lead email.
