### ISSUE TITLE
✨ T&Cs - Add subheadings to the table

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#939]
cc @pierssinclairssw @UlyssesMaclaren

https://www.ssw.com.au/terms-and-conditions

<img width="1331" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/38869720/6b1d2287-42fc-49ab-bac4-f2b54de0e531">

**Figure: ❌ Too many rows makes this table hard to read**

![image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/e6a16cae-71ef-47d4-a960-ef34c1d62b76)
**Figure: ✅ Subheadings seperate sections**

```[tasklist]
### Tasks
- [x] Allow users to add subheadings to categorise roles in the table using Tina
- [x] Add subheadings - Developers, SysAdmins, Designers, TV + Marketing
- [x] Seperate Data Engineers and Software Engineers
- [x] Checked by Brady then Piers
- [ ] Complete Done Video v2 for combined #939 and #933
```

**Comment by bradystroud** [comment]
reopening because there is 1 task remaining 🎥👀 @Harry-Ross
