### ISSUE TITLE
🐛 Educational - Cannot edit Solutions in Tina

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#942]
cc @tiagov8 

1. Go to https://www.ssw.com.au/admin/index.html#/collections/edit/educational/educational
2. Scroll down and click "Educational Solutions"
3. Click ✏️ to edit an item
4. Nothing happens 🤷

```[tasklist]
### Tasks
- [x] Allow them to be edited
- [x] Use the content of the item as the UI title in Tina
- [x] Why cant we see the page on the right when editing?
```

![Image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/3ec564ab-04ad-4424-9c2f-a08564cec2d5)

**Comment by amankumarrr** [comment]
@bradystroud  @wicksipedia 

I have changed the schema from an object type to a three-item row in order to make it editable. This change was necessary due to a bug in Tina CMS, where using an object inside the rich text editor would redirect to a blank page. Considering our current use case, it is more practical to use a fixed items approach, as it allows for easier modification. I have raised this issue in Tina's Discord community for further assistance and discussion. You can find the details of the issue in the following thread:

https://discord.com/channels/835168149439643678/1069976809950683177/threads/1128126883532378216
