### ISSUE TITLE
✨ Rewards page - update old links

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#969]
https://www.ssw.com.au/ssw/Rewards/

```[tasklist]
### Tasks
- [x] Add a redirect to front door
- [x] Update the link on the mega menu
- [ ] Update the link on the app store record
```

![Image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/a4529cd3-694f-4618-afa4-66c4b9d496b6)

**Comment by jackreimers** [comment]
As per my discussion with @bradystroud, the app store listings will not be updated as it will be painful and the link has a redirect so users can still navigate to it.
